# This notebook serves as a template for cleaning the original text data and saving the train/test splits to Parquet files rather than csv

In [1]:
# !pip install nltk

# !pip install pyspellchecker

# !pip install textblob

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [2]:
train.head()

  essay_id                                          full_text  score
0  000d118  Many people have car where they live. The thin...      3
1  000fe60  I am a scientist at NASA that is discussing th...      3
2  001ab80  People always wish they had the same technolog...      4
3  001bdc0  We all heard about Venus, the planet without a...      4
4  002ba53  Dear, State Senator\n\nThis is a letter to arg...      3

In [3]:
test.head()

  essay_id                                          full_text
0  000d118  Many people have car where they live. The thin...
1  000fe60  I am a scientist at NASA that is discussing th...
2  001ab80  People always wish they had the same technolog...

In [4]:
# def preprocess_text(df, col = 'full_text'):

#     df['paragraph'] = df[col].str.split('\n\n')

#     return df


# train = preprocess_text(train)

# train.head()

In [5]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import string
from spellchecker import SpellChecker
from textblob import TextBlob

# # Set the download location to Kaggle's working directory
# download_dir = '/kaggle/working/nltk_data'

# # Add this download directory to nltk's data path
# if download_dir not in nltk.data.path:
#     nltk.data.path.append(download_dir)

# Download necessary datasets from NLTK
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('omw-1.4')
nltk.download('universal_tagset')
nltk.download('maxent_ne_chunker')
nltk.download('words')

# Now check if the directory is correctly set and files are present
# import os
# print(os.listdir(download_dir))  # This should show the downloaded files

[nltk_data] Downloading package punkt to /home/laptop/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/laptop/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/laptop/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/laptop/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to /home/laptop/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package universal_tagset to
[nltk_data]     /home/laptop/nltk_data...
[nltk_data]   Package universal_tagset is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /home/laptop/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /home/laptop/nltk_data...
[nltk_data]   Package words is already up-to-date!

True

In [6]:
# import zipfile
# import os

# # Path to the zip file
# zip_path = '/kaggle/working/nltk_data/corpora/wordnet.zip'

# # Target extraction directory
# extract_dir = '/kaggle/working/nltk_data/corpora/wordnet'

# # Create the target directory if it doesn't already exist
# if not os.path.exists(extract_dir):
#     os.makedirs(extract_dir)

# # Extract the zip file
# with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#     zip_ref.extractall(extract_dir)

# # Verify the files have been extracted
# print(os.listdir(extract_dir))  # Should show the contents of the wordnet corpus

In [7]:
# import os
# import shutil

# # Set the source and target directories
# source_dir = '/kaggle/working/nltk_data/corpora/wordnet/wordnet'
# target_dir = '/kaggle/working/nltk_data/corpora/wordnet'

# # Move each file and subdirectory from the source to the target directory
# for filename in os.listdir(source_dir):
#     source_file = os.path.join(source_dir, filename)
#     target_file = os.path.join(target_dir, filename)
#     if os.path.isdir(source_file):
#         if os.path.exists(target_file):
#             shutil.rmtree(target_file)  # Remove if target directory already exists
#         shutil.move(source_file, target_dir)
#     else:
#         if os.path.exists(target_file):
#             os.remove(target_file)  # Remove if target file already exists
#         shutil.move(source_file, target_dir)

# # Clean up the now empty source directory
# os.rmdir(source_dir)

# # Verify the structure
# print(os.listdir(target_dir))  # Should list 'lexnames' among other files

In [8]:
# import os
# from tqdm import tqdm

# # List of file paths to unzip
# embeddings = ['data/archive.zip']

# def unzip_embeddings(file_paths):
#     """
#     Unzip a list of files.

#     Args:
#         file_paths (list): List of file paths to unzip.

#     Returns:
#         None
#     """
#     # Initialize tqdm with the total number of files to unzip
#     with tqdm(total=len(file_paths)) as pbar:
#         for emb in file_paths:
#             # Use the -o flag to automatically replace files
#             if os.system(f'unzip -o {emb} -d data/') == 0:
#                 print(f"Inflating {emb} successful.")
#             else:
#                 print(f"Inflating {emb} failed.")
#             pbar.update(1)  # Update the progress bar

# # Call the function to unzip files
# unzip_embeddings(embeddings)

In [9]:
def embedding_checks(df, glove_path, paragram_path, wiki_news_path, col_name = 'clean_text'):

    """
    Preprocesses text for both training and testing datasets. 
    Includes loading embeddings, building vocabularies, cleaning text among other things.
    
    :param summaries_train: DataFrame with the training data
    :param summaries_test: DataFrame with the testing data
    :param glove_path: path to the GloVe embedding
    :param paragram_path: path to the Paragram embedding
    :param wiki_news_path: path to the Wiki News embedding
    
    :return: Preprocessed DataFrame and list of out-of-vocab words
    """

    import tqdm 

    def load_embed(file):
        """
        Load the embeddings from a file.
        """
        print(f"Loading embeddings from {file}")
        
        def get_coefs(word, *arr): 
            return word, np.asarray(arr, dtype='float32')
        
        if file == wiki_news_path:
            embeddings_index = dict(get_coefs(*o.split(" ")) for o in tqdm(open(file), "Reading Embedding File") if len(o)>100)
        else:
            embeddings_index = dict(get_coefs(*o.split(" ")) for o in tqdm(open(file, encoding='latin'), "Reading Embedding File"))
        
        print(f"Loaded embeddings from {file}")
        return embeddings_index

    # Load embeddings
    print("Loading all embeddings.")
    embed_glove = load_embed(glove_path)
    embed_paragram = load_embed(paragram_path)
    embed_fasttext = load_embed(wiki_news_path)
    print("All embeddings loaded.")
    
    def build_vocab(texts):
        """
        Build a vocabulary from a given list of texts.
        """
        print("Building vocabulary.")
        sentences = texts.apply(lambda x: x.split()).values
        vocab = {}
        for sentence in tqdm(sentences, "Populating Vocabulary"):
            for word in sentence:
                try:
                    vocab[word] += 1
                except KeyError:
                    vocab[word] = 1
        print("Vocabulary built.")
        return vocab

    def check_coverage(vocab, embeddings_index):
        """
        Check which words in the vocabulary are covered by the embeddings.
        """
        print("Checking coverage.")
        known_words = {}
        unknown_words = {}
        nb_known_words = 0
        nb_unknown_words = 0
        for word in tqdm(vocab.keys(), "Checking Words"):
            try:
                known_words[word] = embeddings_index[word]
                nb_known_words += vocab[word]
            except:
                unknown_words[word] = vocab[word]
                nb_unknown_words += vocab[word]
                pass
        unknown_words = sorted(unknown_words.items(), key=operator.itemgetter(1))[::-1]
        print("Coverage checked.")
        return unknown_words

    # Build and check vocab for train and test datasets
    print("Processing train and test datasets.")
    
    vocab_train = build_vocab(df[col_name])
    
    oov_glove_train = check_coverage(vocab_train, embed_glove)
    oov_paragram_train = check_coverage(vocab_train, embed_paragram)
    oov_fasttext_train = check_coverage(vocab_train, embed_fasttext)
  
    print("Processed train and test datasets.")
    
    
    # Rebuild and check vocab after cleaning contractions
    
#     vocab_train_clean = build_vocab(df['clean_text'])
    
#     oov_glove_train = check_coverage(vocab_train_clean, embed_glove)
#     oov_paragram_train = check_coverage(vocab_train_clean, embed_paragram)
#     oov_fasttext_train = check_coverage(vocab_train_clean, embed_fasttext)


    return df, oov_glove_train, oov_paragram_train, oov_fasttext_train

In [10]:
# Preprocessing
import numpy as np
import pandas as pd
import operator
from spellchecker import SpellChecker
from tqdm import tqdm  # Import tqdm
import re

def clean_text(df, col_name = 'full_text'):
    """
    Preprocesses text for both training and testing datasets. 
    Includes loading embeddings, building vocabularies, cleaning text among other things.
    
    :param summaries_train: DataFrame with the training data
    :param summaries_test: DataFrame with the testing data
    :param glove_path: path to the GloVe embedding
    :param paragram_path: path to the Paragram embedding
    :param wiki_news_path: path to the Wiki News embedding
    
    :return: Preprocessed DataFrame and list of out-of-vocab words
    """
    print("Starting text cleaning process. \n")


    
    # Lowercase all texts

    df['lowered'] = df[col_name].apply(lambda x: x.lower())

    
    # Handle contractions
    contraction_mapping = {"ain't": "is not", "aren't": "are not","can't": "cannot", "'cause": "because", "could've": "could have", "couldn't": "could not", 
                           "didn't": "did not",  "doesn't": "does not", "don't": "do not", "hadn't": "had not", "hasn't": "has not", "haven't": "have not", 
                           "he'd": "he would","he'll": "he will", "he's": "he is", "how'd": "how did", "how'd'y": "how do you", "how'll": "how will", "how's": "how is",  
                           "I'd": "I would", "I'd've": "I would have", "I'll": "I will", "I'll've": "I will have","I'm": "I am", "I've": "I have", "i'd": "i would", 
                           "i'd've": "i would have", "i'll": "i will",  "i'll've": "i will have","i'm": "i am", "i've": "i have", "isn't": "is not", "it'd": "it would", 
                           "it'd've": "it would have", "it'll": "it will", "it'll've": "it will have","it's": "it is", "let's": "let us", "ma'am": "madam", 
                           "mayn't": "may not", "might've": "might have","mightn't": "might not","mightn't've": "might not have", "must've": "must have", 
                           "mustn't": "must not", "mustn't've": "must not have", "needn't": "need not", "needn't've": "need not have","o'clock": "of the clock", 
                           "oughtn't": "ought not", "oughtn't've": "ought not have", "shan't": "shall not", "sha'n't": "shall not", "shan't've": "shall not have", 
                           "she'd": "she would", "she'd've": "she would have", "she'll": "she will", "she'll've": "she will have", "she's": "she is", 
                           "should've": "should have", "shouldn't": "should not", "shouldn't've": "should not have", "so've": "so have","so's": "so as", 
                           "this's": "this is","that'd": "that would", "that'd've": "that would have", "that's": "that is", "there'd": "there would", 
                           "there'd've": "there would have", "there's": "there is", "here's": "here is","they'd": "they would", "they'd've": "they would have", 
                           "they'll": "they will", "they'll've": "they will have", "they're": "they are", "they've": "they have", "to've": "to have", 
                           "wasn't": "was not", "we'd": "we would", "we'd've": "we would have", "we'll": "we will", "we'll've": "we will have", "we're": "we are", 
                           "we've": "we have", "weren't": "were not", "what'll": "what will", "what'll've": "what will have", "what're": "what are",  "what's": "what is",
                           "what've": "what have", "when's": "when is", "when've": "when have", "where'd": "where did", "where's": "where is", "where've": "where have",
                           "who'll": "who will", "who'll've": "who will have", "who's": "who is", "who've": "who have", "why's": "why is", "why've": "why have", 
                           "will've": "will have", "won't": "will not", "won't've": "will not have", "would've": "would have", "wouldn't": "would not", 
                           "wouldn't've": "would not have", "y'all": "you all", "y'all'd": "you all would","y'all'd've": "you all would have","y'all're": "you all are",
                           "y'all've": "you all have","you'd": "you would", "you'd've": "you would have", "you'll": "you will", "you'll've": "you will have", 
                           "you're": "you are", "you've": "you have" }
    
    
    def clean_contractions(text, mapping):
        """
        Replace contractions in the text based on a given mapping.
        
        :param text: The original text
        :param mapping: Dictionary containing contractions mapping
        
        :return: Text with contractions replaced
        """
        
        specials = ["’", "‘", "´", "`"]
        
        for s in specials:
            text = text.replace(s, "'")
        text = ' '.join([mapping[t] if t in mapping else t for t in text.split(" ")])
        return text

    # Apply contraction cleaning to train and test datasets

    df['cleaned_text'] = df['lowered'].apply(lambda x: clean_contractions(x, contraction_mapping))
    
    
        
    punct = "/-'?!.,#$%\'()*+-/:;<=>@[\\]^_`{|}~" + '""“”’' + '∞θ÷α•à−β∅³π‘₹´°£€\×™√²—–&'
    
    punct_mapping = {"‘": "'", "₹": "e", "´": "'", "°": "", "€": "e", "™": "tm", "√": " sqrt ", "×": "x", "²": "2", "—": "-", "–": "-", "’": "'", "_": "-",
                     "`": "'", '“': '"', '”': '"', '“': '"', "£": "e", '∞': 'infinity', 'θ': 'theta', '÷': '/', 'α': 'alpha', '•': '.', 'à': 'a', '−': '-', 
                     'β': 'beta', '∅': '', '³': '3', 'π': 'pi', }

    def clean_special_chars(text, punct, mapping):
        for p in mapping:
            text = text.replace(p, mapping[p])
        for p in punct:
            text = text.replace(p, f' {p} ')
        specials = {'\u200b': ' ', '…': ' ... ', '\ufeff': '', 'करना': '', 'है': ''}  
        for s in specials:
            text = text.replace(s, specials[s])
        return text

    df['clean_text'] = df['cleaned_text'].apply(lambda x: clean_special_chars(x, punct, punct_mapping))

    # def correct_spelling(text):
    #     """
    #     Corrects the spelling of words in the provided text.

    #     :param text: The text to be spell-checked.
    #     :return: The text with corrected spelling.
    #     """
    #     spell = SpellChecker()
    #     words = text.split()  # Tokenize the text into words
    #     corrected_words = [spell.correction(word) for word in words]
    #     corrected_text = ' '.join(corrected_words)
    #     return corrected_text
    
    # df['clean_text'] = df['clean_text'].apply(lambda x: correct_spelling(x))


    return df

In [11]:
# time the run time

import time

start = time.time()

# Clean the train and test text data

train = clean_text(train, col_name = 'full_text')


end = time.time()

print(f"Time taken to clean text: {end - start} seconds")

Starting text cleaning process.

Time taken to clean text: 1.0322492122650146 seconds

In [12]:
glove_path = '/home/laptop/github/kaggle/scoring/data/glove-840B-300d.txt'
paragran_path = '/home/laptop/github/kaggle/scoring/data/paragram-300-sl999.txt'
fastetxt_path = '/home/laptop/github/kaggle/scoring/data/wiki-news-1M-300d.vec'


# Rebuild and check vocab after cleaning contractions

train, glove, paragram, fastetxt = embedding_checks(train, glove_path, paragran_path, fastetxt_path, col_name='clean_text')

Loading all embeddings.
Loading embeddings from /home/laptop/github/kaggle/scoring/data/glove-840B-300d.txt

TypeError: 'module' object is not callable

In [ ]:
from transformers import pipeline, AutoTokenizer

# Initialize the BERT model and tokenizer
model_name = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_name)
fill_mask = pipeline('fill-mask', model=model_name)

def bert_spell_check_chunked(text):
    max_length = tokenizer.model_max_length - 2  # Subtracting 2 for special tokens [CLS] and [SEP]
    tokens = tokenizer.tokenize(text)
    chunk_size = max_length

    # Splitting tokens into chunks
    chunks = [tokens[i:i + chunk_size] for i in range(0, len(tokens), chunk_size)]

    corrected_text = ''
    for chunk in chunks:
        chunk_text = tokenizer.convert_tokens_to_string(chunk)
        masked_sentence = chunk_text.replace(chunk_text, '[MASK]')
        prediction = fill_mask(masked_sentence)[0]['sequence']
        corrected_text += prediction + ' '

    return corrected_text

# Applying the function to each row of your DataFrame column
df['corrected_text'] = df['clean_text'].apply(bert_spell_check_chunked)

In [70]:
print(glove_train, paragram_train, fastetxt_train)
print(len(glove_train + paragram_train + fastetxt_train))

[('driveless', 1603), ('vauban', 1189), ('unrra', 476), ('bomberger', 352), ('eckman', 351), ('selsky', 299), ('heidrun', 297), ('¨', 139), ('elctoral', 129), ('diverless', 107), ('\x94', 106), ('valledupar', 92), ('drivless', 88), ('risorius', 73), ('landfrom', 66), ('venuse', 59), ('lanform', 53), ('haung', 51), ('sivak', 49), ('mockus', 46), ('eletoral', 46), ('palpabraeus', 44), ('landformation', 43), ('paragrapgh', 43), ('venuses', 41), ('vaubans', 39), ('thrun', 36), ('electorals', 35), ('elctors', 34), ('ellectoral', 32), ('heidrum', 31), ('elecoral', 31), ('technogly', 30), ('antanas', 30), ('paragrpah', 29), ('pursit', 29), ('stanislavsky', 29), ('inconclusion', 28), ('limting', 27), ('tempetures', 26), ('vensus', 25), ('electoal', 25), ('pursuiting', 24), ('electroal', 24), ('electral', 24), ('dirverless', 23), ('facail', 22), ('scienctist', 22), ('atomospheric', 22), ('driverles', 22), ('selfdriving', 21), ('paragrph', 21), ('ailens', 21), ('coyboys', 20), ('palnet', 20), ('planent', 20), ('astronmers', 20), ('intertial', 20), ('auother', 19), ('drivelss', 19), ('mesa\x97landforms', 19), ('frontails', 19), ('pharagraph', 19), ('fahrenhiet', 19), ('malfuntions', 19), ('valcanoes', 19), ('lanforms', 19), ('smartcars', 18), ('advancments', 18), ('vallys', 18), ('dangours', 18), ('pragraph', 17), ('auhtor', 17), ('elecotral', 17), ('accedents', 17), ('sulfric', 17), ('¨the', 17), ('cyndonia', 16), ('passege', 16), ('landfroms', 16), ('emitions', 16), ('drverless', 16), ('scienctists', 15), ('veuns', 15), ('automoblies', 15), ('presendent', 15), ('elcetoral', 15), ('geece', 15), ('teachnology', 15), ('nasa\x92s', 15), ('technonlogy', 15), ('driverlesss', 15), ('astonomers', 15), ('expessions', 14), ('\x93so', 14), ('eletors', 14), ('sciencetist', 14), ('presient', 14), ('segoing', 14), ('limitng', 14), ('landorm', 14), ('atomspheric', 14), ('astronaunts', 14), ('matian', 14), ('emotins', 14), ('fehrenheit', 14), ('emotionals', 14), ('determain', 13), ('intesifying', 13), ('understandment', 13), ('bagota', 13), ('sciencetists', 13), ('\x93it', 12), ('despiting', 12), ('seegoing', 12), ('vanus', 12), ('alret', 12), ('seacowboy', 12), ('electores', 12), ('whittiling', 12), ('seagiong', 12), ('huangs', 12), ('sudying', 12), ('humnas', 12), ('clostest', 12), ('conclustion', 12), ('malfuctions', 12), ('acciedent', 12), ('limmiting', 12), ('¨face¨', 12), ('vaunban', 12), ('aouthor', 12), ('emotons', 12), ('autonimous', 11), ('ascertainments', 11), ('elcetion', 11), ('whitting', 11), ('facal', 11), ('exploreing', 11), ('computure', 11), ('woudn', 11), ('transpertation', 11), ('dixide', 11), ('unhabitable', 11), ('parargraph', 11), ('exspressions', 11), ('\x93that\x92s', 11), ('pullution', 11), ('eroupe', 11), ('canadidate', 11), ('acorrding', 11), ('advanteges', 11), ('wothy', 11), ('classroms', 11), ('atronomers', 10), ('emothions', 10), ('marvled', 10), ('\x93huge', 10), ('arthor', 10), ('malins', 10), ('shoudn', 10), ('sulferic', 10), ('preident', 10), ('perecnt', 10), ('nautural', 10), ('technolagy', 10), ('¨driverless', 10), ('electroral', 10), ('navagating', 10), ('unmaned', 10), ('martion', 10), ('valcanos', 9), ('sicentists', 9), ('electorl', 9), ('ruduce', 9), ('privice', 9), ('farhrenheit', 9), ('aviods', 9), ('planet\x92s', 9), ('surveryor', 9), ('coyboy', 9), ('disadvanteges', 9), ('parapgraph', 9), ('driverlass', 9), ('\x93we', 9), ('shawdows', 9), ('vauben', 9), ('dixoide', 9), ('accoriding', 9), ('atmosperic', 9), ('temputure', 9), ('accidnets', 9), ('technologly', 9), ('atmosheric', 9), ('gravin', 9), ('acciedents', 9), ('venus\x92s', 9), ('canadates', 9), ('camera\x92s', 9), ('experssions', 9), ('eploring', 9), ('computures', 9), ('ashwalt', 8), ('astronomres', 8), ('seagoin', 8), ('seaging', 8), ('nixion', 8), ('unreasnable', 8), ('reaserchers', 8), ('vensu', 8), ('evedince', 8), ('cannidate', 8), ('asspects', 8), ('fahreheit', 8), ('apperared', 8), ('persents', 8), ('elcetors', 8), ('exavated', 8), ('transportantion', 8), ('tchnology', 8), ('acroplis', 8), ('planest', 8), ('sinceraly', 8), ('bomburger', 8), ('fulkerson', 8), ('baceball', 8), ('electorla', 8), ('malfuntioning', 8), ('scentist', 8), ('expresstion', 8), ('expresstions', 8), ('constucts', 8), ('faical', 8), ('sencers', 8), ('percautions', 8), ('landforming', 8), ('athour', 8), ('illision', 8), ('preisdent', 8), ('nasas', 8), ('technologhy', 8), ('venus¨', 8), ('¨a', 8), ('pleged', 8), ('mucsles', 8), ('asunción', 8), ('scientits', 8), ('attintion', 8), ('sargit', 7), ('solfware', 7), ('adventer', 7), ('\x93as', 7), ('pbds', 7), ('sceintists', 7), ('precidency', 7), ('pollutin', 7), ('tectnology', 7), ('exprssions', 7), ('invition', 7), ('auothor', 7), ('suveyor', 7), ('polluation', 7), ('recevies', 7), ('surviveable', 7), ('fromation', 7), ('diocide', 7), ('atmoshperic', 7), ('dnager', 7), ('lastley', 7), ('unnra', 7), ('vauble', 7), ('envirorment', 7), ('unrr', 7), ('erotion', 7), ('extraterestrial', 7), ('scienists', 7), ('\x93a', 7), ('vicking', 7), ('messas', 7), ('presdident', 7), ('electora', 7), ('beneifit', 7), ('emmsions', 7), ('\x93then', 7), ('presidnt', 7), ('preseident', 7), ('driverlss', 7), ('syestem', 7), ('driverlees', 7), ('tecnolgy', 7), ('paraghraph', 7), ('safier', 7), ('expolring', 7), ('eurpoe', 7), ('deviod', 7), ('widthstand', 7), ('electers', 7), ('drivning', 7), ('alieans', 7), ('workzones', 7), ('¨making', 7), ('eathquakes', 7), ('scintist', 7), ('survided', 7), ('fahrenhit', 7), ('senitor', 7), ('huamns', 7), ('danges', 7), ('canididate', 7), ('senetor', 7), ('accendent', 7), ('tecaher', 7), ('cannidates', 7), ('foucused', 7), ('concluson', 7), ('soloar', 7), ('polllution', 7), ('fault\x97the', 7), ('crators', 7), ('illegle', 6), ('cleanier', 6), ('driviers', 6), ('canadiate', 6), ('vuban', 6), ('venusis', 6), ('expeariance', 6), ('plantets', 6), ('technoly', 6), ('evdience', 6), ('surveyour', 6), ('candates', 6), ('atlanic', 6), ('theroys', 6), ('ponser', 6), ('bomberg', 6), ('pursiut', 6), ('represenitives', 6), ('sientist', 6), ('uasge', 6), ('secoundly', 6), ('dangeros', 6), ('motify', 6), ('instince', 6), ('submerine', 6), ('presindent', 6), ('computerdriven', 6), ('mars\x97evidence', 6), ('postivies', 6), ('spaceraft', 6), ('it\x92s', 6), ('plaent', 6), ('exspression', 6), ('airplains', 6), ('resones', 6), ('huag', 6), ('advanatges', 6), ('diseal', 6), ('coumpter', 6), ('mealt', 6), ('sicentist', 6), ('moument', 6), ('studants', 6), ('injuired', 6), ('droven', 6), ('classromm', 6), ('paragrapg', 6), ('scients', 6), ('astromomers', 6), ('velleys', 6), ('usgae', 6), ('analogus', 6), ('beaucse', 6), ('corrsive', 6), ('shouln', 6), ('expressons', 6), ('dangous', 6), ('pryamids', 6), ('wrothy', 6), ('presisdent', 6), ('clasrooms', 6), ('you\x92re', 6), ('eclectoral', 6), ('surviable', 6), ('dangorous', 6), ('dangeres', 6), ('thechnology', 6), ('pruis', 6), ('sidwalks', 6), ('elecotrs', 6), ('slilcon', 6), ('malifunction', 6), ('teperatures', 6), ('conclusin', 6), ('technolody', 6), ('plantary', 6), ('vanban', 6), ('coclusion', 6), ('responability', 6), ('seacowboys', 6), ('ocenas', 6), ('atmosphereic', 6), ('greeenhouse', 6), ('pollutuion', 6), ('landfom', 6), ('tempertaure', 6), ('stuyding', 6), ('disscusing', 6), ('focased', 6), ('electronices', 6), ('pararaph', 6), ('sentor', 6), ('emmitions', 6), ('popullation', 6), ('driveress', 6), ('envoriment', 6), ('emontional', 6), ('curcial', 6), ('elecotoral', 6), ('puruit', 6), ('regared', 6), ('airplans', 6), ('¨venus', 6), ('scientst', 6), ('intimdating', 6), ('pursuite', 6), ('wouln', 6), ('vauleable', 6), ('professers', 6), ('presadent', 6), ('veunus', 6), ('expresssions', 6), ('surfave', 6), ('movents', 6), ('advanges', 6), ('canadidates', 6), ('facters', 5), ('astronots', 5), ('edvidence', 5), ('utfonm', 5), ('civization', 5), ('sensiors', 5), ('source3', 5), ('eletion', 5), ('emotsions', 5), ('unalert', 5), ('reaseachers', 5), ('technogoly', 5), ('plaet', 5), ('bradfor', 5), ('contraversal', 5), ('expretions', 5), ('faherenheit', 5), ('eplains', 5), ('satelittes', 5), ('calssroom', 5), ('happeir', 5), ('fahernheit', 5), ('ocens', 5), ('techonogly', 5), ('canadite', 5), ('conditiond', 5), ('decates', 5), ('classoom', 5), ('spacraft', 5), ('veanus', 5), ('sufuric', 5), ('authore', 5), ('electos', 5), ('facsinated', 5), ('hospitible', 5), ('attition', 5), ('musces', 5), ('comditions', 5), ('scociety', 5), ('boberger', 5), ('hazardess', 5), ('mailn', 5), ('attiention', 5), ('electeral', 5), ('confued', 5), ('planetry', 5), ('anitlock', 5), ('ingured', 5), ('paragrahp', 5), ('umasking', 5), ('scietists', 5), ('venusain', 5), ('coquencedence', 5), ('techonogy', 5), ('aeronatics', 5), ('anologous', 5), ('finacialy', 5), ('hummans', 5), ('canididates', 5), ('invisions', 5), ('tramendously', 5), ('colombias', 5), ('reconization', 5), ('despte', 5), ('acciddents', 5), ('emoitions', 5), ('techonoly', 5), ('dnagerous', 5), ('bogato', 5), ('driverlesscars', 5), ('polluton', 5), ('brightes', 5), ('sreets', 5), ('surfce', 5), ('segragationists', 5), ('pulluted', 5), ('happyiness', 5), ('candidtes', 5), ('drierless', 5), ('landfor', 5), ('nintey', 5), ('clounds', 5), ('candiddate', 5), ('polloution', 5), ('aleans', 5), ('exlpore', 5), ('acrticle', 5), ('enfored', 5), ('expretion', 5), ('communtication', 5), ('maufactures', 5), ('¨evening', 5), ('dioxied', 5), ('acccidents', 5), ('enivironment', 5), ('sergy', 5), ('indanger', 5), ('authoer', 5), ('atrifact', 5), ('knolege', 5), ('goldburg', 5), ('colobians', 5), ('tansport', 5), ('presidencey', 5), ('shows\x97even', 5), ('factial', 5), ('dicern', 5), ('accients', 5), ('eygptian', 5), ('fahenheit', 5), ('devoided', 5), ('scientics', 5), ('planetray', 5), ('reasions', 5), ('tachnology', 5), ('transportaton', 5), ('rosental', 5), ('smile¨', 5), ('face¨', 5), ('dangerest', 5), ('democtratic', 5), ('¨face', 5), ('suthor', 5), ('intensifiying', 5), ('disguested', 5), ('bimp', 5), ('evience', 5), ('benefital', 5), ('emisssions', 5), ('prusuit', 5), ('¨twin¨', 5), ('sulfiric', 5), ('cumputers', 5), ('shodows', 5), ('colloege', 5), ('counclers', 5), ('ligtning', 5), ('auhor', 5), ('¨driverless¨', 4), ('optimisstic', 4), ('pixil', 4), ('expermint', 4), ('electoreal', 4), ('benfaftial', 4), ('heidren', 4), ('oprotunity', 4), ('cydonia\x97mars', 4), ('2001\x97a', 4), ('echman', 4), ('scientistics', 4), ('reovolutionary', 4), ('tecnolgie', 4), ('stals', 4), ('surportive', 4), ('blobal', 4), ('imagian', 4), ('fouces', 4), ('dangreous', 4), ('danerous', 4), ('incooperated', 4), ('limithing', 4), ('electoial', 4), ('dangest', 4), ('surfes', 4), ('hunag', 4), ('driversless', 4), ('gandola', 4), ('torwads', 4), ('systeam', 4), ('gremany', 4), ('dission', 4), ('implament', 4), ('reaseaches', 4), ('helthier', 4), ('expressios', 4), ('imitions', 4), ('genunie', 4), ('decresing', 4), ('grocey', 4), ('exprestions', 4), ('electorcal', 4), ('corrisive', 4), ('effeciant', 4), ('procesess', 4), ('garvins', 4), ('persuite', 4), ('evedance', 4), ('illionois', 4), ('invetions', 4), ('vinchi', 4), ('lincenses', 4), ('motorvehicles', 4), ('venushas', 4), ('suburn', 4), ('fascianted', 4), ('temputures', 4), ('cardide', 4), ('pletiful', 4), ('conspirasy', 4), ('tecnhology', 4), ('evevidence', 4), ('therorists', 4), ('intreged', 4), ('livible', 4), ('drivereless', 4), ('accasionally', 4), ('eurpe', 4), ('potientally', 4), ('romeny', 4), ('articfact', 4), ('incipent', 4), ('astronuts', 4), ('polluion', 4), ('technolohy', 4), ('nemerous', 4), ('maulfunctions', 4), ('unessacary', 4), ('panets', 4), ('imagaination', 4), ('reassons', 4), ('emotioal', 4), ('dissadvantages', 4), ('venuis', 4), ('eruope', 4), ('evdince', 4), ('blankeds', 4), ('scientifcally', 4), ('reserches', 4), ('veince', 4), ('pagraph', 4), ('frequant', 4), ('obricularis', 4), ('sufrace', 4), ('paragh', 4), ('safetyness', 4), ('¨nasa', 4), ('aniamals', 4), ('certanty', 4), ('discoverings', 4), ('driveres', 4), ('farenhiet', 4), ('percant', 4), ('relieze', 4), ('sloar', 4), ('fouding', 4), ('artificat', 4), ('cassroom', 4), ('emostions', 4), ('civilazations', 4), ('confusd', 4), ('unveild', 4), ('abloished', 4), ('aien', 4), ('scientise', 4), ('infrences', 4), ('pursute', 4), ('liscenes', 4), ('dnagers', 4), ('antlantic', 4), ('emmotions', 4), ('unnessisary', 4), ('driveerless', 4), ('attenshion', 4), ('emensly', 4), ('drvierless', 4), ('innovtion', 4), ('unviersal', 4), ('limitating', 4), ('woulden', 4), ('coybows', 4), ('garuntees', 4), ('convensing', 4), ('amotions', 4), ('anamals', 4), ('techonological', 4), ('codying', 4), ('decress', 4), ('positves', 4), ('autnomous', 4), ('voing', 4), ('releaves', 4), ('spacecarft', 4), ('representitves', 4), ('presuade', 4), ('valube', 4), ('huange', 4), ('compuers', 4), ('don\x92t', 4), ('coudn', 4), ('¨seagoing', 4), ('elctorial', 4), ('drivreless', 4), ('technolegy', 4), ('aleart', 4), ('\x93the', 4), ('dangerours', 4), ('evindence', 4), ('panamal', 4), ('perssure', 4), ('facical', 4), ('dectects', 4), ('trasnportation', 4), ('ladforms', 4), ('eroup', 4), ('colser', 4), ('presidet', 4), ('scinetist', 4), ('excrise', 4), ('excaveted', 4), ('desiding', 4), ('vechical', 4), ('abloish', 4), ('unfreindly', 4), ('parograph', 4), ('\x93most', 4), ('certine', 4), ('citicens', 4), ('democrtic', 4), ('deosn', 4), ('reasearches', 4), ('brandford', 4), ('simulatiing', 4), ('imtimidating', 4), ('planitary', 4), ('star¨', 4), ('vothing', 4), ('emotinos', 4), ('surafce', 4), ('condicions', 4), ('sciencists', 4), ('stiving', 4), ('thirthy', 4), ('\x93malin\x92s', 4), ('candidtate', 4), ('praragraph', 4), ('wittling', 4), ('animails', 4), ('advangtages', 4), ('scientsts', 4), ('presedency', 4), ('majorety', 4), ('conclousion', 4), ('transortation', 4), ('tecahers', 4), ('advantiges', 4), ('vinice', 4), ('equvialent', 4), ('formtion', 4), ('souldn', 4), ('perdicted', 4), ('polutin', 4), ('padestrians', 4), ('deceving', 4), ('disadvantges', 4), ('driveles', 4), ('teahcers', 4), ('showdows', 4), ('keilah', 4), ('suburd', 4), ('huand', 4), ('reaveling', 4), ('inhabbited', 4), ('atmopheric', 4), ('sulfuic', 4), ('dagrees', 4), ('spacecaft', 4), ('venuns', 4), ('peopkle', 4), ('scienetists', 4), ('automonous', 4), ('conclucion', 4), ('contrustion', 4), ('hazordous', 4), ('theortists', 4), ('eaths', 4), ('consuler', 4), ('hiltop', 4), ('clonclusion', 4), ('hassal', 4), ('drivierless', 4), ('emoition', 4), ('sincearly', 4), ('drivering', 4), ('accadent', 4), ('viberate', 4), ('possibaly', 4), ('fuems', 4), ('veicles', 4), ('paragraghs', 4), ('horese', 4), ('sacecraft', 4), ('surfurs', 4), ('technonlgy', 4), ('computars', 4), ('pasangers', 4), ('transportatin', 4), ('electroics', 4), ('sureface', 4), ('eurpting', 4), ('rescined', 4), ('mars¨', 4), ('scientisis', 4), ('fenceing', 4), ('autopliot', 4), ('concluion', 4), ('counclusion', 4), ('coming¨', 4), ('sientists', 4), ('systam', 4), ('vinvi', 4), ('symstem', 4), ('stdents', 4), ('temptures', 4), ('nacessary', 3), ('cerosity', 3), ('potenetial', 3), ('responsiblitly', 3), ('fums', 3), ('facaial', 3), ('emissins', 3), ('disaventages', 3), ('dangerour', 3), ('presiential', 3), ('vaubun', 3), ('forpresident', 3), ('posablet', 3), ('scapecraft', 3), ('calulates', 3), ('canidadtes', 3), ('engaed', 3), ('sgcp', 3), ('disision', 3), ('campaighn', 3), ('source4', 3), ('survivle', 3), ('sureyor', 3), ('scine', 3), ('redusing', 3), ('consistution', 3), ('evrething', 3), ('fatial', 3), ('glabal', 3), ('candiadates', 3), ('anchorism', 3), ('therist', 3), ('darastically', 3), ('animoji', 3), ('tecknology', 3), ('ladform', 3), ('inrich', 3), ('cruzz', 3), ('recongizes', 3), ('oceon', 3), ('disracted', 3), ('imagintion', 3), ('driffrent', 3), ('stiutions', 3), ('deflict', 3), ('momunment', 3), ('evedience', 3), ('atomshpere', 3), ('temperatuers', 3), ('studiying', 3), ('emotios', 3), ('advaces', 3), ('unessisary', 3), ('presue', 3), ('blimb', 3), ('presudent', 3), ('conputers', 3), ('studensts', 3), ('automomous', 3), ('benitfical', 3), ('subatle', 3), ('atmsphere', 3), ('contuie', 3), ('distrated', 3), ('driverlesses', 3), ('cydoia', 3), ('charels', 3), ('technoology', 3), ('misfunctions', 3), ('eassay', 3), ('similiaraties', 3), ('simalaritys', 3), ('contions', 3), ('aproching', 3), ('eurupe', 3), ('transprtation', 3), ('agrrement', 3), ('exaplains', 3), ('atmospheroc', 3), ('univesal', 3), ('mechens', 3), ('phragraph', 3), ('familir', 3), ('parahgraph', 3), ('meteroid', 3), ('posibilites', 3), ('expierment', 3), ('exspencive', 3), ('idntify', 3), ('frequesnt', 3), ('animles', 3), ('licensess', 3), ('resurchers', 3), ('inpending', 3), ('emmition', 3), ('tarvels', 3), ('aldults', 3), ('inverment', 3), ('prefernece', 3), ('electory', 3), ('balences', 3), ('resarchers', 3), ('opritunity', 3), ('driverlsess', 3), ('tempeter', 3), ('investagate', 3), ('enotions', 3), ('ellectors', 3), ('percetn', 3), ('accdient', 3), ('derect', 3), ('greace', 3), ('acciednt', 3), ('ainmals', 3), ('apirl', 3), ('unintrested', 3), ('contrversy', 3), ('evidenve', 3), ('communionship', 3), ('sutdent', 3), ('sciencist', 3), ('earthquackes', 3), ('shawdos', 3), ('expreesion', 3), ('mucels', 3), ('spaned', 3), ('computuers', 3), ('catasrophe', 3), ('greenhous', 3), ('exlaining', 3), ('humanless', 3), ('botoga', 3), ('pyrmaids', 3), ('dangroues', 3), ('seagoning', 3), ('featers', 3), ('exprestion', 3), ('mountens', 3), ('shadoes', 3), ('destractions', 3), ('diriving', 3), ('presendential', 3), ('ufair', 3), ('emotiones', 3), ('bumberger', 3), ('agurement', 3), ('sceintist', 3), ('occasionnally', 3), ('strgazer', 3), ('constitutuion', 3), ('expadition', 3), ('comfterable', 3), ('oppertounity', 3), ('condititons', 3), ('¨at', 3), ('sloutions', 3), ('jouneys', 3), ('envierment', 3), ('benfital', 3), ('privacity', 3), ('cnfused', 3), ('rehibilitation', 3), ('automous', 3), ('councilers', 3), ('callege', 3), ('driver¨', 3), ('vinci\x92s', 3), ('descison', 3), ('wachman', 3), ('resaerchers', 3), ('camreas', 3), ('furthurmore', 3), ('inconvinence', 3), ('pursiting', 3), ('tectnolony', 3), ('expoloring', 3), ('consitiution', 3), ('greenhose', 3), ('resherch', 3), ('porcent', 3), ('egyptains', 3), ('dangeruse', 3), ('estamating', 3), ('marveld', 3), ('eqyptian', 3), ('particapated', 3), ('callenges', 3), ('tavels', 3), ('cummunicate', 3), ('invension', 3), ('facian', 3), ('pulrality', 3), ('presisent', 3), ('promgram', 3), ('diffrient', 3), ('understnading', 3), ('indeavor', 3), ('cospiracy', 3), ('smaile', 3), ('marses', 3), ('condistions', 3), ('vnus', 3), ('euope', 3), ('cars¨', 3), ('naturual', 3), ('disctracted', 3), ('idetify', 3), ('reconginze', 3), ('abourd', 3), ('artura', 3), ('latitiude', 3), ('reprocautions', 3), ('vaulabe', 3), ('pedestians', 3), ('autopiolet', 3), ('¨traffic', 3), ('discorver', 3), ('caculating', 3), ('arugement', 3), ('mechainics', 3), ('facelike', 3), ('movemets', 3), ('opputunites', 3), ('oppurtunitys', 3), ('presdint', 3), ('computres', 3), ('eloctoral', 3), ('lowared', 3), ('extordinary', 3), ('deystroyed', 3), ('manufactuerer', 3), ('percect', 3), ('emotoins', 3), ('poluttion', 3), ('wlater', 3), ('environemt', 3), ('meaninfully', 3), ('appropiations', 3), ('selfdriven', 3), ('dioxcide', 3), ('potentionaly', 3), ('emmisons', 3), ('revunue', 3), ('inovators', 3), ('innvations', 3), ('exspenses', 3), ('hostlie', 3), ('recignition', 3), ('cowby', 3), ('par28', 3), ('consoulers', 3), ('oppurtinty', 3), ('traving', 3), ('spacecrft', 3), ('delcaring', 3), ('fathes', 3), ('pedistrians', 3), ('regonition', 3), ('anables', 3), ('dissaper', 3), ('certanity', 3), ('polutes', 3), ('emptions', 3), ('ecample', 3), ('recignize', 3), ('machienes', 3), ('exterterrestrial', 3), ('emotin', 3), ('representator', 3), ('drivelesss', 3), ('sulfic', 3), ('sedimant', 3), ('prsidential', 3), ('musscles', 3), ('doudts', 3), ('dergrees', 3), ('dergees', 3), ('polotician', 3), ('colclusion', 3), ('matals', 3), ('reshearch', 3), ('expersion', 3), ('perceving', 3),

In [71]:
train.head()

,essay_id,full_text,score,lowered_question,cleaned_text,clean_text,lowered
1,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...
2,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,people always wish they had the same technolog...,people always wish they had the same technolog...,people always wish they had the same technolog...
3,001bdc0,"We all heard about Venus, the planet without a...",4,"we all heard about venus, the planet without a...","we all heard about venus, the planet without a...","we all heard about venus , the planet without...","we all heard about venus, the planet without a..."
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,"dear, state senator\n\nthis is a letter to arg...","dear, state senator\n\nthis is a letter to arg...","dear , state senator\n\nthis is a letter to a...","dear, state senator\n\nthis is a letter to arg..."
6,0033037,The posibilty of a face reconizing computer wo...,2,the posibilty of a face reconizing computer wo...,the posibilty of a face reconizing computer wo...,the posibilty of a face reconizing computer wo...,the posibilty of a face reconizing computer wo...

In [17]:
print(train['full_text'][0])

Many people have car where they live. The thing they don't know is that when you use a car alot of thing can happen like you can get in accidet or the smoke that the car has is bad to breath on if someone is walk but in VAUBAN,Germany they dont have that proble because 70 percent of vauban's families do not own cars,and 57 percent sold a car to move there. Street parkig ,driveways and home garages are forbidden on the outskirts of freiburd that near the French and Swiss borders. You probaly won't see a car in Vauban's streets because they are completely "car free" but If some that lives in VAUBAN that owns a car ownership is allowed,but there are only two places that you can park a large garages at the edge of the development,where a car owner buys a space but it not cheap to buy one they sell the space for you car for $40,000 along with a home. The vauban people completed this in 2006 ,they said that this an example of a growing trend in Europe,The untile states and some where else are suburban life from auto use this is called "smart planning". The current efforts to drastically reduce greenhouse gas emissions from tailes the passengee cars are responsible for 12 percent of greenhouse gas emissions in Europe and up to 50 percent in some car intensive in the United States. I honeslty think that good idea that they did that is Vaudan because that makes cities denser and better for walking and in VAUBAN there are 5,500 residents within a rectangular square mile. In the artical David Gold berg said that "All of our development since World war 2 has been centered on the cars,and that will have to change" and i think that was very true what David Gold said because alot thing we need cars to do we can go anyway were with out cars beacuse some people are a very lazy to walk to place thats why they alot of people use car and i think that it was a good idea that that they did that in VAUBAN so people can see how we really don't need car to go to place from place because we can walk from were we need to go or we can ride bycles with out the use of a car. It good that they are doing that if you thik about your help the earth in way and thats a very good thing to. In the United states ,the Environmental protection Agency is promoting what is called "car reduced"communtunties,and the legislators are starting to act,if cautiously. Maany experts expect pubic transport serving suburbs to play a much larger role in a new six years federal transportation bill to approved this year. In previous bill,80 percent of appropriations have by law gone to highways and only 20 percent to other transports. There many good reason why they should do this.

In [18]:
print(train['clean_text'][0])

many people have car where they live .  the thing they do not know is that when you use a car alot of thing can happen like you can get in accident or the smoke that the car has is bad to breath on if someone is walk but in  , germany they dont have that proble because 70 percent of   '  s families do not own cars , and 57 percent sold a car to move there .  street parking  , driveways and home garages are forbidden on the outskirts of  that near the french and swiss borders .  you probaly will not see a car in   '  s streets because they are completely   "  car free  "   but if some that lives in  that owns a car ownership is allowed , but there are only two places that you can park a large garages at the edge of the development , where a car owner buys a space but it not cheap to buy one they sell the space for you car for  $ 40 , 000 along with a home .  the  people completed this in 2006  , they said that this an example of a growing trend in europe , the untile states and some where else are suburban life from auto use this is called   "  smart planning  "   .  the current efforts to drastically reduce greenhouse gas emissions from tables the passenger cars are responsible for 12 percent of greenhouse gas emissions in europe and up to 50 percent in some car intensive in the united states .  i honeslty think that good idea that they did that is vandal because that makes cities denser and better for walking and in  there are 5 , 500 residents within a rectangular square mile .  in the artical david gold berg said that   "  all of our development since world war 2 has been centered on the cars , and that will have to change  "   and i think that was very true what david gold said because alot thing we need cars to do we can go anyway were with out cars beacuse some people are a very lazy to walk to place thats why they alot of people use car and i think that it was a good idea that that they did that in  so people can see how we really do not need car to go to place from place because we can walk from were we need to go or we can ride cycles with out the use of a car .  it good that they are doing that if you thik about your help the earth in way and thats a very good thing to .  in the united states  , the environmental protection agency is promoting what is called   "  car reduced  "  communtunties , and the legislators are starting to act , if cautiously .  many experts expect pubic transport serving suburbs to play a much larger role in a new six years federal transportation bill to approved this year .  in previous bill , 80 percent of appropriations have by law gone to highways and only 20 percent to other transports .  there many good reason why they should do this .

In [ ]:
def custom_train_validation_split(essays, test_size=0.2, random_state=56):
    
    """
    Custom function to perform train-validation split ensuring that
    the same prompt IDs are in both training and validation sets.

    Parameters:
    - summaries: DataFrame containing summaries and associated prompt_ids
    - prompts: DataFrame containing prompts and associated prompt_ids
    - test_size: Proportion of the dataset to be used as the validation set
    - random_state: Random seed for reproducibility

    Returns:
    - train_summaries: Training set containing summaries
    - validation_summaries: Validation set containing summaries
    - train_prompts: Training set containing prompts
    - validation_prompts: Validation set containing prompts
    """
    from sklearn.model_selection import train_test_split
    # Extract unique prompt IDs
    unique_essay_ids = essays['essay_id'].unique()

    # Split the unique prompt IDs into training and validation sets
    train_ids, validation_ids = train_test_split(unique_essay_ids, test_size=test_size, random_state=random_state)

    # Use these IDs to filter the original summaries and prompts DataFrames
    train_essays = essays[essays['essay_id'].isin(train_ids)]
    validation_essays = essays[essays['essay_id'].isin(validation_ids)]

    return train_essays, validation_essays


train, validation = custom_train_validation_split(train, 0.25)

In [19]:
# Save the cleaned text data to a Parquet file

train.to_parquet('clean_train.parquet')
validation.to_parquet('clean_validation.parquet')

# test.to_parquet('cleaned_test.parquet')

In [ ]:
# save