In [1]:
import pandas as pd 
import numpy as np

train = pd.read_csv('/kaggle/input/leap-atmospheric-physics-ai-climsim/train.csv',nrows=10000)
train

,sample_id,state_t_0,state_t_1,state_t_2,state_t_3,state_t_4,state_t_5,state_t_6,state_t_7,state_t_8,...,ptend_v_58,ptend_v_59,cam_out_NETSW,cam_out_FLWDS,cam_out_PRECSC,cam_out_PRECC,cam_out_SOLS,cam_out_SOLL,cam_out_SOLSD,cam_out_SOLLD
0,train_0,213.806117,222.244454,229.259879,245.743959,258.337482,265.772467,263.978456,254.879872,243.946147,...,-6.132147e-07,1.401824e-06,0.000000,349.564325,0.0,2.947672e-12,0.000000,0.000000,0.000000,0.000000
1,train_1,213.177430,225.851064,229.663618,246.828333,261.026415,269.078431,267.736565,256.896227,244.169421,...,3.560950e-07,9.984912e-07,0.000000,335.204086,0.0,3.138366e-09,0.000000,0.000000,0.000000,0.000000
2,train_2,217.105685,220.448106,234.653398,244.422951,254.023818,259.651472,257.709514,251.064513,241.879600,...,1.565672e-06,6.186607e-05,0.000000,401.709340,0.0,7.424215e-09,0.000000,0.000000,0.000000,0.000000
3,train_3,217.773994,225.611775,234.104091,247.745365,257.411402,263.470947,261.131775,253.303250,242.316814,...,-9.067304e-06,1.020519e-05,0.000000,400.230177,0.0,2.534090e-08,0.000000,0.000000,0.000000,0.000000
4,train_4,216.349337,230.526083,233.650252,248.196013,262.500730,270.055663,268.863606,258.161645,244.442620,...,1.681596e-06,-6.378779e-06,0.000000,321.960470,0.0,3.377415e-10,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,train_9995,216.136446,232.148355,233.158769,244.960561,255.503946,261.854313,261.281828,253.841078,242.447050,...,-1.700152e-05,-1.332795e-05,716.094718,414.340142,0.0,0.000000e+00,306.351156,334.245792,132.551825,64.318362
9996,train_9996,214.918347,227.005413,232.234679,247.188997,257.665000,264.458980,264.444587,257.801384,246.897318,...,-7.205415e-06,3.412841e-06,425.653980,390.589742,0.0,3.732297e-09,148.417660,91.361454,120.161394,92.104924
9997,train_9997,214.943843,226.572586,230.751971,245.991705,257.504874,264.664252,263.822958,256.306956,244.885091,...,2.902561e-05,7.003127e-06,525.416736,387.895266,0.0,7.780432e-08,228.431387,250.154373,61.813844,12.164337
9998,train_9998,216.605554,231.923186,233.204988,245.067903,256.228286,263.198778,261.713294,253.445886,241.483092,...,-2.764231e-05,-1.224546e-05,477.346202,425.720898,0.0,5.936750e-08,211.039149,211.822729,79.612773,50.353456
9999,train_9999,216.305962,231.156845,234.833978,244.011648,256.413999,263.878915,261.516360,252.843516,240.661138,...,1.933024e-06,-2.967886e-06,549.464735,395.906462,0.0,0.000000e+00,264.453973,264.529789,45.620035,10.773180

In [2]:
sample_submission = pd.read_csv('/kaggle/input/leap-atmospheric-physics-ai-climsim/sample_submission.csv', nrows=10000)
sample_submission

,sample_id,ptend_t_0,ptend_t_1,ptend_t_2,ptend_t_3,ptend_t_4,ptend_t_5,ptend_t_6,ptend_t_7,ptend_t_8,...,ptend_v_58,ptend_v_59,cam_out_NETSW,cam_out_FLWDS,cam_out_PRECSC,cam_out_PRECC,cam_out_SOLS,cam_out_SOLL,cam_out_SOLSD,cam_out_SOLLD
0,test_169651,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632
1,test_524862,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632
2,test_634129,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632
3,test_403572,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632
4,test_484578,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,test_573177,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632
9996,test_518944,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632
9997,test_27443,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632
9998,test_541576,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632
9999,test_96161,30981.265272,22502.432414,18894.14713,14514.244731,10944.348069,9065.01072,9663.669039,12688.557363,19890.172265,...,41183.344137,29194.123693,0.004054,0.013882,1.351299e+08,1.221972e+07,0.009071,0.00859,0.021537,0.033632

In [3]:
test = pd.read_csv('/kaggle/input/leap-atmospheric-physics-ai-climsim/test.csv', nrows=10000)
test

,sample_id,state_t_0,state_t_1,state_t_2,state_t_3,state_t_4,state_t_5,state_t_6,state_t_7,state_t_8,...,pbuf_N2O_50,pbuf_N2O_51,pbuf_N2O_52,pbuf_N2O_53,pbuf_N2O_54,pbuf_N2O_55,pbuf_N2O_56,pbuf_N2O_57,pbuf_N2O_58,pbuf_N2O_59
0,test_169651,209.802593,220.698213,227.783289,241.386812,254.602962,262.319063,261.308368,254.062035,243.904420,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07
1,test_524862,208.366101,219.238711,228.265017,242.099772,256.164270,263.783211,261.835384,253.636172,243.783467,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07
2,test_634129,213.073771,229.421551,233.368455,242.683788,252.912786,260.953981,260.977310,253.059885,240.929890,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07
3,test_403572,212.048636,226.003864,230.980609,241.056187,252.829634,262.185770,261.900745,253.187196,241.186311,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07
4,test_484578,207.926097,216.697348,227.821590,243.555011,257.498525,265.294257,262.886892,253.702132,243.453695,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,test_573177,211.429641,225.002988,233.039423,243.202445,255.126322,262.479246,260.379200,251.888442,241.330519,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07
9996,test_518944,210.211831,219.315960,232.426042,243.095417,256.746710,262.915815,260.338913,251.854771,241.618406,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07
9997,test_27443,215.966931,222.223302,233.314743,241.398842,255.693677,262.395244,260.244291,251.600466,241.373213,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07
9998,test_541576,214.158593,228.176766,233.848518,241.030868,254.214009,262.510049,260.838728,252.243712,241.156828,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07
9999,test_96161,218.456237,229.482245,234.465077,240.823484,253.143530,261.378548,260.422954,251.734687,240.423806,...,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07,4.908584e-07

In [4]:
targets = [x for x in sample_submission.columns if x not in ["sample_id"]]

print('First Ten Target Variables')
targets[:10]

First Ten Target Variables

['ptend_t_0',
 'ptend_t_1',
 'ptend_t_2',
 'ptend_t_3',
 'ptend_t_4',
 'ptend_t_5',
 'ptend_t_6',
 'ptend_t_7',
 'ptend_t_8',
 'ptend_t_9']

In [5]:
cols_13_pbuf_N2O = ["pbuf_N2O_"+str(i) for i in range(27,60)]
cols_13_pbuf_CH4 = ["pbuf_CH4_"+str(i) for i in range(27,60)]

cols_to_delete = cols_13_pbuf_N2O + cols_13_pbuf_CH4
len(cols_to_delete)

66

In [6]:
print(f'Number of variables before drops: {len(train.columns)}')

Number of variables before drops: 925

In [7]:
train.drop(columns=cols_to_delete, inplace=True, axis=1)
test.drop(columns=cols_to_delete, inplace=True, axis=1)

In [8]:
print(f'Number of variables before drops: {len(train.columns)}')

Number of variables before drops: 859

In [9]:
train[targets]

,ptend_t_0,ptend_t_1,ptend_t_2,ptend_t_3,ptend_t_4,ptend_t_5,ptend_t_6,ptend_t_7,ptend_t_8,ptend_t_9,...,ptend_v_58,ptend_v_59,cam_out_NETSW,cam_out_FLWDS,cam_out_PRECSC,cam_out_PRECC,cam_out_SOLS,cam_out_SOLL,cam_out_SOLSD,cam_out_SOLLD
0,-0.000014,-0.000023,-0.000020,-0.000052,-0.000086,-0.000112,-0.000106,-0.000078,-0.000049,-0.000038,...,-6.132147e-07,1.401824e-06,0.000000,349.564325,0.0,2.947672e-12,0.000000,0.000000,0.000000,0.000000
1,-0.000009,-0.000032,-0.000018,-0.000051,-0.000091,-0.000119,-0.000116,-0.000082,-0.000047,-0.000037,...,3.560950e-07,9.984912e-07,0.000000,335.204086,0.0,3.138366e-09,0.000000,0.000000,0.000000,0.000000
2,-0.000022,-0.000017,-0.000041,-0.000052,-0.000078,-0.000098,-0.000092,-0.000076,-0.000053,-0.000042,...,1.565672e-06,6.186607e-05,0.000000,401.709340,0.0,7.424215e-09,0.000000,0.000000,0.000000,0.000000
3,-0.000020,-0.000027,-0.000032,-0.000059,-0.000084,-0.000106,-0.000099,-0.000078,-0.000050,-0.000038,...,-9.067304e-06,1.020519e-05,0.000000,400.230177,0.0,2.534090e-08,0.000000,0.000000,0.000000,0.000000
4,-0.000010,-0.000042,-0.000024,-0.000051,-0.000094,-0.000121,-0.000119,-0.000085,-0.000047,-0.000036,...,1.681596e-06,-6.378779e-06,0.000000,321.960470,0.0,3.377415e-10,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.000043,0.000015,0.000061,0.000082,0.000118,0.000166,0.000178,0.000137,0.000086,0.000065,...,-1.700152e-05,-1.332795e-05,716.094718,414.340142,0.0,0.000000e+00,306.351156,334.245792,132.551825,64.318362
9996,0.000041,0.000029,0.000061,0.000071,0.000104,0.000143,0.000145,0.000103,0.000062,0.000047,...,-7.205415e-06,3.412841e-06,425.653980,390.589742,0.0,3.732297e-09,148.417660,91.361454,120.161394,92.104924
9997,0.000039,0.000028,0.000062,0.000072,0.000100,0.000130,0.000121,0.000082,0.000054,0.000042,...,2.902561e-05,7.003127e-06,525.416736,387.895266,0.0,7.780432e-08,228.431387,250.154373,61.813844,12.164337
9998,0.000041,0.000016,0.000062,0.000082,0.000116,0.000156,0.000161,0.000121,0.000082,0.000065,...,-2.764231e-05,-1.224546e-05,477.346202,425.720898,0.0,5.936750e-08,211.039149,211.822729,79.612773,50.353456
9999,0.000040,0.000018,0.000055,0.000085,0.000111,0.000137,0.000129,0.000090,0.000064,0.000051,...,1.933024e-06,-2.967886e-06,549.464735,395.906462,0.0,0.000000e+00,264.453973,264.529789,45.620035,10.773180