 

<!-- Main div with background color and padding -->

<div style="background-color:#e6f2ff; padding: 20px;">

<!-- Image with margin and size adjustments -->

<img src="https://images.pexels.com/photos/2908984/pexels-photo-2908984.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Image Alt Text" style="display:block; margin:auto; width:40%;"/>

<!-- Main title -->

<h1 style="font-family:Verdana; color:#333366; text-align:center; font-size:4em;">Learning Agency Lab - Automated Essay Scoring 2.0</h1>

<!-- Subtitle -->

<h3 style="font-family:Verdana; color:#666699; text-align:center; font-size:3em;">Improve upon essay scoring algorithms to improve student learning outcomes

</h3>

<!-- Author name -->

<h4 style="font-family:Verdana; text-align:center; font-size:2em;">by Jack Donohue</h4>

<!-- Section headers -->

<!-- Project Description -->

## <p style="font-family:JetBrains Mono; font-weight:bold; letter-spacing: 2px; color:#243139; font-size:140%; text-align:left;padding: 0px; border-bottom: 3px solid #000000"><a name="install-packages"></a>Project Description</p>

<p style="background-color:#e6f2ff;">Goal of the Competition & Link</p>

## <p style="font-family:JetBrains Mono; font-weight:bold; letter-spacing: 2px; color:#243139; font-size:140%; text-align:left;padding: 0px; border-bottom: 3px solid #000000"><a name="install-packages"></a>Goal of the Competition</p>

<p style="background-color:#e6f2ff;">Goal of the Competition & Link</p>


    
## <p style="font-family:JetBrains Mono; font-weight:bold; letter-spacing: 2px; color:#243139; font-size:140%; text-align:left;padding: 0px; border-bottom: 3px solid #000000"><a name="install-packages"></a>Table of Contents</p>

1. [Install Packages](#install-packages)
2. [Variable Settings](#var-settings)
3. [Kaggle Setup](#kaggle-setup)
4. [Data Loading](#data-loading)
5. [Exploratory Data Analysis (EDA)](#eda)
6. [Preprocessing](#preprocessing)
7. [Training](#training)
8. [Inference](#inference)
9. [Model Evaluation](#model-evaluation)

<br></br>

In [1]:
 
# Import Packages
import shutup; shutup.please()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import keras_tuner as kt
import seaborn as sns

from nltk.corpus import stopwords, wordnet
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk import pos_tag, ne_chunk
from textblob import TextBlob

from textstat import flesch_reading_ease, smog_index

import spacy
from collections import Counter
from gensim import corpora, models
import pyLDAvis.gensim as gen
import pyLDAvis
import re

# Machine Learning & Data Preprocessing

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Deep Learning

from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Gensim
# from gensim.models import Word2Vec, KeyedVectors

# Progress bar
from tqdm import tqdm

# Keras Tuner
from keras_tuner.tuners import RandomSearch

# # Setting logging levels and environment variables
# tf.get_logger().setLevel(logging.ERROR)
# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

from textstat import flesch_reading_ease

2024-04-12 18:20:30.349385: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-12 18:20:30.390498: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-12 18:20:31.075554: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

# <p style="font-family:JetBrains Mono; font-weight:bold; letter-spacing: 2px; color:#243139; font-size:140%; text-align:left;padding: 0px; border-bottom: 3px solid #000000"> <a name="data-loading"></a>Data Loading</p>

### Competition data was cleaned in the 'clean-text-data.ipynb' notebook and loaded here for further processing and training

In [2]:
# Data Loading
# Placeholder for data loading code
# train = pd.read_parquet('data/cleaned_train.parquet')

train = pd.read_parquet('train.parquet')

# test = pd.read_parquet('data/cleaned_test.parquet')

In [3]:
train.head()

,essay_id,full_text,score,lowered,clean_text,corrected_text
0,000d118,Many people have car where they live. The thin...,3,many people have car where they live. the thin...,many people have car where they live the thing...,many people have car where they live the thing...
1,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...
2,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,people always wish they had the same technolog...,people always wish they had the same technolog...
3,001bdc0,"We all heard about Venus, the planet without a...",4,"we all heard about venus, the planet without a...",we all heard about venus the planet without al...,we all heard about venus the planet without al...
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,"dear, state senator\n\nthis is a letter to arg...",dear state senator this is a letter to argue i...,dear state senator this is a letter to argue i...

In [ ]:
# test.head()

# <p style="font-family:JetBrains Mono; font-weight:bold; letter-spacing: 2px; color:#243139; font-size:140%; text-align:left;padding: 0px; border-bottom: 3px solid #000000"> <a name="preprocessing"></a>Preprocessing</p>

In [ ]:
# # helper functions to tokenize by word and by sentence and add to the dataframe
# import nltk

# def tokenize_by_word(text):
#     return nltk.word_tokenize(text)

# def tokenize_by_sentence(text):
#     return nltk.sent_tokenize(text)

# train['tokenized_word'] = train['corrected_text'].apply(tokenize_by_word)
# train['tokenized_sentence'] = train['corrected_text'].apply(tokenize_by_sentence)

In [ ]:
# helper function to lemmatize, remove stopwords and punctuation, and other important text preprocessing steps then add to the dataframe

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import WordNetLemmatizer
import string

def preprocess_text_by_word(text):
    stop_words = set(stopwords.words('english'))
    lemmatizer = WordNetLemmatizer()
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = word_tokenize(text)
    text = [lemmatizer.lemmatize(word) for word in text if word not in stop_words]
    text = ' '.join(text)
    return text

def preprocess_text_by_sentence(text):
    stop_words = set(stopwords.words('english'))
    lemmatizer = WordNetLemmatizer()
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = sent_tokenize(text)
    text = [word_tokenize(sentence) for sentence in text]
    text = [[lemmatizer.lemmatize(word) for word in sentence if word not in stop_words] for sentence in text]
    text = [' '.join(sentence) for sentence in text]
    return text

train['tokenized_word'] = train['corrected_text'].apply(preprocess_text_by_word)
train['tokenized_sentence'] = train['corrected_text'].apply(preprocess_text_by_sentence)

train.head()

# <p style="font-family:JetBrains Mono; font-weight:bold; letter-spacing: 2px; color:#243139; font-size:140%; text-align:left;padding: 0px; border-bottom: 3px solid #000000"> <a name="eda"></a>Exploratory Data Analysis (EDA)</p>

In [ ]:
eda_df = train.copy()

In [ ]:
# Helper functions for EDA

def topic_modeling(texts, num_topics=5):
    """
    Perform topic modeling using LDA.
    """
    dictionary = corpora.Dictionary(texts)
    corpus = [dictionary.doc2bow(text) for text in tqdm(texts, desc='Creating corpus', leave=False)]
    lda_model = models.LdaModel(corpus, num_topics=num_topics, id2word=dictionary, passes=15)
    lda_display = gen.prepare(lda_model, corpus, dictionary)
    return lda_display

def sentiment_analysis(texts):
    """
    Perform sentiment analysis on the text using TextBlob.
    """
    return texts.apply(lambda x: TextBlob(x).sentiment.polarity)

def text_complexity(texts):
    """
    Calculate the Flesch Reading Ease score of the text using textstat.
    """
    return texts.apply(lambda x: flesch_reading_ease(x))

In [ ]:
tokenized_words = pd.Series(eda_df['tokenized_word'])

tokenized_sentences = pd.Series(eda_df['tokenized_sentence'])

In [ ]:

# Perform topic modeling on both summaries and prompts

print("Performing topic modeling on training text...")

lda_display_summaries = topic_modeling(tokenized_sentences)

print("Performing topic modeling on test text...")

lda_display_prompts = topic_modeling(tokenized_sentences)

# Perform sentiment analysis on summaries and prompts

print("Performing sentiment analysis on train...")

eda_df['sentiment'] = sentiment_analysis(eda_df['corrected_text'])

print("Performing sentiment analysis on test...")

# test['sentiment'] = sentiment_analysis(test['corrected_text'])

# Calculate text complexity for summaries and prompts

print("Calculating text complexity for train...")

eda_df['flesch_score'] = text_complexity(eda_df['corrected_text'])

# print("Calculating text complexity for test...")

# test['flesch_score'] = text_complexity(test['corrected_text'])

In [ ]:

# Visualize sentiment and text complexity using histograms
sns.histplot(eda_df['sentiment']).set_title('Sentiment Distribution in Essays')
plt.show()

In [ ]:
print('\n Preparing Visualizations.....')

sns.histplot(eda_df['flesch_score']).set_title('Flesch Reading Ease Score Distribution')
plt.show()

In [ ]:
# Named Entity Recognition (Limiting to first 100 rows for demonstration)

nlp = spacy.load("en_core_web_sm")
texts = ' '.join(eda_df['corrected_text'][:1000])
doc_text = nlp(texts)

print('\n Preparing Visualizations.....')

# Count the frequencies of named entity types in summaries and prompts

entity_freq_summaries = Counter([ent.label_ for ent in doc_text.ents])

# Visualize named entity frequencies

plt.figure(figsize=(10, 6))
plt.bar(entity_freq_summaries.keys(), entity_freq_summaries.values())
plt.title('Named Entity Frequency')
plt.xticks(rotation=45)
plt.show()

In [ ]:
# Preprocessing
# Placeholder for preprocessing code

# <p style="font-family:JetBrains Mono; font-weight:bold; letter-spacing: 2px; color:#243139; font-size:140%; text-align:left;padding: 0px; border-bottom: 3px solid #000000"> <a name="training"></a>Training</p>

In [4]:
def custom_train_validation_split(essays, test_size=0.2, random_state=56):
    
    """
    Custom function to perform train-validation split ensuring that
    the same prompt IDs are in both training and validation sets.

    Parameters:
    - summaries: DataFrame containing summaries and associated prompt_ids
    - prompts: DataFrame containing prompts and associated prompt_ids
    - test_size: Proportion of the dataset to be used as the validation set
    - random_state: Random seed for reproducibility

    Returns:
    - train_summaries: Training set containing summaries
    - validation_summaries: Validation set containing summaries
    - train_prompts: Training set containing prompts
    - validation_prompts: Validation set containing prompts
    """
    
    # Extract unique prompt IDs
    unique_essay_ids = essays['essay_id'].unique()

    # Split the unique prompt IDs into training and validation sets
    train_ids, validation_ids = train_test_split(unique_essay_ids, test_size=test_size, random_state=random_state)

    # Use these IDs to filter the original summaries and prompts DataFrames
    train_essays = essays[essays['essay_id'].isin(train_ids)]
    validation_essays = essays[essays['essay_id'].isin(validation_ids)]

    return train_essays, validation_essays

In [5]:
train_essays, validation_essays = custom_train_validation_split(train, test_size=0.25, random_state=42)

In [6]:
train_essays.head()

,essay_id,full_text,score,lowered,clean_text,corrected_text
1,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...
2,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,people always wish they had the same technolog...,people always wish they had the same technolog...
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,"dear, state senator\n\nthis is a letter to arg...",dear state senator this is a letter to argue i...,dear state senator this is a letter to argue i...
6,0033037,The posibilty of a face reconizing computer wo...,2,the posibilty of a face reconizing computer wo...,the posibilty of a face reconizing computer wo...,the possibility of a face recognizing computer...
7,0033bf4,What is the Seagoing Cowboys progam?\n\nIt was...,3,what is the seagoing cowboys progam?\n\nit was...,what is the seagoing cowboys progam it was to ...,what is the seagoing cowboys progam it was to ...

In [21]:
def extract_features(essay, col='corrected_text', tfidf_vectorizer=None):
    """
    Extracts TF-IDF features from a column of texts in a DataFrame.
    
    Parameters:
    - essay (DataFrame): DataFrame containing the essays.
    - col (str): The column name of the text data.
    - tfidf_vectorizer (TfidfVectorizer, optional): A pre-fitted TfidfVectorizer. If None, a new one will be fitted.
    
    Returns:
    - DataFrame: The DataFrame with TF-IDF features merged.
    - TfidfVectorizer: The fitted or provided TfidfVectorizer instance.
    """
    import pandas as pd
    from sklearn.feature_extraction.text import TfidfVectorizer
    
    if tfidf_vectorizer is None:
        tfidf_vectorizer = TfidfVectorizer(
            tokenizer=lambda x: x,
            preprocessor=lambda x: x,
            token_pattern=None,
            strip_accents='unicode',
            analyzer='word',
            ngram_range=(1,5),
            min_df=0.05,
            max_df=0.95,
            sublinear_tf=True,
        )
        train_tfid = tfidf_vectorizer.fit_transform(essay[col])
    else:
        train_tfid = tfidf_vectorizer.transform(essay[col])
    
    dense_matrix = train_tfid.toarray()
    df = pd.DataFrame(dense_matrix, columns=[f'tfid_{i}' for i in range(train_tfid.shape[1])])
    df['essay_id'] = essay['essay_id']
    train_feats = pd.merge(essay, df, on='essay_id', how='left')

    return train_feats, tfidf_vectorizer




def preprocess_data(essays, tfidf_vectorizer=None):
    
    """
    Preprocesses and computes features for a dataset with text summaries and prompts.
    
    Parameters:
    - summaries (DataFrame): DataFrame containing the text summaries.
    - prompts (DataFrame): DataFrame containing the text prompts.
    - tfidf_vectorizer (TfidfVectorizer, optional): A pre-fitted TfidfVectorizer.
    
    Returns:
    - DataFrame: The preprocessed and feature-engineered DataFrame.
    """
    
    print('Preprocessing Data.......')

    # Extract TF-IDF features

    essays, tfidf_vectorizer = extract_features(essays, col='corrected_text',
                                                         tfidf_vectorizer=tfidf_vectorizer)

    stop_words = set(stopwords.words('english'))
    
    print('Generating Text Based Features.......')

    # Compute word count, sentence count, text length, and stopword count
    essays['word_count'] = essays['corrected_text'].apply(lambda x: len(word_tokenize(x)))
    essays['sentence_count'] = essays['corrected_text'].apply(lambda x: len(sent_tokenize(x)))
    essays['len_text'] = essays['corrected_text'].str.len()
    essays['stop_count'] = essays['corrected_text'].apply(lambda x: len([word for word in word_tokenize(x) if word in stop_words]))
    
    import string

    essays['punct_count'] = essays['corrected_text'].apply(lambda x: len([char for char in x if char in string.punctuation]))
    essays['capital_count'] = essays['corrected_text'].apply(lambda x: len([word for word in word_tokenize(x) if word.isupper()]))
    
    from nltk import pos_tag

    essays['noun_count'] = essays['corrected_text'].apply(lambda x: len([word for word, pos in pos_tag(word_tokenize(x)) if pos.startswith('NN')]))
    
    from nltk import ne_chunk

    essays['ne_count'] = essays['corrected_text'].apply(lambda x: len([chunk for chunk in ne_chunk(pos_tag(word_tokenize(x))) if hasattr(chunk, 'label')]))
    essays['avg_word_len'] = essays['corrected_text'].apply(lambda x: sum(len(word) for word in word_tokenize(x)) / len(word_tokenize(x)) if len(word_tokenize(x)) > 0 else 0)
    essays['lex_div'] = essays['corrected_text'].apply(lambda x: len(set(word_tokenize(x))) / len(word_tokenize(x)) if len(word_tokenize(x)) > 0 else 0)
    
    from textblob import TextBlob

    essays['polarity'] = essays['corrected_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    essays['subjectivity'] = essays['corrected_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
    
    from collections import Counter

    essays['most_common_word_count'] = essays['corrected_text'].apply(lambda x: Counter(word_tokenize(x)).most_common(1)[0][1] if len(word_tokenize(x)) > 0 else 0)

    
    # # Calculate cosine similarity between the text and its corresponding prompt
    # print('Computing Cosine Similarity.......')
    # merged_data = compute_cosine_similarity(merged_data, 
    #                                         'treated_question_summaries', 
    #                                         'treated_question_prompts')
    
    return essays, tfidf_vectorizer


def compute_cosine_similarity(df, text_col, content_col):
    
    """
    Computes the cosine similarity between two columns of text in a DataFrame.
    
    Parameters:
    - df (DataFrame): The DataFrame containing the texts.
    - text_col (str): The name of the column containing the first set of texts.
    - content_col (str): The name of the column containing the second set of texts.
    
    Returns:
    - DataFrame: The DataFrame with an additional column for the computed cosine similarity.
    """
    
    # Combine texts from both columns to fit the TF-IDF vectorizer
    all_texts = df[text_col].tolist() + df[content_col].tolist()
    
    # Fit the TF-IDF vectorizer on the combined corpus
    vectorizer = TfidfVectorizer()
    vectorizer.fit(all_texts)
    
    # Generate TF-IDF vectors for both columns
    text_tfidf = vectorizer.transform(df[text_col])
    content_tfidf = vectorizer.transform(df[content_col])
    
    # Compute cosine similarity for each pair of text and content
    cosine_sim_values = [cosine_similarity(text_tfidf[i], content_tfidf[i])[0][0] for i in range(len(df))]
    
    # Add the computed cosine similarity values to the DataFrame
    df['cos_sim'] = cosine_sim_values
    
    return df

In [22]:
train_essays, tfidf_vectorizer_train = preprocess_data(train_essays)

Preprocessing Data.......
Generating Text Based Features.......

In [ ]:
validation_essays, _ = preprocess_data(validation_essays, tfidf_vectorizer=tfidf_vectorizer_train)

Preprocessing Data.......
Generating Text Based Features.......

In [ ]:
train_essays.head()

,essay_id,full_text,score,lowered,clean_text,corrected_text,tfid_0,tfid_1,tfid_2,tfid_3,...,stop_count,punct_count,capital_count,noun_count,ne_count,avg_word_len,lex_div,polarity,subjectivity,most_common_word_count
0,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,0.0,0.015852,0.0,0.0,...,199,0,0,69,0,3.865672,0.429851,0.101786,0.444643,16
1,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,people always wish they had the same technolog...,people always wish they had the same technolog...,0.0,0.000000,0.0,0.0,...,277,0,0,127,0,4.460980,0.408348,0.171804,0.458290,28
2,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,"dear, state senator\n\nthis is a letter to arg...",dear state senator this is a letter to argue i...,dear state senator this is a letter to argue i...,0.0,0.011288,0.0,0.0,...,195,0,0,101,0,4.665796,0.373368,0.165438,0.553994,39
3,0033037,The posibilty of a face reconizing computer wo...,2,the posibilty of a face reconizing computer wo...,the posibilty of a face reconizing computer wo...,the possibility of a face recognizing computer...,0.0,0.000000,0.0,0.0,...,93,0,0,46,0,4.666667,0.522222,0.014286,0.437500,12
4,0033bf4,What is the Seagoing Cowboys progam?\n\nIt was...,3,what is the seagoing cowboys progam?\n\nit was...,what is the seagoing cowboys progam it was to ...,what is the seagoing cowboys progam it was to ...,0.0,0.015139,0.0,0.0,...,175,0,0,68,0,4.423729,0.375706,0.245500,0.439167,22

In [ ]:
validation_essays.head()

,essay_id,full_text,score,lowered,clean_text,corrected_text,tfid_0,tfid_1,tfid_2,tfid_3,...,stop_count,punct_count,capital_count,noun_count,ne_count,avg_word_len,lex_div,polarity,subjectivity,most_common_word_count
0,000d118,Many people have car where they live. The thin...,3,many people have car where they live. the thin...,many people have car where they live the thing...,many people have car where they live the thing...,0.0,0.00000,0.0,0.0,...,264,0,0,127,0,4.253385,0.442940,0.179676,0.540916,21
1,001bdc0,"We all heard about Venus, the planet without a...",4,"we all heard about venus, the planet without a...",we all heard about venus the planet without al...,we all heard about venus the planet without al...,0.0,0.01178,0.0,0.0,...,202,0,0,126,0,4.871739,0.480435,0.122434,0.540318,29
2,0030e86,If I were to choose between keeping the electo...,4,if i were to choose between keeping the electo...,if i were to choose between keeping the electo...,if i were to choose between keeping the electo...,0.0,0.00000,0.0,0.0,...,190,0,0,92,0,4.807229,0.440964,0.126214,0.461245,20
3,0036253,The challenge of exploring Venus\n\nThis stori...,2,the challenge of exploring venus\n\nthis stori...,the challenge of exploring venus this storie i...,the challenge of exploring venus this storie i...,0.0,0.00000,0.0,0.0,...,135,0,0,96,0,4.866242,0.468153,0.110292,0.597625,33
4,0065bd6,Driverless cars should not exsist it can cause...,3,driverless cars should not exsist it can cause...,driverless cars should not exsist it can cause...,driverless cars should not exsist it can cause...,0.0,0.00000,0.0,0.0,...,159,0,0,67,0,4.427119,0.416949,0.059774,0.529511,14

In [ ]:
train_essays.columns

Index(['essay_id', 'full_text', 'score', 'lowered', 'clean_text',
       'corrected_text', 'tfid_0', 'tfid_1', 'tfid_2', 'tfid_3',
       ...
       'stop_count', 'punct_count', 'capital_count', 'noun_count', 'ne_count',
       'avg_word_len', 'lex_div', 'polarity', 'subjectivity',
       'most_common_word_count'],
      dtype='object', length=13817)

In [14]:
len(train_essays.columns)

13817

In [ ]:
len(validation_essays.columns)

In [17]:
drop_cols = ['full_text','lowered', 'clean_text',
       'corrected_text']

training = train_essays.copy()
validation = validation_essays.copy()

training.drop(columns=drop_cols, inplace= True)
validation.drop(columns=drop_cols, inplace= True)

In [18]:
training.head()

,essay_id,score,tfid_0,tfid_1,tfid_2,tfid_3,tfid_4,tfid_5,tfid_6,tfid_7,...,stop_count,punct_count,capital_count,noun_count,ne_count,avg_word_len,lex_div,polarity,subjectivity,most_common_word_count
0,000fe60,3,0.0,0.015852,0.0,0.0,0.000000,0.016168,0.014800,0.011238,...,199,0,0,69,0,3.865672,0.429851,0.101786,0.444643,16
1,001ab80,4,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.013669,0.021782,...,277,0,0,127,0,4.460980,0.408348,0.171804,0.458290,28
2,002ba53,3,0.0,0.011288,0.0,0.0,0.000000,0.019493,0.000000,0.000000,...,195,0,0,101,0,4.665796,0.373368,0.165438,0.553994,39
3,0033037,2,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,93,0,0,46,0,4.666667,0.522222,0.014286,0.437500,12
4,0033bf4,3,0.0,0.015139,0.0,0.0,0.023701,0.000000,0.019308,0.030767,...,175,0,0,68,0,4.423729,0.375706,0.245500,0.439167,22

In [19]:
validation.head()

,essay_id,score,tfid_0,tfid_1,tfid_2,tfid_3,tfid_4,tfid_5,tfid_6,tfid_7,...,stop_count,punct_count,capital_count,noun_count,ne_count,avg_word_len,lex_div,polarity,subjectivity,most_common_word_count
0,000d118,3,0.0,0.00000,0.0,0.0,0.0,0.0,0.021158,0.033943,...,264,0,0,127,0,4.253385,0.442940,0.179676,0.540916,21
1,001bdc0,4,0.0,0.01178,0.0,0.0,0.0,0.0,0.000000,0.000000,...,202,0,0,126,0,4.871739,0.480435,0.122434,0.540318,29
2,0030e86,4,0.0,0.00000,0.0,0.0,0.0,0.0,0.011856,0.000000,...,190,0,0,92,0,4.807229,0.440964,0.126214,0.461245,20
3,0036253,2,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,...,135,0,0,96,0,4.866242,0.468153,0.110292,0.597625,33
4,0065bd6,3,0.0,0.00000,0.0,0.0,0.0,0.0,0.007364,0.011814,...,159,0,0,67,0,4.427119,0.416949,0.059774,0.529511,14

In [ ]:
# training.to_parquet('data/training_features.parquet')
# validation.to_parquet('data/validation_features.parquet')

In [20]:
feature_cols = []

for col in training.columns:
    if (col != 'essay_id') and (col != 'score'):
        feature_cols.append(col) 


# Select relevant columns (replace with actual column names)

training_labels = training['score']

validation_labels = validation['score']

train_features = training[feature_cols].values

val_features = validation[feature_cols].values

# test_features = test[feature_cols].values


# Standardize the features if needed

scaler = StandardScaler()


train_features = scaler.fit_transform(train_features)

val_features = scaler.transform(val_features)

# test_features = scaler.transform(test_features)



# Optionally, convert back to DataFrame

train_labels = pd.DataFrame(training_labels, columns=['score'],
                             index=training_labels.index)

val_labels = pd.DataFrame(validation_labels, columns=['score'], 
                          index=validation_labels.index)

import pickle


with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

KeyError: "['tfid_13713', 'tfid_13714', 'tfid_13715', 'tfid_13716', 'tfid_13717', 'tfid_13718', 'tfid_13719', 'tfid_13720', 'tfid_13721', 'tfid_13722', 'tfid_13723', 'tfid_13724', 'tfid_13725', 'tfid_13726', 'tfid_13727', 'tfid_13728', 'tfid_13729', 'tfid_13730', 'tfid_13731', 'tfid_13732', 'tfid_13733', 'tfid_13734', 'tfid_13735', 'tfid_13736', 'tfid_13737', 'tfid_13738', 'tfid_13739', 'tfid_13740', 'tfid_13741', 'tfid_13742', 'tfid_13743', 'tfid_13744', 'tfid_13745', 'tfid_13746', 'tfid_13747', 'tfid_13748', 'tfid_13749', 'tfid_13750', 'tfid_13751', 'tfid_13752', 'tfid_13753', 'tfid_13754', 'tfid_13755', 'tfid_13756', 'tfid_13757', 'tfid_13758', 'tfid_13759', 'tfid_13760', 'tfid_13761', 'tfid_13762', 'tfid_13763', 'tfid_13764', 'tfid_13765', 'tfid_13766', 'tfid_13767', 'tfid_13768', 'tfid_13769', 'tfid_13770', 'tfid_13771', 'tfid_13772', 'tfid_13773', 'tfid_13774', 'tfid_13775', 'tfid_13776', 'tfid_13777', 'tfid_13778', 'tfid_13779', 'tfid_13780', 'tfid_13781', 'tfid_13782', 'tfid_13783', 'tfid_13784', 'tfid_13785', 'tfid_13786', 'tfid_13787', 'tfid_13788', 'tfid_13789', 'tfid_13790', 'tfid_13791', 'tfid_13792', 'tfid_13793', 'tfid_13794', 'tfid_13795', 'tfid_13796', 'tfid_13797'] not in index"

In [ ]:
scaler_path = 'scaler.pkl'

# Check if the file has been written correctly and is not empty
import os

if os.path.getsize(scaler_path) > 0:
    print(f"Scaler saved successfully in {scaler_path}.")
else:
    print(f"Failed to save scaler to {scaler_path}. File is empty.")

# <p style="font-family:JetBrains Mono; font-weight:bold; letter-spacing: 2px; color:#243139; font-size:140%; text-align:left;padding: 0px; border-bottom: 3px solid #000000"> <a name="inference"></a>Inference</p>

In [ ]:
# Inference
# Placeholder for inference code

# <p style="font-family:JetBrains Mono; font-weight:bold; letter-spacing: 2px; color:#243139; font-size:140%; text-align:left;padding: 0px; border-bottom: 3px solid #000000"> <a name="model-evaluation"></a>Model Evaluation</p>

In [ ]:
# Model Evaluation
# Placeholder for model evaluation code