# sklearn model with tensorflow keras tuner

In [ ]:
# ! python -m pip install --no-index --find-links=/kaggle/usr/lib/pip_install_permanent/my_packages -r /kaggle/usr/lib/pip_install_permanent/requirements.txt

In [ ]:
# import os
# os.environ['PACKAGE_DIR'] = '/kaggle/usr/lib/pip_install_permanent'

In [1]:
from helper_func import *
# # import helper_functions as hf
# import sys
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import string
# from spellchecker import SpellChecker
# from textblob import TextBlob
# from multiprocessing import Pool
# from tqdm import tqdm
# import numpy as np
# import pandas as pd
# # Preprocessing
# from nltk.tokenize import word_tokenize, sent_tokenize
# import operator
# from spellchecker import SpellChecker
# from tqdm import tqdm  # Import tqdm
# import re
# import inflect
# from wordsegment import load, segment
# from nltk.corpus import words
# word_list = set(words.words())
# from spellchecker import SpellChecker

# from tqdm.contrib.concurrent import process_map  # If this import fails, you might need to update tqdm

# import multiprocessing
 
# # Import Packages
# # import shutup; shutup.please()
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import tensorflow as tf
# import keras_tuner as kt
# import seaborn as sns

# from nltk.corpus import stopwords, wordnet
# from nltk.tokenize import word_tokenize, sent_tokenize
# from nltk import pos_tag, ne_chunk
# from textblob import TextBlob

# from textstat import flesch_reading_ease, smog_index

# import spacy
# from collections import Counter
# from gensim import corpora, models
# import pyLDAvis.gensim as gen
# import pyLDAvis
# import re

# # Machine Learning & Data Preprocessing

# from sklearn.preprocessing import StandardScaler, MinMaxScaler
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

# # Deep Learning

# from tensorflow.keras import layers
# from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.sequence import pad_sequences

# # Gensim
# # from gensim.models import Word2Vec, KeyedVectors
# import pandas as pd
# # Progress bar
# from tqdm import tqdm

# # Keras Tuner
# from keras_tuner.tuners import RandomSearch

# # # Setting logging levels and environment variables
# # tf.get_logger().setLevel(logging.ERROR)
# # os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# from textstat import flesch_reading_ease

# # from helper_functions import *
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import string
# from spellchecker import SpellChecker
# from textblob import TextBlob
# from multiprocessing import Pool
# from tqdm import tqdm
# import numpy as np
# import pandas as pd
# # Preprocessing
# from nltk.tokenize import word_tokenize, sent_tokenize
# import operator
# from spellchecker import SpellChecker
# from tqdm import tqdm  # Import tqdm
# import re
# import inflect
# from wordsegment import load, segment
# from nltk.corpus import words
# word_list = set(words.words())
# print('Packages Instaled......')
import sklearn
print(sklearn.__version__)

1.4.2

[nltk_data] Downloading package punkt to /home/jack/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/jack/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [2]:
import pandas as pd

deberta_train = pd.read_csv('/home/jack/github/kaggle/scoring/deberta_train_predictions.csv')
deberta_val = pd.read_csv('/home/jack/github/kaggle/scoring/deberta_val_predictions.csv')

In [3]:
deberta_full = pd.concat([deberta_train, deberta_val])

In [4]:
deberta_full.drop(columns=['clean_text', 'score'], inplace=True)

In [5]:
train = pd.read_csv('/home/jack/github/kaggle/scoring/data/train.csv')

In [6]:
print(deberta_full.shape, train.shape)

(17307, 7) (17307, 3)

In [7]:
# Combine train and deberta_full on essay_id

train = train.merge(deberta_full, on='essay_id')

In [8]:
train.to_parquet('train_with_deberta.parquet')

In [9]:
import os
from tqdm import tqdm

glove_path = 'data/glove-840B-300d.txt'

paragram_path = '/home/jack/github/kaggle/scoring/data/paragram-300-sl999.txt'

wiki_news_path = 'data/wiki-news-1M-300d.vec'


# Load embeddings

embeddings = parallel_load_embeddings([glove_path, paragram_path, wiki_news_path])

glove = embeddings["glove"]
paragram = embeddings["paragram"]
fasttext = embeddings["fasttext"]

[nltk_data] Downloading package punkt to /home/jack/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/jack/nltk_data...
[nltk_data] Downloading package punkt to /home/jack/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/jack/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/jack/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
Reading Embedding File: 0it [00:00, ?it/s][nltk_data] Downloading package punkt to /home/jack/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/jack/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
Reading Embedding File: 3208it [00:00, 32078.04it/s]

Loading embeddings from /home/jack/github/kaggle/scoring/data/paragram-300-sl999.txt
Loading embeddings from data/glove-840B-300d.txt
Loading embeddings from data/wiki-news-1M-300d.vec

Reading Embedding File: 999995it [00:32, 30945.63it/s]]
Reading Embedding File: 1000231it [00:32, 30872.38it/s]

Loaded embeddings from data/wiki-news-1M-300d.vec

Reading Embedding File: 1703756it [00:56, 30118.10it/s]
Reading Embedding File: 1769038it [00:56, 31031.89it/s]

Loaded embeddings from /home/jack/github/kaggle/scoring/data/paragram-300-sl999.txt

Reading Embedding File: 2194914it [01:12, 22350.73it/s]

Loaded embeddings from data/glove-840B-300d.txt

Reading Embedding File: 2196017it [01:12, 30320.33it/s]

In [10]:
train, oov_glove, oov_paragram, oov_fasttxt = spellcheck_and_correct_text(train, embeddings)

Starting text cleaning process.

Checking Vocabulary.................

Processing dataset.
Building vocabulary.

Populating Vocabulary: 100%|██████████| 17307/17307 [00:00<00:00, 24863.74it/s]

Vocabulary built.
Checking coverage.

Checking Words: 100%|██████████| 65918/65918 [00:00<00:00, 1710383.87it/s]

Coverage checked.
Checking coverage.

Checking Words: 100%|██████████| 65918/65918 [00:00<00:00, 1819630.59it/s]

Coverage checked.
Checking coverage.

Checking Words: 100%|██████████| 65918/65918 [00:00<00:00, 1957852.73it/s]

Coverage checked.
Processed dataset.
Adding Text Features.................

Complete.................

In [14]:
def custom_train_validation_split(essays, test_size=0.2, random_state=56):
    
    """
    Custom function to perform train-validation split ensuring that
    the same prompt IDs are in both training and validation sets.

    Parameters:
    - summaries: DataFrame containing summaries and associated prompt_ids
    - prompts: DataFrame containing prompts and associated prompt_ids
    - test_size: Proportion of the dataset to be used as the validation set
    - random_state: Random seed for reproducibility

    Returns:
    - train_summaries: Training set containing summaries
    - validation_summaries: Validation set containing summaries
    - train_prompts: Training set containing prompts
    - validation_prompts: Validation set containing prompts
    """

    from sklearn.model_selection import train_test_split

    
    # Extract unique prompt IDs
    unique_essay_ids = essays['essay_id'].unique()

    # Split the unique prompt IDs into training and validation sets
    train_ids, validation_ids = train_test_split(unique_essay_ids, test_size=test_size, random_state=random_state)

    # Use these IDs to filter the original summaries and prompts DataFrames
    train_essays = essays[essays['essay_id'].isin(train_ids)]
    validation_essays = essays[essays['essay_id'].isin(validation_ids)]

    return train_essays, validation_essays

In [15]:

train_essays, val_essays = custom_train_validation_split(train, test_size=0.25, random_state=42)

In [16]:
train_essays.head()

,essay_id,full_text,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,lowered,...,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score
1,000fe60,I am a scientist at NASA that is discussing th...,3,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,i am a scientist at nasa that is discussing th...,...,335,335.0,335,335,3.868657,11,1,-234.72,134.48,0.7050
2,001ab80,People always wish they had the same technolog...,4,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,people always wish they had the same technolog...,...,551,551.0,551,551,4.464610,15,1,-470.88,222.72,-0.7712
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,0.052828,0.680586,0.248129,0.016296,0.001250,0.000911,"dear, state senator\n\nthis is a letter to arg...",...,383,383.0,383,383,4.676240,13,1,-308.82,155.71,0.9836
6,0033037,The posibilty of a face reconizing computer wo...,2,0.110127,0.875541,0.012530,0.000799,0.000427,0.000577,the posibilty of a face reconizing computer wo...,...,179,179.0,179,179,4.670391,13,1,-93.30,74.51,-0.1566
7,0033bf4,What is the Seagoing Cowboys progam?\n\nIt was...,3,0.004650,0.469768,0.515730,0.009045,0.000419,0.000389,what is the seagoing cowboys progam?\n\nit was...,...,354,354.0,354,354,4.423729,14,1,-262.46,142.39,0.9960

In [ ]:
# import pandas as pd

# train_essays = pd.read_parquet('/home/jack/github/kaggle/scoring/train_essays.parquet')
# val_essays = pd.read_parquet('/home/jack/github/kaggle/scoring/validation_essays.parquet')

In [17]:
pd.set_option('display.max_columns', None)

train_essays.head()

,essay_id,full_text,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,lowered,clean_text,combined_dense_vector,dense_vec_0,dense_vec_1,dense_vec_2,dense_vec_3,dense_vec_4,dense_vec_5,dense_vec_6,dense_vec_7,dense_vec_8,dense_vec_9,dense_vec_10,dense_vec_11,dense_vec_12,dense_vec_13,dense_vec_14,dense_vec_15,dense_vec_16,dense_vec_17,dense_vec_18,dense_vec_19,dense_vec_20,dense_vec_21,dense_vec_22,dense_vec_23,dense_vec_24,dense_vec_25,dense_vec_26,dense_vec_27,dense_vec_28,dense_vec_29,dense_vec_30,dense_vec_31,dense_vec_32,dense_vec_33,dense_vec_34,dense_vec_35,dense_vec_36,dense_vec_37,dense_vec_38,dense_vec_39,dense_vec_40,dense_vec_41,dense_vec_42,dense_vec_43,dense_vec_44,dense_vec_45,dense_vec_46,dense_vec_47,dense_vec_48,dense_vec_49,dense_vec_50,dense_vec_51,dense_vec_52,dense_vec_53,dense_vec_54,dense_vec_55,dense_vec_56,dense_vec_57,dense_vec_58,dense_vec_59,dense_vec_60,dense_vec_61,dense_vec_62,dense_vec_63,dense_vec_64,dense_vec_65,dense_vec_66,dense_vec_67,dense_vec_68,dense_vec_69,dense_vec_70,dense_vec_71,dense_vec_72,dense_vec_73,dense_vec_74,dense_vec_75,dense_vec_76,dense_vec_77,dense_vec_78,dense_vec_79,dense_vec_80,dense_vec_81,dense_vec_82,dense_vec_83,dense_vec_84,dense_vec_85,dense_vec_86,dense_vec_87,dense_vec_88,dense_vec_89,dense_vec_90,dense_vec_91,dense_vec_92,dense_vec_93,dense_vec_94,dense_vec_95,dense_vec_96,dense_vec_97,dense_vec_98,dense_vec_99,dense_vec_100,dense_vec_101,dense_vec_102,dense_vec_103,dense_vec_104,dense_vec_105,dense_vec_106,dense_vec_107,dense_vec_108,dense_vec_109,dense_vec_110,dense_vec_111,dense_vec_112,dense_vec_113,dense_vec_114,dense_vec_115,dense_vec_116,dense_vec_117,dense_vec_118,dense_vec_119,dense_vec_120,dense_vec_121,dense_vec_122,dense_vec_123,dense_vec_124,dense_vec_125,dense_vec_126,dense_vec_127,dense_vec_128,dense_vec_129,dense_vec_130,dense_vec_131,dense_vec_132,dense_vec_133,dense_vec_134,dense_vec_135,dense_vec_136,dense_vec_137,dense_vec_138,dense_vec_139,dense_vec_140,dense_vec_141,dense_vec_142,dense_vec_143,dense_vec_144,dense_vec_145,dense_vec_146,dense_vec_147,dense_vec_148,dense_vec_149,dense_vec_150,dense_vec_151,dense_vec_152,dense_vec_153,dense_vec_154,dense_vec_155,dense_vec_156,dense_vec_157,dense_vec_158,dense_vec_159,dense_vec_160,dense_vec_161,dense_vec_162,dense_vec_163,dense_vec_164,dense_vec_165,dense_vec_166,dense_vec_167,dense_vec_168,dense_vec_169,dense_vec_170,dense_vec_171,dense_vec_172,dense_vec_173,dense_vec_174,dense_vec_175,dense_vec_176,dense_vec_177,dense_vec_178,dense_vec_179,dense_vec_180,dense_vec_181,dense_vec_182,dense_vec_183,dense_vec_184,dense_vec_185,dense_vec_186,dense_vec_187,dense_vec_188,dense_vec_189,dense_vec_190,dense_vec_191,dense_vec_192,dense_vec_193,dense_vec_194,dense_vec_195,dense_vec_196,dense_vec_197,dense_vec_198,dense_vec_199,dense_vec_200,dense_vec_201,dense_vec_202,dense_vec_203,dense_vec_204,dense_vec_205,dense_vec_206,dense_vec_207,dense_vec_208,dense_vec_209,dense_vec_210,dense_vec_211,dense_vec_212,dense_vec_213,dense_vec_214,dense_vec_215,dense_vec_216,dense_vec_217,dense_vec_218,dense_vec_219,dense_vec_220,dense_vec_221,dense_vec_222,dense_vec_223,dense_vec_224,dense_vec_225,dense_vec_226,dense_vec_227,dense_vec_228,dense_vec_229,dense_vec_230,dense_vec_231,dense_vec_232,dense_vec_233,dense_vec_234,dense_vec_235,dense_vec_236,dense_vec_237,dense_vec_238,dense_vec_239,dense_vec_240,dense_vec_241,dense_vec_242,dense_vec_243,dense_vec_244,dense_vec_245,dense_vec_246,dense_vec_247,dense_vec_248,dense_vec_249,dense_vec_250,dense_vec_251,dense_vec_252,dense_vec_253,dense_vec_254,dense_vec_255,dense_vec_256,dense_vec_257,dense_vec_258,dense_vec_259,dense_vec_260,dense_vec_261,dense_vec_262,dense_vec_263,dense_vec_264,dense_vec_265,dense_vec_266,dense_vec_267,dense_vec_268,dense_vec_269,dense_vec_270,dense_vec_271,dense_vec_272,dense_vec_273,dense_vec_274,dense_vec_275,dense_vec_276,dense_vec_277,dense_vec_278,dense_vec_279,dense_vec_280,dense_vec_281,dense_vec_282,dense_vec_283,dense_vec_284,dense_vec_285,dense_vec_286,dense_vec_287,dense_vec_288,dense_vec_289,dense_vec_290,dense_vec_291,dense_vec_292,dense_vec_293,dense_vec_294,dense_vec_295,dense_vec_296,dense_vec_297,dense_vec_298,dense_vec_299,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score
1,000fe60,I am a scientist at NASA that is discussing th...,3,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,"[-0.032712538, 0.04669811, -0.13660896, -0.048...",-0.032713,0.046698,-0.136609,-0.048152,0.047696,-0.004443,0.046734,-0.059357,-0.032121,1.285806,-0.119313,0.013975,0.056946,-0.060316,-0.078511,-0.004584,-0.048324,0.647274,-0.168202,-0.035725,0.034521,-0.028346,-0.034882,0.075648,0.048808,-0.033032,-0.067159,0.014139,0.124446,-0.031408,-0.002349,0.061957,0.034338,0.045260,0.034421,-0.019964,-0.022890,0.010729,-0.075448,-0.102107,-0.074799,0.080605,-0.019239,-0.022030,0.006664,0.034116,-0.055335,-0.057563,-0.011224,0.073920,-0.067545,0.040773,-0.200102,-0.008043,0.083470,-0.003326,-0.024546,-0.028617,0.018732,0.008175,0.035272,-0.025157,-0.090092,0.174079,0.019353,-0.090247,-0.073154,0.043198,0.050949,0.044592,-0.059415,0.071835,0.083959,-0.013087,-0.004838,0.019530,0.067745,-0.098724,0.036961,0.163368,0.042773,0.033691,-0.125996,-0.034199,0.028793,-0.237971,-0.058225,-0.280883,0.063932,-0.034725,-0.081763,0.017643,-0.058779,-0.005981,0.084234,0.040724,0.042815,-0.058148,0.004132,0.040302,-0.044956,0.096126,-0.094965,0.031231,0.028017,-0.319391,0.020466,-0.020388,0.019903,0.038596,-0.006203,-0.151156,0.042978,0.014991,0.065452,-0.019112,-0.040464,0.030046,-0.003441,-0.103580,0.063077,-0.098320,-0.006884,-0.040257,-0.019951,0.093513,0.018410,-0.059675,0.087255,-0.047970,-0.053383,-0.033300,-0.015919,0.006166,0.110885,-0.055347,-0.109681,-0.058883,-0.016135,-0.034800,-0.824161,0.017004,0.063604,0.120758,0.037935,-0.002126,-0.040530,0.072112,-0.064538,-0.094373,-0.031174,-0.044704,0.047332,-0.069864,-0.012384,-0.010360,-0.087732,-0.008455,-0.014778,-0.011045,0.005535,0.021092,-0.042645,-0.003463,-0.080103,-0.006808,0.057941,0.028832,0.103315,0.058213,-0.088466,-0.078980,0.039823,-0.087792,0.002323,0.061345,0.012442,-0.000126,-0.010545,-0.048735,0.056436,0.021782,-0.056678,-0.165973,-0.024925,-0.032815,-0.096127,-0.002867,0.118896,0.054701,0.024991,-0.009603,-0.202084,0.050876,0.073659,0.094858,-0.044689,-0.113991,0.045416,0.169860,-0.015575,0.055076,-0.008341,0.065086,0.116757,-0.078593,0.039199,0.021418,0.007993,-0.027354,-0.024936,-0.103732,-0.068246,-0.123329,-0.004008,0.103565,-0.106021,0.049907,-0.090531,0.023692,0.028011,0.009567,-0.040305,0.001069,0.087014,0.044982,-0.017972,0.106559,-0.028919,-0.030545,-0.118606,0.008301,0.109749,0.026450,-0.061610,-0.035989,0.038390,-0.005245,-0.184052,0.155121,0.084689,0.122408,0.000111,0.089325,0.080965,-0.117501,-0.007393,-0.087233,-0.095646,0.173983,0.083668,-0.114703,0.012775,0.005698,0.027230,0.141868,0.022690,0.051869,0.051189,0.029620,0.112520,0.066396,-0.042694,0.052129,-0.014629,-0.075908,0.024164,0.027144,0.179926,0.070649,0.050765,-0.016924,-0.059643,-0.018341,-0.011308,0.043099,-0.069518,-0.018552,0.066208,0.148774,0.093601,-0.005265,-0.001824,-0.067244,-0.019749,-0.105434,0.102756,-0.068079,0.051185,-0.012933,-0.065777,0.013292,-0.020224,-0.087896,0.132957,-0.000835,-0.043428,-0.026731,0.038848,0.080179,1,1,335,335.0,335,335,335.0,335,335,3.868657,11,1,-234.72,134.48,0.7050
2,001ab80,People always wish they had the same technolog...,4,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,people always wish they had the same technolog...,people always wish they had the same technolog...,"[-0.0034833213, 0.053125754, -0.1098204, -0.07...",-0.003483,0.053126,-0.109820,-0.076553,0.064854,-0.034473,0.040305,-0.084725,0.006507,1.325952,-0.111131,0.031189,0.073996,-0.034450,-0.100345,-0.016828,-0.082494,0.695776,-0.146310,-0.021674,-0.006636,-0.025182,-0.016390,-0.003493,0.035426,0.015223,-0.072644,-0.011722,0.119547,-0.048760,0.014189,-0.009935,-0.004579,0.080328,0.063146,-0.049035,0.017173,0.021852,-0.015964,-0.039959,-0.041504,0.102342,-0.012582,0.028158,-0.006109,0.027521,-0.033203,-0.064683,-0.007056,0.066666,-0.076527,-0.003866,-0.193947,0.004486,0.075519,0.013331,0.026105,-0.074785,-0.021101,-0.006930,0.059002,-0.028145,-0.052780,0.183155,0.031896,-0.015109,-0.028238,-0.010827,0.071940,0.064333,-0.069842,0.035723,0.128400,-0.012767,-0.024173,-0.024139,0.082791,-0.058949,0.051478,0.183144,0.028652,0.010402,-0.113171,-0.058827,0.002241,-0.192689,-0.115464,-0.154220,0.057216,-0.049360,-0.070581,0.052940,0.016445,-0.039322,0.039640,0.027091,0.063495,-0.042658,-0.002001,0.048027,-0.064977,0.074527,-0.082012,0.027653,0.095241,-0.393930,0.035515,0.040810,0.039972,0.083037,-0.012653,-0.138669,0.068344,-0.035966,0.039913,-0.045526,-0.004653,0.023350,-0.049928,-0.091381,0.053581,-0.082949,-0.003490,-0.069873,-0.003526,0.049308,0.065457,-0.041187,0.053435,-0.000077,-0.022821,0.005528,-0.036464,-0.011510,0.054127,-0.084789,-0.080017,-0.061253,-0.046376,-0.013909,-0.710956,-0.039063,0.157514,0.070110,0.032061,-0.057806,-0.026148,0.063357,0.039084,-0.036501,0.022767,-0.018787,0.090513,-0.058454,0.001590,-0.087572,-0.085389,-0.007191,-0.028017,-0.043578,-0.019670,0.043613,-0.022499,-0.003030,-0.049921,-0.049869,0.063097,0.006132,0.115662,0.023572,-0.050684,-0.005954,0.025533,-0.045689,0.014420,0.004212,0.035822,-0.024131,0.029666,-0.029246,0.050521,0.019596,-0.077628,-0.132521,-0.068981,-0.024217,-0.073660,-0.035777,0.086653,0.046742,0.087102,-0.016664,-0.113192,0.090741,0.070022,0.069655,-0.073104,-0.082429,0.025707,0.153377,-0.028602,0.006993,-0.020625,-0.019577,0.099316,-0.024216,0.026777,0.017824,0.038669,-0.014184,-0.075035,-0.095251,-0.060317,-0.082709,0.005431,0.101148,-0.074368,0.115339,-0.123442,0.001132,0.026840,-0.001408,-0.045826,0.000391,0.019393,0.010207,-0.034078,0.094191,-0.048466,-0.058971,-0.101445,-0.018623,0.131634,0.019118,-0.057258,-0.033586,0.042589,0.004257,-0.185027,0.166622,0.084277,0.095218,0.003934,0.123114,0.049328,-0.111467,-0.017738,-0.081914,-0.117823,0.173337,0.024265,-0.098834,-0.019283,-0.006835,0.001076,0.147008,0.014003,0.042332,0.051666,0.022643,0.130977,0.078248,-0.026629,0.062809,-0.047684,-0.070003,-0.030752,0.000582,0.184503,0.009034,0.111400,-0.011923,-0.020985,-0.047535,0.001933,0.058512,-0.029460,0.051345,0.054794,0.150601,0.019696,0.000855,0.052583,-0.030939,0.011797,-0.040528,0.100660,-0.061138,0.062459,-0.031331,-0.168369,-0.003437,0.020841,-0.108261,0.099127,-0.029729,-0.014295,-0.073321,0.060506,0.092429,1,1,551,551.0,551,551,551.0,551,551,4.464610,15,1,-470.88,222.72,-0.7712
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,0.052828,0.680586,0.248129,0.016296,0.001250,0.000911,"dear, state senator\n\nthis is a letter to arg...",dear state senator this is a letter to argue i...,"[-0.0073380726, 0.015529702, 0.016174192, -0.0...",-0.007338,0.015530,0.016174,-0.006898,0.019063,-0.018329,0.016975,-0.009071,0.010381,1.367668,-0.166174,0.059751,0.056506,-0.123201,-0.037016,-0.012361,-0.054963,0.552611,-0.089861,-0.016953,-0.039613,-0.072490,-0.014385,-0.052068,0.113689,-0.029473,-0.169476,0.031760,0.097549,0.013277,0.045731,0.050567,0.023579,0.031825,0.062989,-0.022020,-0.057784,-0.040928,-0.048233,-0.101182,-0.040843,0.183635,0.011011,0.027222,0.089476,-0.012664,-0.015374,0.002220,-0.003588,-0.003124,-0.075105,0.078262,-0.157704,-0.058356,0.050006,0.025387,0.037653,-0.001766,-0.003839,-0.010205,0.011765,0.062568,-0.095727,0.164034,-0.027951,0.019454,-0.019738,-0.049291,0.021017,0.042361,-0.018310,0.029316,0.072403,0.006667,-0.033488,-0.013306,0.030075,-0.018546,0.048322,0.151696,0.003850,0.023939,-0.068112,-0.054536,0.053323,-0.121416,-0.181323,-0.220333,0.045294,-0.057774,-0.067645,0.043449,0.021178,-0.021385,0.007285,-0.023710,0.038304,-0.021840,-0.037879,0.046593,-0.035505,0.093162,-0.085594,0.035817,0.035406,-0.337080,0.061420,0.010891,0.080845,0.011432,-0.013200,-0.108386,-0.057002,0.020057,0.010903,-0.012082,-0.107733,0.034366,-0.028460,-0.118671,0.035556,-0.016730,-0.025655,0.016826,-0.097333,0.036385,0.107515,-0.001109,0.057314,0.016269,-0.127519,0.039520,0.040537,-0.065917,0.074163,-0.044967,-0.084594,0.019964,-0.019137,-0.031557,-0.536052,0.008049,0.092564,0.121024,0.069262,-0.026980,0.007065,0.060149,0.041165,0.042582,0.036851,-0.018291,0.032252,-0.078362,0.021819,0.021960,-0.046161,-0.004725,-0.072247,-0.033177,-0.032321,0.055979,-0.026413,-0.016523,-0.197560,-0.027892,0.022140,0.010616,0.102092,0.030718,0.010709,-0.090178,0.056242,-0.008871,-0.003510,0.006888,0.074183,-0.098335,0.051569,-0.027799,0.042941,-0.045313,-0.088586,-0.202144,0.025992,0.040394,-0.051013,-0.027905,0.098808,0.022057,-0.007650,-0.015187,-0.164019,0.112436,0.146184,0.108754,-0.063650,-0.041872,-0.068532,0.119308,0.033701,0.124684,-0.093056,0.028846,0.107164,-0.069563,-0.008054,-0.011052,-0.047602,0.005380,-0.090578,0.020154,-0.113106,-0.084853,0.038603,0.139608,-0.131021,0.093421,-0.063594,0.042725,-0.007797,0.030095,-0.077815,-0.073227,0.045153,0.069696,0.000129,0.055424,0.046111,-0.016500,-0.054262,-0.028312,0.108520,0.001578,-0.146131,-0.064860,0.058095,0.021501,-0.222509,0.108750,0.048293,0.073937,0.054827,0.125249,0.043536,-0.137586,0.073796,-0.078355,-0.109795,0.130942,0.053489,-0.013682,-0.019521,-0.011844,0.018094,0.229178,-0.000784,0.015516,0.106967,-0.010381,0.078915,0.057778,-0.041484,0.096244,-0.019612,-0.113762,0.018927,-0.115009,0.126322,-0.073299,0.104574,0.015961,-0.078156,-0.023475,0.043359,0.063719,-0.010232,0.047228,0.026488,0.100735,0.053177,-0.012269,-0.015860,-0.010857,-0.005702,-0.073441,0.076493,-0.025840,0.090305,0.012302,-0.034805,-0.007414,0.048701,-0.115684,0.118522,0.004432,0.021477,-0.080859,0.009234,0.012399,1,1,383,383.0,383,383,383.0,383,383,4.676240,13,1,-308.82,155.71,0.9836
6,0033037,The posibilty of a face reconizing computer wo...,2,0.110127,0.875541,0.012530,0.000799,0.000427,0.000577,the posibilty of a face reconizing computer wo...,the posibilty of a face reconizing computer wo...,"[-0.032074902, 0.065870605, -0.118498474, -0.0...",-0.032075,0.065871,-0.118498,-0.042810,0.063599,-0.052338,0.059985,-0.028226,0.015508,1.272676,-0.136040,0.037969,0.039294,-0.038399,-0.041418,0.025996,-0.047409,0.659131,-0.185383,-0.028049,0.012320,-0.092598,-0.038730,0.004874,0.061049,-0.047244,-0.072019,-0.006578,0.129172,-0.043762,-0.055111,0.019337,0.054099,0.040739,0.057634,-0.039313,-0.004073,0.052086,-0.016344,-0.109417,-0.031574,0.082143,-0.066622,-0.025554,0.029063,0.047160,-0.033690,-0.035064,0.021725,0.034352,-0.097038,0.022536,-0.158017,0.002738,0.071174,0.002540,0.007133,-0.036035,-0.031675,0.026097,0.029399,-0.037657,-0.044362,0.103836,0.022283,-0.038240,-0.033004,0.042612,0.116959,0.069085,-0.044362,0.011279,0.128281,-0.035907,0.010480,0.037982,0.094914,-0.022477,0.039724,0.212526,0.021280,0.031157,-0.060721,-0.059667,0.058769,-0.140180,-0.099034,-0.193138,0.065286,0.013675,-0.117314,0.006835,-0.015280,-0.028296,0.049569,0.034413,0.116476,-0.073795,0.030497,0.035016,-0.052322,0.058609,-0.066629,-0.003806,0.088908,-0.355891,0.043210,0.027580,0.051176,0.028151,0.009495,-0.143706,-0.023710,-0.042064,0.045958,-0.077456,-0.038221,0.013019,-0.042639,-0.101388,0.108305,-0.087119,0.033390,-0.031363,0.003540,0.092995,0.035578,-0.026669,0.106394,-0.025372,0.014728,0.002619,-0.011820,0.028311,0.112867,-0.049973,-0.101802,-0.010190,-0.022608,-0.010103,-0.692278,-0.013190,0.056348,0.094023,0.030228,-0.010580,-0.021516,0.058123,-0.024854,-0.072584,0.016341,0.001785,0.047651,-0.043105,0.007642,-0.015927,-0.085868,-0.039391,-0.015655,-0.130426,-0.030505,0.021940,-0.021738,-0.024575,-0.050133,-0.040898,0.048162,-0.011335,0.106179,0.065260,-0.067349,-0.090215,0.103851,-0.061940,0.044764,0.031030,-0.011980,-0.021793,-0.006571,-0.050710,0.022449,-0.017180,-0.059229,-0.102202,-0.025790,0.035302,-0.074213,-0.002775,0.134865,0.004021,0.046789,0.022681,-0.205801,0.073317,0.062522,0.077822,-0.018078,-0.153876,0.062100,0.108709,0.021795,0.089174,-0.043507,0.012443,0.086020,-0.038508,0.036313,-0.000215,0.038400,0.019488,-0.049020,-0.054298,-0.097427,-0.127512,0.039426,0.067213,-0.105630,0.015738,-0.113644,0.019799,0.041431,-0.015328,-0.050182,-0.086600,0.001045,0.072771,-0.031397,0.065641,0.024291,-0.053022,-0.143961,-0.014015,0.100058,0.057845,-0.092749,-0.062460,0.043321,0.008413,-0.166832,0.119737,0.074061,0.099142,0.005982,0.077020,0.084503,-0.165216,-0.061754,-0.097756,-0.108793,0.210358,0.061107,-0.056499,-0.029219,0.003171,0.067029,0.121168,0.021918,0.009907,0.073160,0.055094,0.107256,0.083920,-0.025688,0.052793,-0.015226,-0.093456,-0.068362,0.003020,0.153370,0.012342,0.032799,0.007330,-0.062704,-0.050291,-0.072296,0.007562,-0.019953,0.021279,-0.005677,0.132875,0.025869,0.030862,0.024624,-0.084611,0.019655,-0.087435,0.108308,-0.022754,0.043010,-0.045912,-0.031393,-0.005021,0.007474,-0.057541,0.147721,0.066966,-0.015053,-0.040317,0.021414,0.108062,1,1,179,179.0,179,179,179.0,179,179,4.670391,13,1,-93.30,74.51,-0.1566

In [18]:
train_essays['score'].value_counts()

score
3    4706
2    3517
4    2988
1     926
5     731
6     112
Name: count, dtype: int64

In [19]:
drop_cols = [ 'full_text', 'lowered', 'clean_text', 'combined_dense_vector']


train_df = train_essays.copy()
val_df = val_essays.copy()

train_df.drop(columns=drop_cols, inplace= True)
val_df.drop(columns=drop_cols, inplace= True)

In [20]:
train_df.head()

,essay_id,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,dense_vec_0,dense_vec_1,dense_vec_2,dense_vec_3,dense_vec_4,dense_vec_5,dense_vec_6,dense_vec_7,dense_vec_8,dense_vec_9,dense_vec_10,dense_vec_11,dense_vec_12,dense_vec_13,dense_vec_14,dense_vec_15,dense_vec_16,dense_vec_17,dense_vec_18,dense_vec_19,dense_vec_20,dense_vec_21,dense_vec_22,dense_vec_23,dense_vec_24,dense_vec_25,dense_vec_26,dense_vec_27,dense_vec_28,dense_vec_29,dense_vec_30,dense_vec_31,dense_vec_32,dense_vec_33,dense_vec_34,dense_vec_35,dense_vec_36,dense_vec_37,dense_vec_38,dense_vec_39,dense_vec_40,dense_vec_41,dense_vec_42,dense_vec_43,dense_vec_44,dense_vec_45,dense_vec_46,dense_vec_47,dense_vec_48,dense_vec_49,dense_vec_50,dense_vec_51,dense_vec_52,dense_vec_53,dense_vec_54,dense_vec_55,dense_vec_56,dense_vec_57,dense_vec_58,dense_vec_59,dense_vec_60,dense_vec_61,dense_vec_62,dense_vec_63,dense_vec_64,dense_vec_65,dense_vec_66,dense_vec_67,dense_vec_68,dense_vec_69,dense_vec_70,dense_vec_71,dense_vec_72,dense_vec_73,dense_vec_74,dense_vec_75,dense_vec_76,dense_vec_77,dense_vec_78,dense_vec_79,dense_vec_80,dense_vec_81,dense_vec_82,dense_vec_83,dense_vec_84,dense_vec_85,dense_vec_86,dense_vec_87,dense_vec_88,dense_vec_89,dense_vec_90,dense_vec_91,dense_vec_92,dense_vec_93,dense_vec_94,dense_vec_95,dense_vec_96,dense_vec_97,dense_vec_98,dense_vec_99,dense_vec_100,dense_vec_101,dense_vec_102,dense_vec_103,dense_vec_104,dense_vec_105,dense_vec_106,dense_vec_107,dense_vec_108,dense_vec_109,dense_vec_110,dense_vec_111,dense_vec_112,dense_vec_113,dense_vec_114,dense_vec_115,dense_vec_116,dense_vec_117,dense_vec_118,dense_vec_119,dense_vec_120,dense_vec_121,dense_vec_122,dense_vec_123,dense_vec_124,dense_vec_125,dense_vec_126,dense_vec_127,dense_vec_128,dense_vec_129,dense_vec_130,dense_vec_131,dense_vec_132,dense_vec_133,dense_vec_134,dense_vec_135,dense_vec_136,dense_vec_137,dense_vec_138,dense_vec_139,dense_vec_140,dense_vec_141,dense_vec_142,dense_vec_143,dense_vec_144,dense_vec_145,dense_vec_146,dense_vec_147,dense_vec_148,dense_vec_149,dense_vec_150,dense_vec_151,dense_vec_152,dense_vec_153,dense_vec_154,dense_vec_155,dense_vec_156,dense_vec_157,dense_vec_158,dense_vec_159,dense_vec_160,dense_vec_161,dense_vec_162,dense_vec_163,dense_vec_164,dense_vec_165,dense_vec_166,dense_vec_167,dense_vec_168,dense_vec_169,dense_vec_170,dense_vec_171,dense_vec_172,dense_vec_173,dense_vec_174,dense_vec_175,dense_vec_176,dense_vec_177,dense_vec_178,dense_vec_179,dense_vec_180,dense_vec_181,dense_vec_182,dense_vec_183,dense_vec_184,dense_vec_185,dense_vec_186,dense_vec_187,dense_vec_188,dense_vec_189,dense_vec_190,dense_vec_191,dense_vec_192,dense_vec_193,dense_vec_194,dense_vec_195,dense_vec_196,dense_vec_197,dense_vec_198,dense_vec_199,dense_vec_200,dense_vec_201,dense_vec_202,dense_vec_203,dense_vec_204,dense_vec_205,dense_vec_206,dense_vec_207,dense_vec_208,dense_vec_209,dense_vec_210,dense_vec_211,dense_vec_212,dense_vec_213,dense_vec_214,dense_vec_215,dense_vec_216,dense_vec_217,dense_vec_218,dense_vec_219,dense_vec_220,dense_vec_221,dense_vec_222,dense_vec_223,dense_vec_224,dense_vec_225,dense_vec_226,dense_vec_227,dense_vec_228,dense_vec_229,dense_vec_230,dense_vec_231,dense_vec_232,dense_vec_233,dense_vec_234,dense_vec_235,dense_vec_236,dense_vec_237,dense_vec_238,dense_vec_239,dense_vec_240,dense_vec_241,dense_vec_242,dense_vec_243,dense_vec_244,dense_vec_245,dense_vec_246,dense_vec_247,dense_vec_248,dense_vec_249,dense_vec_250,dense_vec_251,dense_vec_252,dense_vec_253,dense_vec_254,dense_vec_255,dense_vec_256,dense_vec_257,dense_vec_258,dense_vec_259,dense_vec_260,dense_vec_261,dense_vec_262,dense_vec_263,dense_vec_264,dense_vec_265,dense_vec_266,dense_vec_267,dense_vec_268,dense_vec_269,dense_vec_270,dense_vec_271,dense_vec_272,dense_vec_273,dense_vec_274,dense_vec_275,dense_vec_276,dense_vec_277,dense_vec_278,dense_vec_279,dense_vec_280,dense_vec_281,dense_vec_282,dense_vec_283,dense_vec_284,dense_vec_285,dense_vec_286,dense_vec_287,dense_vec_288,dense_vec_289,dense_vec_290,dense_vec_291,dense_vec_292,dense_vec_293,dense_vec_294,dense_vec_295,dense_vec_296,dense_vec_297,dense_vec_298,dense_vec_299,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score
1,000fe60,3,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,-0.032713,0.046698,-0.136609,-0.048152,0.047696,-0.004443,0.046734,-0.059357,-0.032121,1.285806,-0.119313,0.013975,0.056946,-0.060316,-0.078511,-0.004584,-0.048324,0.647274,-0.168202,-0.035725,0.034521,-0.028346,-0.034882,0.075648,0.048808,-0.033032,-0.067159,0.014139,0.124446,-0.031408,-0.002349,0.061957,0.034338,0.045260,0.034421,-0.019964,-0.022890,0.010729,-0.075448,-0.102107,-0.074799,0.080605,-0.019239,-0.022030,0.006664,0.034116,-0.055335,-0.057563,-0.011224,0.073920,-0.067545,0.040773,-0.200102,-0.008043,0.083470,-0.003326,-0.024546,-0.028617,0.018732,0.008175,0.035272,-0.025157,-0.090092,0.174079,0.019353,-0.090247,-0.073154,0.043198,0.050949,0.044592,-0.059415,0.071835,0.083959,-0.013087,-0.004838,0.019530,0.067745,-0.098724,0.036961,0.163368,0.042773,0.033691,-0.125996,-0.034199,0.028793,-0.237971,-0.058225,-0.280883,0.063932,-0.034725,-0.081763,0.017643,-0.058779,-0.005981,0.084234,0.040724,0.042815,-0.058148,0.004132,0.040302,-0.044956,0.096126,-0.094965,0.031231,0.028017,-0.319391,0.020466,-0.020388,0.019903,0.038596,-0.006203,-0.151156,0.042978,0.014991,0.065452,-0.019112,-0.040464,0.030046,-0.003441,-0.103580,0.063077,-0.098320,-0.006884,-0.040257,-0.019951,0.093513,0.018410,-0.059675,0.087255,-0.047970,-0.053383,-0.033300,-0.015919,0.006166,0.110885,-0.055347,-0.109681,-0.058883,-0.016135,-0.034800,-0.824161,0.017004,0.063604,0.120758,0.037935,-0.002126,-0.040530,0.072112,-0.064538,-0.094373,-0.031174,-0.044704,0.047332,-0.069864,-0.012384,-0.010360,-0.087732,-0.008455,-0.014778,-0.011045,0.005535,0.021092,-0.042645,-0.003463,-0.080103,-0.006808,0.057941,0.028832,0.103315,0.058213,-0.088466,-0.078980,0.039823,-0.087792,0.002323,0.061345,0.012442,-0.000126,-0.010545,-0.048735,0.056436,0.021782,-0.056678,-0.165973,-0.024925,-0.032815,-0.096127,-0.002867,0.118896,0.054701,0.024991,-0.009603,-0.202084,0.050876,0.073659,0.094858,-0.044689,-0.113991,0.045416,0.169860,-0.015575,0.055076,-0.008341,0.065086,0.116757,-0.078593,0.039199,0.021418,0.007993,-0.027354,-0.024936,-0.103732,-0.068246,-0.123329,-0.004008,0.103565,-0.106021,0.049907,-0.090531,0.023692,0.028011,0.009567,-0.040305,0.001069,0.087014,0.044982,-0.017972,0.106559,-0.028919,-0.030545,-0.118606,0.008301,0.109749,0.026450,-0.061610,-0.035989,0.038390,-0.005245,-0.184052,0.155121,0.084689,0.122408,0.000111,0.089325,0.080965,-0.117501,-0.007393,-0.087233,-0.095646,0.173983,0.083668,-0.114703,0.012775,0.005698,0.027230,0.141868,0.022690,0.051869,0.051189,0.029620,0.112520,0.066396,-0.042694,0.052129,-0.014629,-0.075908,0.024164,0.027144,0.179926,0.070649,0.050765,-0.016924,-0.059643,-0.018341,-0.011308,0.043099,-0.069518,-0.018552,0.066208,0.148774,0.093601,-0.005265,-0.001824,-0.067244,-0.019749,-0.105434,0.102756,-0.068079,0.051185,-0.012933,-0.065777,0.013292,-0.020224,-0.087896,0.132957,-0.000835,-0.043428,-0.026731,0.038848,0.080179,1,1,335,335.0,335,335,335.0,335,335,3.868657,11,1,-234.72,134.48,0.7050
2,001ab80,4,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,-0.003483,0.053126,-0.109820,-0.076553,0.064854,-0.034473,0.040305,-0.084725,0.006507,1.325952,-0.111131,0.031189,0.073996,-0.034450,-0.100345,-0.016828,-0.082494,0.695776,-0.146310,-0.021674,-0.006636,-0.025182,-0.016390,-0.003493,0.035426,0.015223,-0.072644,-0.011722,0.119547,-0.048760,0.014189,-0.009935,-0.004579,0.080328,0.063146,-0.049035,0.017173,0.021852,-0.015964,-0.039959,-0.041504,0.102342,-0.012582,0.028158,-0.006109,0.027521,-0.033203,-0.064683,-0.007056,0.066666,-0.076527,-0.003866,-0.193947,0.004486,0.075519,0.013331,0.026105,-0.074785,-0.021101,-0.006930,0.059002,-0.028145,-0.052780,0.183155,0.031896,-0.015109,-0.028238,-0.010827,0.071940,0.064333,-0.069842,0.035723,0.128400,-0.012767,-0.024173,-0.024139,0.082791,-0.058949,0.051478,0.183144,0.028652,0.010402,-0.113171,-0.058827,0.002241,-0.192689,-0.115464,-0.154220,0.057216,-0.049360,-0.070581,0.052940,0.016445,-0.039322,0.039640,0.027091,0.063495,-0.042658,-0.002001,0.048027,-0.064977,0.074527,-0.082012,0.027653,0.095241,-0.393930,0.035515,0.040810,0.039972,0.083037,-0.012653,-0.138669,0.068344,-0.035966,0.039913,-0.045526,-0.004653,0.023350,-0.049928,-0.091381,0.053581,-0.082949,-0.003490,-0.069873,-0.003526,0.049308,0.065457,-0.041187,0.053435,-0.000077,-0.022821,0.005528,-0.036464,-0.011510,0.054127,-0.084789,-0.080017,-0.061253,-0.046376,-0.013909,-0.710956,-0.039063,0.157514,0.070110,0.032061,-0.057806,-0.026148,0.063357,0.039084,-0.036501,0.022767,-0.018787,0.090513,-0.058454,0.001590,-0.087572,-0.085389,-0.007191,-0.028017,-0.043578,-0.019670,0.043613,-0.022499,-0.003030,-0.049921,-0.049869,0.063097,0.006132,0.115662,0.023572,-0.050684,-0.005954,0.025533,-0.045689,0.014420,0.004212,0.035822,-0.024131,0.029666,-0.029246,0.050521,0.019596,-0.077628,-0.132521,-0.068981,-0.024217,-0.073660,-0.035777,0.086653,0.046742,0.087102,-0.016664,-0.113192,0.090741,0.070022,0.069655,-0.073104,-0.082429,0.025707,0.153377,-0.028602,0.006993,-0.020625,-0.019577,0.099316,-0.024216,0.026777,0.017824,0.038669,-0.014184,-0.075035,-0.095251,-0.060317,-0.082709,0.005431,0.101148,-0.074368,0.115339,-0.123442,0.001132,0.026840,-0.001408,-0.045826,0.000391,0.019393,0.010207,-0.034078,0.094191,-0.048466,-0.058971,-0.101445,-0.018623,0.131634,0.019118,-0.057258,-0.033586,0.042589,0.004257,-0.185027,0.166622,0.084277,0.095218,0.003934,0.123114,0.049328,-0.111467,-0.017738,-0.081914,-0.117823,0.173337,0.024265,-0.098834,-0.019283,-0.006835,0.001076,0.147008,0.014003,0.042332,0.051666,0.022643,0.130977,0.078248,-0.026629,0.062809,-0.047684,-0.070003,-0.030752,0.000582,0.184503,0.009034,0.111400,-0.011923,-0.020985,-0.047535,0.001933,0.058512,-0.029460,0.051345,0.054794,0.150601,0.019696,0.000855,0.052583,-0.030939,0.011797,-0.040528,0.100660,-0.061138,0.062459,-0.031331,-0.168369,-0.003437,0.020841,-0.108261,0.099127,-0.029729,-0.014295,-0.073321,0.060506,0.092429,1,1,551,551.0,551,551,551.0,551,551,4.464610,15,1,-470.88,222.72,-0.7712
4,002ba53,3,0.052828,0.680586,0.248129,0.016296,0.001250,0.000911,-0.007338,0.015530,0.016174,-0.006898,0.019063,-0.018329,0.016975,-0.009071,0.010381,1.367668,-0.166174,0.059751,0.056506,-0.123201,-0.037016,-0.012361,-0.054963,0.552611,-0.089861,-0.016953,-0.039613,-0.072490,-0.014385,-0.052068,0.113689,-0.029473,-0.169476,0.031760,0.097549,0.013277,0.045731,0.050567,0.023579,0.031825,0.062989,-0.022020,-0.057784,-0.040928,-0.048233,-0.101182,-0.040843,0.183635,0.011011,0.027222,0.089476,-0.012664,-0.015374,0.002220,-0.003588,-0.003124,-0.075105,0.078262,-0.157704,-0.058356,0.050006,0.025387,0.037653,-0.001766,-0.003839,-0.010205,0.011765,0.062568,-0.095727,0.164034,-0.027951,0.019454,-0.019738,-0.049291,0.021017,0.042361,-0.018310,0.029316,0.072403,0.006667,-0.033488,-0.013306,0.030075,-0.018546,0.048322,0.151696,0.003850,0.023939,-0.068112,-0.054536,0.053323,-0.121416,-0.181323,-0.220333,0.045294,-0.057774,-0.067645,0.043449,0.021178,-0.021385,0.007285,-0.023710,0.038304,-0.021840,-0.037879,0.046593,-0.035505,0.093162,-0.085594,0.035817,0.035406,-0.337080,0.061420,0.010891,0.080845,0.011432,-0.013200,-0.108386,-0.057002,0.020057,0.010903,-0.012082,-0.107733,0.034366,-0.028460,-0.118671,0.035556,-0.016730,-0.025655,0.016826,-0.097333,0.036385,0.107515,-0.001109,0.057314,0.016269,-0.127519,0.039520,0.040537,-0.065917,0.074163,-0.044967,-0.084594,0.019964,-0.019137,-0.031557,-0.536052,0.008049,0.092564,0.121024,0.069262,-0.026980,0.007065,0.060149,0.041165,0.042582,0.036851,-0.018291,0.032252,-0.078362,0.021819,0.021960,-0.046161,-0.004725,-0.072247,-0.033177,-0.032321,0.055979,-0.026413,-0.016523,-0.197560,-0.027892,0.022140,0.010616,0.102092,0.030718,0.010709,-0.090178,0.056242,-0.008871,-0.003510,0.006888,0.074183,-0.098335,0.051569,-0.027799,0.042941,-0.045313,-0.088586,-0.202144,0.025992,0.040394,-0.051013,-0.027905,0.098808,0.022057,-0.007650,-0.015187,-0.164019,0.112436,0.146184,0.108754,-0.063650,-0.041872,-0.068532,0.119308,0.033701,0.124684,-0.093056,0.028846,0.107164,-0.069563,-0.008054,-0.011052,-0.047602,0.005380,-0.090578,0.020154,-0.113106,-0.084853,0.038603,0.139608,-0.131021,0.093421,-0.063594,0.042725,-0.007797,0.030095,-0.077815,-0.073227,0.045153,0.069696,0.000129,0.055424,0.046111,-0.016500,-0.054262,-0.028312,0.108520,0.001578,-0.146131,-0.064860,0.058095,0.021501,-0.222509,0.108750,0.048293,0.073937,0.054827,0.125249,0.043536,-0.137586,0.073796,-0.078355,-0.109795,0.130942,0.053489,-0.013682,-0.019521,-0.011844,0.018094,0.229178,-0.000784,0.015516,0.106967,-0.010381,0.078915,0.057778,-0.041484,0.096244,-0.019612,-0.113762,0.018927,-0.115009,0.126322,-0.073299,0.104574,0.015961,-0.078156,-0.023475,0.043359,0.063719,-0.010232,0.047228,0.026488,0.100735,0.053177,-0.012269,-0.015860,-0.010857,-0.005702,-0.073441,0.076493,-0.025840,0.090305,0.012302,-0.034805,-0.007414,0.048701,-0.115684,0.118522,0.004432,0.021477,-0.080859,0.009234,0.012399,1,1,383,383.0,383,383,383.0,383,383,4.676240,13,1,-308.82,155.71,0.9836
6,0033037,2,0.110127,0.875541,0.012530,0.000799,0.000427,0.000577,-0.032075,0.065871,-0.118498,-0.042810,0.063599,-0.052338,0.059985,-0.028226,0.015508,1.272676,-0.136040,0.037969,0.039294,-0.038399,-0.041418,0.025996,-0.047409,0.659131,-0.185383,-0.028049,0.012320,-0.092598,-0.038730,0.004874,0.061049,-0.047244,-0.072019,-0.006578,0.129172,-0.043762,-0.055111,0.019337,0.054099,0.040739,0.057634,-0.039313,-0.004073,0.052086,-0.016344,-0.109417,-0.031574,0.082143,-0.066622,-0.025554,0.029063,0.047160,-0.033690,-0.035064,0.021725,0.034352,-0.097038,0.022536,-0.158017,0.002738,0.071174,0.002540,0.007133,-0.036035,-0.031675,0.026097,0.029399,-0.037657,-0.044362,0.103836,0.022283,-0.038240,-0.033004,0.042612,0.116959,0.069085,-0.044362,0.011279,0.128281,-0.035907,0.010480,0.037982,0.094914,-0.022477,0.039724,0.212526,0.021280,0.031157,-0.060721,-0.059667,0.058769,-0.140180,-0.099034,-0.193138,0.065286,0.013675,-0.117314,0.006835,-0.015280,-0.028296,0.049569,0.034413,0.116476,-0.073795,0.030497,0.035016,-0.052322,0.058609,-0.066629,-0.003806,0.088908,-0.355891,0.043210,0.027580,0.051176,0.028151,0.009495,-0.143706,-0.023710,-0.042064,0.045958,-0.077456,-0.038221,0.013019,-0.042639,-0.101388,0.108305,-0.087119,0.033390,-0.031363,0.003540,0.092995,0.035578,-0.026669,0.106394,-0.025372,0.014728,0.002619,-0.011820,0.028311,0.112867,-0.049973,-0.101802,-0.010190,-0.022608,-0.010103,-0.692278,-0.013190,0.056348,0.094023,0.030228,-0.010580,-0.021516,0.058123,-0.024854,-0.072584,0.016341,0.001785,0.047651,-0.043105,0.007642,-0.015927,-0.085868,-0.039391,-0.015655,-0.130426,-0.030505,0.021940,-0.021738,-0.024575,-0.050133,-0.040898,0.048162,-0.011335,0.106179,0.065260,-0.067349,-0.090215,0.103851,-0.061940,0.044764,0.031030,-0.011980,-0.021793,-0.006571,-0.050710,0.022449,-0.017180,-0.059229,-0.102202,-0.025790,0.035302,-0.074213,-0.002775,0.134865,0.004021,0.046789,0.022681,-0.205801,0.073317,0.062522,0.077822,-0.018078,-0.153876,0.062100,0.108709,0.021795,0.089174,-0.043507,0.012443,0.086020,-0.038508,0.036313,-0.000215,0.038400,0.019488,-0.049020,-0.054298,-0.097427,-0.127512,0.039426,0.067213,-0.105630,0.015738,-0.113644,0.019799,0.041431,-0.015328,-0.050182,-0.086600,0.001045,0.072771,-0.031397,0.065641,0.024291,-0.053022,-0.143961,-0.014015,0.100058,0.057845,-0.092749,-0.062460,0.043321,0.008413,-0.166832,0.119737,0.074061,0.099142,0.005982,0.077020,0.084503,-0.165216,-0.061754,-0.097756,-0.108793,0.210358,0.061107,-0.056499,-0.029219,0.003171,0.067029,0.121168,0.021918,0.009907,0.073160,0.055094,0.107256,0.083920,-0.025688,0.052793,-0.015226,-0.093456,-0.068362,0.003020,0.153370,0.012342,0.032799,0.007330,-0.062704,-0.050291,-0.072296,0.007562,-0.019953,0.021279,-0.005677,0.132875,0.025869,0.030862,0.024624,-0.084611,0.019655,-0.087435,0.108308,-0.022754,0.043010,-0.045912,-0.031393,-0.005021,0.007474,-0.057541,0.147721,0.066966,-0.015053,-0.040317,0.021414,0.108062,1,1,179,179.0,179,179,179.0,179,179,4.670391,13,1,-93.30,74.51,-0.1566
7,0033bf4,3,0.004650,0.469768,0.515730,0.009045,0.000419,0.000389,-0.014745,0.022309,-0.107477,-0.070887,0.054542,-0.017777,0.016451,-0.019688,-0.009280,1.329445,-0.142463,0.043401,0.085784,-0.076412,-0.036700,-0.073533,-0.083395,0.594980,-0.192711,-0.007933,0.009929,0.016093,-0.032935,0.008876,-0.037578,-0.009195,-0.053173,0.018374,0.119039,-0.029377,0.011777,-0.004542,-0.000648,0.043772,0.050277,-0.088588,-0.022592,0.010854,-0.051540,-0.042986,-0.110735,0.073115,-0.026408,-0.050392,0.015211,0.013102,-0.039871,-0.001760,0.024571,0.063696,-0.079018,0.002344,-0.148007,-0.048616,0.068836,0.007790,0.021678,-0.015996,-0.041131,0.012755,0.053557,-0.025932,-0.071262,0.190618,0.005656,-0.011720,-0.004620,0.043429,0.119877,0.047666,-0.010428,0.049948,0.116636,-0.037641,0.050737,-0.009244,0.102969,-0.046552,0.116260,0.143692,0.041211,0.012100,-0.130892,-0.080049,0.021917,-0.192183,-0.130850,-0.178382,0.082359,-0.028270,-0.081682,-0.011603,0.015856,0.015524,0.090056,0.010772,0.030634,-0.091554,-0.052806,0.054403,-0.080271,0.093436,-0.079393,0.020381,0.023911,-0.321845,0.079596,-0.020322,0.036824,0.001124,0.064943,-0.144108,0.051916,-0.001323,0.081893,-0.042791,-0.030184,0.032699,-0.062140,-0.129443,0.111285,-0.079879,0.033912,-0.034143,-0.019953,0.051918,0.055424,-0.014728,0.079700,-0.034618,-0.026447,-0.015642,-0.076690,0.010311,0.090071,-0.038030,-0.103226,-0.064781,-0.033024,-0.045375,-0.757830,0.003399,0.106763,0.081800,0.052876,-0.039916,-0.000628,0.088871,-0.077543,-0.084018,-0.016208,0.047606,0.050901,-0.102131,-0.032748,-0.036869,-0.056256,0.010576,-0.018542,-0.013982,0.062336,0.064539,-0.035292,-0.003732,-0.016423,0.000928,0.121990,-0.027984,0.091657,0.013764,-0.067508,-0.007606,0.078256,-0.019771,0.042812,0.063728,-0.012387,-0.000965,0.036267,-0.034696,0.043330,0.021540,-0.105537,-0.098408,-0.020550,-0.016488,-0.069687,-0.034544,0.107136,0.016134,0.037579,0.006719,-0.122454,0.029767,0.014679,0.104663,-0.049751,-0.116436,0.039083,0.112405,0.035837,0.037330,0.013378,0.054765,0.138952,-0.030679,0.076044,0.012821,0.012752,-0.035148,0.027260,-0.089633,-0.051192,-0.084864,0.004823,0.096047,-0.069396,0.079365,-0.107521,0.040529,0.023764,0.015108,-0.000219,-0.017288,0.040904,0.081330,-0.025446,0.129584,-0.068966,0.005133,-0.122108,-0.025888,0.117129,0.037898,-0.046449,-0.034377,0.037893,-0.012538,-0.174985,0.118329,0.052390,0.108847,0.004178,0.118281,0.077609,-0.101738,-0.054401,-0.085695,-0.166299,0.192446,0.094585,-0.051816,-0.070428,0.023274,0.064476,0.171674,0.035343,0.049263,0.006346,0.061122,0.082118,0.070863,-0.059479,0.094928,-0.043640,-0.079367,0.001909,0.018965,0.150407,0.011962,0.070678,-0.033749,-0.012110,-0.016630,-0.030282,0.062693,-0.045691,0.025609,0.031645,0.119018,0.015313,-0.011255,-0.009819,-0.046400,0.022651,-0.081064,0.119951,-0.060815,0.085450,0.022049,-0.093644,0.006680,-0.044701,-0.093238,0.127002,-0.017354,-0.015854,-0.049203,0.037991,0.066524,1,1,354,354.0,354,354,354.0,354,354,4.423729,14,1,-262.46,142.39,0.9960

In [21]:
feature_cols = []

for col in train_df.columns:
    if (col != 'essay_id') and (col != 'score'):
        feature_cols.append(col)

In [22]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pickle
import numpy as np

# Extract labels from the training and validation datasets
train_labels = train_df['score']  # Extracts 'score' column as the label
val_labels = val_df['score']

# Extract features for scaling
train_features = train_df[feature_cols] # Subset with only feature columns
val_features = val_df[feature_cols]

# Initialize the scaler
scaler = MinMaxScaler()  # Using StandardScaler for scaling

# Fit the scaler to the training features
scaler.fit(train_features)  # This defines the transformation based on the training data

# Transform training and validation features
train_feats_scaled = scaler.transform(train_features)  # Transforms the training data
val_feats_scaled = scaler.transform(val_features)  # Transforms the validation data

# Reassign the scaled features to the original DataFrames, keeping the same column names
train_df[feature_cols] = train_feats_scaled  # Replace the original features with scaled ones
val_df[feature_cols] = val_feats_scaled

# Save the scaler for later use
with open('sklearn_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)  # Persist the scaler for future use or reference

In [23]:
# Check if the file has been written correctly and is not empty
import os
scaler_path = 'sklearn_scaler.pkl'
if os.path.getsize(scaler_path) > 0:
    print(f"Scaler saved successfully in {scaler_path}.")
else:
    print(f"Failed to save scaler to {scaler_path}. File is empty.")

Scaler saved successfully in sklearn_scaler.pkl.

In [24]:
# Check if the scaler is StandardScaler
if isinstance(scaler, StandardScaler):
    print("The scaler is a StandardScaler.")
elif isinstance(scaler, MinMaxScaler):
    print("The scaler is a MinMaxScaler.")
else:
    print("The scaler is neither StandardScaler nor MinMaxScaler.")

The scaler is a MinMaxScaler.

In [25]:
train_df = pca_dataframe(train_df)
val_df = pca_dataframe(val_df)

In [26]:
train_df

,essay_id,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,dense_vec_0,dense_vec_1,dense_vec_2,dense_vec_3,dense_vec_4,dense_vec_5,dense_vec_6,dense_vec_7,dense_vec_8,dense_vec_9,dense_vec_10,dense_vec_11,dense_vec_12,dense_vec_13,dense_vec_14,dense_vec_15,dense_vec_16,dense_vec_17,dense_vec_18,dense_vec_19,dense_vec_20,dense_vec_21,dense_vec_22,dense_vec_23,dense_vec_24,dense_vec_25,dense_vec_26,dense_vec_27,dense_vec_28,dense_vec_29,dense_vec_30,dense_vec_31,dense_vec_32,dense_vec_33,dense_vec_34,dense_vec_35,dense_vec_36,dense_vec_37,dense_vec_38,dense_vec_39,dense_vec_40,dense_vec_41,dense_vec_42,dense_vec_43,dense_vec_44,dense_vec_45,dense_vec_46,dense_vec_47,dense_vec_48,dense_vec_49,dense_vec_50,dense_vec_51,dense_vec_52,dense_vec_53,dense_vec_54,dense_vec_55,dense_vec_56,dense_vec_57,dense_vec_58,dense_vec_59,dense_vec_60,dense_vec_61,dense_vec_62,dense_vec_63,dense_vec_64,dense_vec_65,dense_vec_66,dense_vec_67,dense_vec_68,dense_vec_69,dense_vec_70,dense_vec_71,dense_vec_72,dense_vec_73,dense_vec_74,dense_vec_75,dense_vec_76,dense_vec_77,dense_vec_78,dense_vec_79,dense_vec_80,dense_vec_81,dense_vec_82,dense_vec_83,dense_vec_84,dense_vec_85,dense_vec_86,dense_vec_87,dense_vec_88,dense_vec_89,dense_vec_90,dense_vec_91,dense_vec_92,dense_vec_93,dense_vec_94,dense_vec_95,dense_vec_96,dense_vec_97,dense_vec_98,dense_vec_99,dense_vec_100,dense_vec_101,dense_vec_102,dense_vec_103,dense_vec_104,dense_vec_105,dense_vec_106,dense_vec_107,dense_vec_108,dense_vec_109,dense_vec_110,dense_vec_111,dense_vec_112,dense_vec_113,dense_vec_114,dense_vec_115,dense_vec_116,dense_vec_117,dense_vec_118,dense_vec_119,dense_vec_120,dense_vec_121,dense_vec_122,dense_vec_123,dense_vec_124,dense_vec_125,dense_vec_126,dense_vec_127,dense_vec_128,dense_vec_129,dense_vec_130,dense_vec_131,dense_vec_132,dense_vec_133,dense_vec_134,dense_vec_135,dense_vec_136,dense_vec_137,dense_vec_138,dense_vec_139,dense_vec_140,dense_vec_141,dense_vec_142,dense_vec_143,dense_vec_144,dense_vec_145,dense_vec_146,dense_vec_147,dense_vec_148,dense_vec_149,dense_vec_150,dense_vec_151,dense_vec_152,dense_vec_153,dense_vec_154,dense_vec_155,dense_vec_156,dense_vec_157,dense_vec_158,dense_vec_159,dense_vec_160,dense_vec_161,dense_vec_162,dense_vec_163,dense_vec_164,dense_vec_165,dense_vec_166,dense_vec_167,dense_vec_168,dense_vec_169,dense_vec_170,dense_vec_171,dense_vec_172,dense_vec_173,dense_vec_174,dense_vec_175,dense_vec_176,dense_vec_177,dense_vec_178,dense_vec_179,dense_vec_180,dense_vec_181,dense_vec_182,dense_vec_183,dense_vec_184,dense_vec_185,dense_vec_186,dense_vec_187,dense_vec_188,dense_vec_189,dense_vec_190,dense_vec_191,dense_vec_192,dense_vec_193,dense_vec_194,dense_vec_195,dense_vec_196,dense_vec_197,dense_vec_198,dense_vec_199,dense_vec_200,dense_vec_201,dense_vec_202,dense_vec_203,dense_vec_204,dense_vec_205,dense_vec_206,dense_vec_207,dense_vec_208,dense_vec_209,dense_vec_210,dense_vec_211,dense_vec_212,dense_vec_213,dense_vec_214,dense_vec_215,dense_vec_216,dense_vec_217,dense_vec_218,dense_vec_219,dense_vec_220,dense_vec_221,dense_vec_222,dense_vec_223,dense_vec_224,dense_vec_225,dense_vec_226,dense_vec_227,dense_vec_228,dense_vec_229,dense_vec_230,dense_vec_231,dense_vec_232,dense_vec_233,dense_vec_234,dense_vec_235,dense_vec_236,dense_vec_237,dense_vec_238,dense_vec_239,dense_vec_240,dense_vec_241,dense_vec_242,dense_vec_243,dense_vec_244,dense_vec_245,dense_vec_246,dense_vec_247,dense_vec_248,dense_vec_249,dense_vec_250,dense_vec_251,dense_vec_252,dense_vec_253,dense_vec_254,dense_vec_255,dense_vec_256,dense_vec_257,dense_vec_258,dense_vec_259,dense_vec_260,dense_vec_261,dense_vec_262,dense_vec_263,dense_vec_264,dense_vec_265,dense_vec_266,dense_vec_267,dense_vec_268,dense_vec_269,dense_vec_270,dense_vec_271,dense_vec_272,dense_vec_273,dense_vec_274,dense_vec_275,dense_vec_276,dense_vec_277,dense_vec_278,dense_vec_279,dense_vec_280,dense_vec_281,dense_vec_282,dense_vec_283,dense_vec_284,dense_vec_285,dense_vec_286,dense_vec_287,dense_vec_288,dense_vec_289,dense_vec_290,dense_vec_291,dense_vec_292,dense_vec_293,dense_vec_294,dense_vec_295,dense_vec_296,dense_vec_297,dense_vec_298,dense_vec_299,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,cosine_mean,cosine_std,cosine_max,cosine_min,cluster,PCA_1,PCA_2,PCA_3
0,000fe60,3,0.015921,0.869969,0.166321,0.002354,0.000144,0.000225,0.456731,0.510847,0.243413,0.498075,0.502664,0.510814,0.690584,0.367192,0.349800,0.661768,0.422234,0.310885,0.453399,0.541769,0.509896,0.558759,0.617926,0.588445,0.559953,0.490350,0.663950,0.519893,0.430246,0.785366,0.565280,0.456810,0.720692,0.635424,0.543894,0.463361,0.476372,0.832154,0.707733,0.455843,0.270775,0.669277,0.389530,0.456784,0.188382,0.358515,0.508014,0.402091,0.516658,0.362093,0.454594,0.654634,0.369316,0.476901,0.431245,0.604423,0.467781,0.580496,0.354461,0.523921,0.565997,0.463768,0.391773,0.540281,0.579870,0.614356,0.513475,0.381502,0.346491,0.641298,0.507656,0.215312,0.304082,0.632220,0.344233,0.455246,0.389941,0.739314,0.425754,0.531240,0.443585,0.669285,0.497124,0.268624,0.434784,0.595804,0.648118,0.514616,0.383679,0.532851,0.473708,0.277549,0.537248,0.309933,0.566716,0.416355,0.520098,0.496831,0.202840,0.611098,0.707900,0.668378,0.446281,0.422813,0.620634,0.460712,0.486511,0.613540,0.389350,0.536660,0.451098,0.527182,0.374109,0.378263,0.358892,0.548203,0.437381,0.394545,0.524522,0.649388,0.602235,0.554024,0.605191,0.494107,0.563848,0.446162,0.442679,0.328157,0.473672,0.410371,0.540675,0.591197,0.415102,0.382139,0.680050,0.445595,0.464961,0.274714,0.481334,0.555515,0.631213,0.566974,0.280955,0.312397,0.690317,0.473215,0.347980,0.658827,0.361889,0.621514,0.487208,0.551401,0.470030,0.488854,0.365921,0.348677,0.236691,0.419607,0.463238,0.449530,0.498013,0.544097,0.419239,0.489313,0.614430,0.766807,0.463406,0.546594,0.462641,0.488632,0.422671,0.609482,0.414719,0.679544,0.586630,0.566932,0.339356,0.315201,0.437883,0.411290,0.514116,0.583254,0.397515,0.626028,0.410751,0.466482,0.625300,0.521932,0.556265,0.311625,0.524858,0.276842,0.403033,0.500837,0.566843,0.686867,0.355090,0.460614,0.224427,0.433331,0.416719,0.528770,0.569005,0.495594,0.656855,0.779336,0.521942,0.465589,0.571392,0.560831,0.653227,0.240406,0.520146,0.605600,0.567417,0.574906,0.603294,0.302133,0.505811,0.319234,0.410002,0.485927,0.429240,0.373295,0.438179,0.489075,0.463245,0.554995,0.456771,0.668716,0.800250,0.520729,0.527615,0.576868,0.467863,0.459145,0.355101,0.606078,0.467538,0.505318,0.639029,0.474721,0.573379,0.432314,0.448356,0.672005,0.565185,0.616156,0.507243,0.485608,0.571461,0.441421,0.565978,0.421362,0.651363,0.529187,0.737990,0.377622,0.541437,0.606611,0.440447,0.375130,0.530741,0.469024,0.542124,0.623352,0.530946,0.443428,0.464046,0.519176,0.571042,0.472334,0.596663,0.606014,0.707226,0.724404,0.450054,0.540733,0.300551,0.496960,0.492214,0.526468,0.295146,0.317239,0.682788,0.563489,0.706234,0.389702,0.557918,0.360153,0.271773,0.287825,0.477937,0.508834,0.512716,0.418130,0.571948,0.560332,0.408931,0.428068,0.536585,0.506139,0.332660,0.450418,0.486313,0.591158,0.0,0.0,0.122842,0.122842,0.122842,0.122842,0.122842,0.122842,0.122842,0.207050,0.09375,0.0,0.877740,0.121900,0.852589,0.946271,0.018241,1.0,0.848127,0,-0.515670,-0.916843,-0.511049
1,001ab80,4,0.000313,0.008578,0.391804,0.778231,0.016489,0.001209,0.585345,0.540790,0.338812,0.323688,0.589370,0.331264,0.645055,0.272249,0.551038,0.723234,0.463918,0.426372,0.542078,0.646965,0.428410,0.490323,0.398302,0.686362,0.661014,0.552119,0.478626,0.539869,0.533003,0.425918,0.502828,0.710530,0.698656,0.486638,0.521324,0.385274,0.554675,0.519337,0.505481,0.627996,0.388181,0.470596,0.611287,0.512189,0.536547,0.622235,0.676480,0.498486,0.556789,0.605915,0.383206,0.617952,0.506396,0.439928,0.455883,0.568387,0.421833,0.355650,0.387829,0.601504,0.523088,0.566251,0.675612,0.320520,0.385162,0.520618,0.632818,0.369961,0.562333,0.693736,0.572846,0.523263,0.597395,0.343516,0.451439,0.585366,0.337635,0.560268,0.634521,0.533129,0.355224,0.454396,0.573001,0.481087,0.509666,0.672653,0.569139,0.389484,0.448743,0.373812,0.323052,0.486102,0.397017,0.627723,0.536680,0.334687,0.579412,0.693528,0.560807,0.458922,0.477773,0.591246,0.553695,0.496273,0.586623,0.496268,0.363200,0.498556,0.473036,0.514769,0.754488,0.331787,0.445608,0.673653,0.458945,0.738717,0.405991,0.470779,0.635485,0.399611,0.466342,0.412145,0.760974,0.461796,0.339134,0.526864,0.396136,0.404991,0.494411,0.295552,0.613244,0.322403,0.609640,0.462218,0.460080,0.716031,0.573987,0.479620,0.381323,0.472377,0.334936,0.391890,0.466090,0.301393,0.476939,0.605438,0.508652,0.396404,0.701672,0.335377,0.453704,0.248535,0.552589,0.441562,0.785002,0.597069,0.582049,0.536047,0.678529,0.523878,0.587143,0.182005,0.433157,0.494203,0.544700,0.638408,0.356254,0.669821,0.581365,0.491177,0.527241,0.354380,0.441771,0.564610,0.653757,0.332334,0.542246,0.693758,0.371163,0.598039,0.567371,0.278836,0.531560,0.515858,0.645660,0.572466,0.588792,0.510929,0.440158,0.440590,0.335101,0.325840,0.534519,0.358796,0.373308,0.648085,0.670011,0.410191,0.564545,0.609836,0.403166,0.383139,0.385371,0.654132,0.580341,0.711688,0.457027,0.211976,0.503167,0.242514,0.555774,0.600292,0.448686,0.582135,0.692643,0.641820,0.297849,0.335747,0.548409,0.493426,0.455949,0.473180,0.591269,0.692486,0.296529,0.352637,0.456176,0.491389,0.425697,0.664774,0.470144,0.353676,0.425539,0.521726,0.373123,0.325641,0.436413,0.434575,0.601028,0.463288,0.657336,0.488060,0.594277,0.474406,0.441821,0.724417,0.563285,0.493349,0.526599,0.626895,0.404078,0.473417,0.530318,0.451883,0.569699,0.526899,0.447333,0.450245,0.431223,0.547840,0.310236,0.393989,0.467882,0.423068,0.544790,0.583959,0.623300,0.508600,0.544003,0.582202,0.372366,0.499498,0.353244,0.504928,0.719435,0.488659,0.661425,0.568998,0.521795,0.346570,0.563192,0.592672,0.512466,0.681869,0.617730,0.571629,0.389419,0.420890,0.847449,0.571299,0.483742,0.593946,0.466201,0.544514,0.583487,0.320188,0.209596,0.472469,0.592030,0.315474,0.362051,0.355566,0.478113,0.209214,0.617850,0.652491,0.0,0.0,0.266268,0.266268,0.266268,0.266268,0.266268,0.266268,0.266268,0.482872,0.21875,0.0,0.723142,0.268666,0.113935,0.950616,0.020129,1.0,0.862118,2,1.098929,0.366285,-0.245064
2,002ba53,3,0.054838,0.711027,0.280640,0.019367,0.001528,0.001423,0.568383,0.365648,0.787502,0.751387,0.357968,0.427789,0.479846,0.555395,0.571221,0.787104,0.183489,0.617987,0.451114,0.286021,0.664753,0.515289,0.575256,0.397336,0.921610,0.572874,0.330132,0.241148,0.544150,0.205294,0.868079,0.475525,0.309630,0.736806,0.419962,0.664455,0.704017,0.782594,0.651816,0.389888,0.387538,0.655222,0.196383,0.199481,0.347674,0.362441,0.679825,0.858983,0.699013,0.601369,0.917452,0.394425,0.616827,0.787343,0.476385,0.221697,0.429109,0.769332,0.584324,0.212366,0.385400,0.640429,0.740327,0.668093,0.469543,0.500301,0.395253,0.720337,0.313894,0.583255,0.261790,0.664920,0.652898,0.137973,0.191366,0.440543,0.596156,0.528501,0.371471,0.647839,0.312652,0.507706,0.307154,0.696906,0.493390,0.550446,0.430421,0.462218,0.677338,0.401525,0.612896,0.814353,0.235665,0.461848,0.483358,0.287736,0.594985,0.640641,0.583330,0.540789,0.310809,0.303820,0.422845,0.594997,0.387666,0.489668,0.544720,0.597761,0.449897,0.564721,0.484444,0.480812,0.568683,0.529241,0.662720,0.431757,0.403332,0.655645,0.087154,0.674220,0.311991,0.591786,0.312559,0.514956,0.442906,0.346334,0.307793,0.735996,0.358957,0.631681,0.198780,0.243825,0.783546,0.635815,0.485310,0.808333,0.200494,0.659009,0.756153,0.216470,0.439526,0.628708,0.437525,0.678548,0.669132,0.493737,0.756895,0.616914,0.466672,0.623020,0.665876,0.416213,0.743245,0.424236,0.793419,0.936498,0.672217,0.538275,0.388051,0.394157,0.716175,0.695667,0.666130,0.503743,0.311743,0.679460,0.302471,0.737486,0.558296,0.411844,0.015720,0.484573,0.226863,0.587311,0.579980,0.380730,0.871928,0.257152,0.514548,0.761342,0.488436,0.293098,0.751494,0.175293,0.773612,0.580335,0.542001,0.184131,0.379427,0.172179,0.744167,0.694039,0.667055,0.392771,0.446267,0.527801,0.189594,0.420734,0.370073,0.705892,0.686960,0.609066,0.446469,0.857852,0.214484,0.571858,0.767490,0.832737,0.100911,0.424576,0.599627,0.300168,0.248300,0.393606,0.340466,0.741218,0.203086,0.793166,0.264785,0.484229,0.617415,0.676014,0.301269,0.585567,0.554122,0.604185,0.247205,0.673970,0.245664,0.236526,0.595897,0.639449,0.642346,0.348895,0.831528,0.525108,0.659980,0.372858,0.460038,0.362735,0.283553,0.314425,0.671442,0.550793,0.190609,0.460691,0.397352,0.397233,0.784301,0.635824,0.373431,0.334914,0.845837,0.472308,0.599262,0.376638,0.590325,0.839934,0.430405,0.524353,0.394961,0.695492,0.360872,0.293845,0.854089,0.397495,0.362793,0.396032,0.470069,0.779503,0.541093,0.298182,0.573451,0.065033,0.564224,0.173647,0.637632,0.726594,0.194597,0.470513,0.785264,0.615036,0.616784,0.660391,0.456397,0.349415,0.532945,0.354008,0.483224,0.688092,0.366161,0.438712,0.330928,0.725963,0.758285,0.552474,0.681343,0.451580,0.716245,0.274436,0.462111,0.533589,0.656720,0.170188,0.306464,0.251797,0.0,0.0,0.154714,0.154714,0.154714,0.154714,0.154714,0.154714,0.154714,0.580820,0.15625,0.0,0.829232,0.157211,0.991994,0.911187,0.025996,1.0,0.813989,1,-1.032145,0.819954,2.531095
3,0033037,2,0.115234,0.915460,0.009655,0.000243,0.000314,0.000675,0.459536,0.600162,0.307908,0.530877,0.583031,0.224449,0.784421,0.483706,0.597929,0.641665,0.337016,0.471855,0.361589,0.630906,0.648326,0.729668,0.623812,0.612381,0.480641,0.524095,0.563980,0.114178,0.408861,0.463917,0.622408,0.382088,0.701168,0.516234,0.565671,0.407765,0.226568,0.646704,0.810434,0.433650,0.365651,0.537036,0.493688,0.662784,0.534325,0.327496,0.726728,0.408909,0.231009,0.344975,0.579786,0.727189,0.503382,0.593735,0.626025,0.407865,0.316913,0.488639,0.582624,0.590677,0.499640,0.499863,0.569297,0.504970,0.333476,0.725563,0.483940,0.333220,0.611031,0.235444,0.522886,0.428463,0.566268,0.629090,0.681358,0.616694,0.465460,0.439075,0.633959,0.396536,0.513590,0.760083,0.634140,0.675909,0.449037,0.786828,0.527906,0.501001,0.714833,0.368391,0.643794,0.727936,0.437268,0.530080,0.572773,0.686428,0.331521,0.436605,0.409838,0.509247,0.529014,0.632674,0.828895,0.348607,0.766838,0.436381,0.441147,0.413814,0.572432,0.322268,0.725906,0.431502,0.482164,0.609796,0.514806,0.503430,0.513768,0.440027,0.232790,0.369722,0.498511,0.240630,0.614947,0.411944,0.374367,0.460664,0.664358,0.384149,0.719797,0.444854,0.644463,0.588048,0.486090,0.525103,0.804533,0.573196,0.707938,0.464269,0.501288,0.659675,0.641562,0.598935,0.330132,0.538520,0.644647,0.629524,0.535162,0.517503,0.335633,0.470475,0.443250,0.505419,0.579176,0.413291,0.526416,0.442196,0.540907,0.628472,0.464830,0.623890,0.625747,0.517992,0.430310,0.369643,0.609810,0.295644,0.310190,0.551235,0.585850,0.364498,0.526507,0.407526,0.363408,0.476169,0.602202,0.614657,0.452757,0.256961,0.736846,0.525957,0.700957,0.421727,0.257493,0.526587,0.433966,0.455742,0.415523,0.325776,0.542127,0.557476,0.521134,0.665023,0.531284,0.501232,0.662697,0.439922,0.465611,0.691147,0.210205,0.532691,0.375221,0.430329,0.740975,0.295247,0.721627,0.528360,0.708158,0.645440,0.376090,0.362902,0.481484,0.505701,0.503544,0.464360,0.691542,0.812899,0.456458,0.498069,0.349027,0.301294,0.621423,0.294206,0.431242,0.206613,0.338699,0.465531,0.544211,0.410712,0.401186,0.158733,0.380574,0.654220,0.442526,0.394442,0.725766,0.353578,0.234962,0.463927,0.408418,0.685298,0.508069,0.327754,0.597919,0.492817,0.563774,0.510759,0.516175,0.511075,0.536971,0.434156,0.590183,0.188400,0.378597,0.360974,0.602951,0.658114,0.627599,0.643986,0.397065,0.594760,0.638592,0.299176,0.525155,0.266814,0.665004,0.767189,0.504603,0.539791,0.548686,0.523095,0.567455,0.391603,0.186535,0.514206,0.636380,0.501315,0.387424,0.677811,0.283033,0.332372,0.165273,0.373827,0.564047,0.525021,0.273067,0.492639,0.415879,0.573812,0.698661,0.259151,0.536544,0.372712,0.509011,0.741828,0.461403,0.242561,0.693392,0.464152,0.532430,0.595885,0.612760,0.859473,0.474330,0.380084,0.380434,0.730764,0.0,0.0,0.019256,0.019256,0.019256,0.019256,0.019256,0.019256,0.019256,0.578112,0.15625,0.0,0.970319,0.022155,0.421466,0.935460,0.018001,1.0,0.848509,2,0.087499,-1.190095,0.120823
4,0033bf4,3,0.004056,0.489960,0.588431,0.010419,0.000303,0.000255,0.535790,0.397227,0.347157,0.358479,0.537258,0.431089,0.476136,0.515658,0.468795,0.728582,0.304290,0.508300,0.603386,0.476310,0.665931,0.173405,0.392505,0.482872,0.446812,0.612531,0.553214,0.800497,0.441065,0.482094,0.162116,0.582143,0.776885,0.659789,0.518982,0.472501,0.543258,0.542802,0.525907,0.448538,0.335580,0.200272,0.391180,0.457405,0.328321,0.609388,0.326180,0.368874,0.473438,0.224307,0.502367,0.537746,0.465100,0.766675,0.642848,0.553634,0.409092,0.386929,0.636897,0.272681,0.487024,0.532164,0.650805,0.600356,0.287254,0.642776,0.605432,0.378509,0.455421,0.736854,0.436464,0.537154,0.751625,0.633454,0.696261,0.475511,0.635698,0.630798,0.579259,0.386302,0.697569,0.527693,0.674760,0.547309,0.843841,0.519345,0.639379,0.398606,0.358839,0.236770,0.434696,0.488433,0.359322,0.567101,0.649138,0.452374,0.520526,0.333857,0.558007,0.709253,0.737943,0.498913,0.383009,0.264384,0.304894,0.525616,0.269005,0.599223,0.489958,0.470268,0.432565,0.520747,0.655034,0.378579,0.443252,0.387567,0.783596,0.437574,0.563618,0.569422,0.689711,0.426832,0.649910,0.506912,0.280100,0.275073,0.678963,0.420336,0.722984,0.434075,0.540663,0.338274,0.568151,0.576826,0.630916,0.520989,0.561051,0.367903,0.185509,0.575013,0.522563,0.669959,0.321242,0.285007,0.571150,0.406283,0.442124,0.595146,0.518045,0.401419,0.572419,0.345848,0.699083,0.579373,0.313326,0.393125,0.332510,0.834338,0.481034,0.239281,0.368125,0.419781,0.606176,0.562934,0.594608,0.755215,0.704885,0.784321,0.505974,0.487049,0.643300,0.655312,0.750791,0.391870,0.523249,0.265914,0.451902,0.685198,0.617338,0.712994,0.692362,0.595951,0.255158,0.622179,0.684220,0.542826,0.544408,0.520718,0.285484,0.572105,0.543703,0.369886,0.557769,0.364118,0.496256,0.498945,0.418915,0.577162,0.529107,0.339868,0.196948,0.585428,0.536291,0.483314,0.632269,0.543527,0.778132,0.371988,0.692015,0.522028,0.777244,0.557517,0.732120,0.549469,0.586842,0.535307,0.921529,0.358017,0.597435,0.484183,0.452988,0.446274,0.616718,0.516996,0.365053,0.590899,0.437619,0.587106,0.682375,0.561931,0.575155,0.695336,0.480245,0.679515,0.273757,0.626708,0.338505,0.388299,0.512551,0.570948,0.702795,0.483668,0.570905,0.400010,0.509131,0.504344,0.416243,0.554906,0.527837,0.606684,0.553706,0.525007,0.403944,0.430189,0.391199,0.594626,0.791409,0.665414,0.255390,0.689027,0.625886,0.484497,0.622310,0.456464,0.291317,0.801225,0.378819,0.467992,0.380506,0.771739,0.396672,0.456420,0.498014,0.574887,0.628477,0.499863,0.519470,0.445638,0.572593,0.505771,0.390495,0.610631,0.424412,0.547610,0.485790,0.430888,0.370627,0.359178,0.515370,0.481383,0.556674,0.402762,0.574187,0.546173,0.727809,0.604361,0.473525,0.525606,0.299797,0.398534,0.505861,0.420054,0.470334,0.334076,0.481108,0.522789,0.0,0.0,0.135458,0.135458,0.135458,0.135458,0.135458,0.135458,0.135458,0.463951,0.18750,0.0,0.859581,0.135056,0.998199,0.938709,0.017121,1.0,0.856232,2,0.422307,-0.499941,-0.032834

In [27]:
val_df

,essay_id,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,dense_vec_0,dense_vec_1,dense_vec_2,dense_vec_3,dense_vec_4,dense_vec_5,dense_vec_6,dense_vec_7,dense_vec_8,dense_vec_9,dense_vec_10,dense_vec_11,dense_vec_12,dense_vec_13,dense_vec_14,dense_vec_15,dense_vec_16,dense_vec_17,dense_vec_18,dense_vec_19,dense_vec_20,dense_vec_21,dense_vec_22,dense_vec_23,dense_vec_24,dense_vec_25,dense_vec_26,dense_vec_27,dense_vec_28,dense_vec_29,dense_vec_30,dense_vec_31,dense_vec_32,dense_vec_33,dense_vec_34,dense_vec_35,dense_vec_36,dense_vec_37,dense_vec_38,dense_vec_39,dense_vec_40,dense_vec_41,dense_vec_42,dense_vec_43,dense_vec_44,dense_vec_45,dense_vec_46,dense_vec_47,dense_vec_48,dense_vec_49,dense_vec_50,dense_vec_51,dense_vec_52,dense_vec_53,dense_vec_54,dense_vec_55,dense_vec_56,dense_vec_57,dense_vec_58,dense_vec_59,dense_vec_60,dense_vec_61,dense_vec_62,dense_vec_63,dense_vec_64,dense_vec_65,dense_vec_66,dense_vec_67,dense_vec_68,dense_vec_69,dense_vec_70,dense_vec_71,dense_vec_72,dense_vec_73,dense_vec_74,dense_vec_75,dense_vec_76,dense_vec_77,dense_vec_78,dense_vec_79,dense_vec_80,dense_vec_81,dense_vec_82,dense_vec_83,dense_vec_84,dense_vec_85,dense_vec_86,dense_vec_87,dense_vec_88,dense_vec_89,dense_vec_90,dense_vec_91,dense_vec_92,dense_vec_93,dense_vec_94,dense_vec_95,dense_vec_96,dense_vec_97,dense_vec_98,dense_vec_99,dense_vec_100,dense_vec_101,dense_vec_102,dense_vec_103,dense_vec_104,dense_vec_105,dense_vec_106,dense_vec_107,dense_vec_108,dense_vec_109,dense_vec_110,dense_vec_111,dense_vec_112,dense_vec_113,dense_vec_114,dense_vec_115,dense_vec_116,dense_vec_117,dense_vec_118,dense_vec_119,dense_vec_120,dense_vec_121,dense_vec_122,dense_vec_123,dense_vec_124,dense_vec_125,dense_vec_126,dense_vec_127,dense_vec_128,dense_vec_129,dense_vec_130,dense_vec_131,dense_vec_132,dense_vec_133,dense_vec_134,dense_vec_135,dense_vec_136,dense_vec_137,dense_vec_138,dense_vec_139,dense_vec_140,dense_vec_141,dense_vec_142,dense_vec_143,dense_vec_144,dense_vec_145,dense_vec_146,dense_vec_147,dense_vec_148,dense_vec_149,dense_vec_150,dense_vec_151,dense_vec_152,dense_vec_153,dense_vec_154,dense_vec_155,dense_vec_156,dense_vec_157,dense_vec_158,dense_vec_159,dense_vec_160,dense_vec_161,dense_vec_162,dense_vec_163,dense_vec_164,dense_vec_165,dense_vec_166,dense_vec_167,dense_vec_168,dense_vec_169,dense_vec_170,dense_vec_171,dense_vec_172,dense_vec_173,dense_vec_174,dense_vec_175,dense_vec_176,dense_vec_177,dense_vec_178,dense_vec_179,dense_vec_180,dense_vec_181,dense_vec_182,dense_vec_183,dense_vec_184,dense_vec_185,dense_vec_186,dense_vec_187,dense_vec_188,dense_vec_189,dense_vec_190,dense_vec_191,dense_vec_192,dense_vec_193,dense_vec_194,dense_vec_195,dense_vec_196,dense_vec_197,dense_vec_198,dense_vec_199,dense_vec_200,dense_vec_201,dense_vec_202,dense_vec_203,dense_vec_204,dense_vec_205,dense_vec_206,dense_vec_207,dense_vec_208,dense_vec_209,dense_vec_210,dense_vec_211,dense_vec_212,dense_vec_213,dense_vec_214,dense_vec_215,dense_vec_216,dense_vec_217,dense_vec_218,dense_vec_219,dense_vec_220,dense_vec_221,dense_vec_222,dense_vec_223,dense_vec_224,dense_vec_225,dense_vec_226,dense_vec_227,dense_vec_228,dense_vec_229,dense_vec_230,dense_vec_231,dense_vec_232,dense_vec_233,dense_vec_234,dense_vec_235,dense_vec_236,dense_vec_237,dense_vec_238,dense_vec_239,dense_vec_240,dense_vec_241,dense_vec_242,dense_vec_243,dense_vec_244,dense_vec_245,dense_vec_246,dense_vec_247,dense_vec_248,dense_vec_249,dense_vec_250,dense_vec_251,dense_vec_252,dense_vec_253,dense_vec_254,dense_vec_255,dense_vec_256,dense_vec_257,dense_vec_258,dense_vec_259,dense_vec_260,dense_vec_261,dense_vec_262,dense_vec_263,dense_vec_264,dense_vec_265,dense_vec_266,dense_vec_267,dense_vec_268,dense_vec_269,dense_vec_270,dense_vec_271,dense_vec_272,dense_vec_273,dense_vec_274,dense_vec_275,dense_vec_276,dense_vec_277,dense_vec_278,dense_vec_279,dense_vec_280,dense_vec_281,dense_vec_282,dense_vec_283,dense_vec_284,dense_vec_285,dense_vec_286,dense_vec_287,dense_vec_288,dense_vec_289,dense_vec_290,dense_vec_291,dense_vec_292,dense_vec_293,dense_vec_294,dense_vec_295,dense_vec_296,dense_vec_297,dense_vec_298,dense_vec_299,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,cosine_mean,cosine_std,cosine_max,cosine_min,cluster,PCA_1,PCA_2,PCA_3
0,000d118,3,0.154565,0.789058,0.098066,0.006899,0.001223,0.001459,0.711378,0.551117,0.326117,0.336264,0.710774,0.364280,0.578822,0.379571,0.457979,0.648876,0.285534,0.558463,0.355019,0.654266,0.495664,0.470325,0.409715,0.615382,0.756452,0.403100,0.537424,0.716282,0.695970,0.429585,0.418334,0.428787,0.614345,0.636310,0.546787,0.490667,0.653500,0.595721,0.557840,0.665729,0.348369,0.411600,0.494662,0.467201,0.454330,0.536900,0.562725,0.508077,0.568207,0.351804,0.545880,0.568026,0.676426,0.372630,0.490684,0.660312,0.503175,0.516968,0.528823,0.432086,0.620853,0.359539,0.763993,0.469601,0.579156,0.622973,0.714989,0.361319,0.422084,0.661798,0.539581,0.458394,0.598660,0.408460,0.510949,0.585148,0.333484,0.615131,0.553839,0.719271,0.502848,0.369842,0.478026,0.496551,0.640751,0.479087,0.554923,0.643825,0.635778,0.397104,0.370333,0.629364,0.492684,0.575384,0.470792,0.336784,0.694520,0.519902,0.662934,0.365165,0.519641,0.655347,0.627554,0.542990,0.486240,0.379550,0.451781,0.705297,0.307407,0.520630,0.495432,0.463755,0.588903,0.550946,0.402814,0.475427,0.504532,0.399133,0.424373,0.449743,0.630914,0.452369,0.670403,0.555791,0.351106,0.356418,0.477078,0.407600,0.414297,0.247855,0.458055,0.413466,0.509847,0.416572,0.587543,0.610309,0.663478,0.575384,0.538347,0.488973,0.407385,0.374577,0.562489,0.286808,0.487029,0.619213,0.555182,0.432556,0.605879,0.379051,0.413432,0.399272,0.378021,0.581670,0.670394,0.528490,0.446187,0.577474,0.562332,0.394143,0.561482,0.373599,0.513875,0.500878,0.406292,0.757863,0.459116,0.580376,0.627590,0.454995,0.506800,0.553433,0.468654,0.561349,0.663356,0.515563,0.602143,0.508258,0.238014,0.629515,0.508479,0.353247,0.329944,0.667603,0.658459,0.524670,0.626845,0.439860,0.335709,0.361744,0.414902,0.431034,0.551564,0.313409,0.563817,0.671700,0.579496,0.604919,0.523531,0.450232,0.343733,0.444462,0.610457,0.522604,0.491281,0.489016,0.532801,0.359304,0.504504,0.377115,0.701813,0.532567,0.552361,0.441113,0.624308,0.421560,0.576431,0.492275,0.566174,0.606172,0.623595,0.449664,0.523544,0.546879,0.495172,0.530910,0.520958,0.499264,0.490580,0.553239,0.554193,0.480669,0.334245,0.548350,0.334874,0.511999,0.555136,0.483739,0.506916,0.470833,0.660255,0.627215,0.721365,0.425614,0.607582,0.615082,0.461793,0.540075,0.572118,0.658934,0.397564,0.480767,0.607018,0.482382,0.566342,0.371956,0.489557,0.579181,0.477254,0.634070,0.387123,0.599745,0.493100,0.380814,0.468151,0.569271,0.507716,0.351927,0.433003,0.542226,0.388034,0.350375,0.489800,0.477826,0.448720,0.526307,0.572595,0.382861,0.587715,0.429598,0.486607,0.485467,0.434657,0.461871,0.615702,0.488262,0.365608,0.327218,0.580469,0.644445,0.326978,0.641254,0.532153,0.419789,0.514875,0.497812,0.449780,0.366521,0.612848,0.425603,0.426855,0.397029,0.481815,0.300900,0.556977,0.639090,0.0,0.0,0.243692,0.243692,0.243692,0.243692,0.243692,0.243692,0.243692,0.384216,0.37500,0.0,0.751272,0.245397,0.997048,0.953854,0.016360,1.0,0.877575,1,0.629006,-0.212911,-0.657524
1,001bdc0,4,0.009970,0.263843,0.764289,0.078994,0.002022,0.001141,0.584499,0.439299,0.393709,0.654454,0.618813,0.644629,0.352208,0.788178,0.535807,0.564654,0.547889,0.470423,0.276318,0.694327,0.618309,0.510394,0.671468,0.569657,0.635659,0.246420,0.459376,0.485965,0.431307,0.478768,0.524842,0.414162,0.678759,0.715937,0.504420,0.555860,0.594866,0.756669,0.531515,0.498957,0.382405,0.262512,0.339232,0.370262,0.757566,0.479137,0.789941,0.259445,0.633613,0.361781,0.631067,0.359663,0.347421,0.536317,0.350079,0.380668,0.646069,0.638299,0.295981,0.309640,0.394177,0.211252,0.555802,0.676869,0.422971,0.624033,0.613154,0.357045,0.513200,0.418272,0.246841,0.304975,0.404189,0.451138,0.279480,0.556981,0.259225,0.469866,0.354428,0.662305,0.441950,0.681179,0.346409,0.405344,0.430637,0.357395,0.498105,0.539373,0.596386,0.536435,0.716265,0.336669,0.312706,0.634932,0.421499,0.769075,0.548686,0.384532,0.433154,0.591981,0.270372,0.409540,0.362379,0.503309,0.463330,0.466645,0.767417,0.514070,0.424142,0.743087,0.482680,0.224589,0.408675,0.630087,0.279511,0.360326,0.712857,0.382791,0.532327,0.693062,0.541759,0.590264,0.564250,0.495026,0.625671,0.444977,0.401020,0.529481,0.402783,0.258651,0.429651,0.390681,0.345296,0.566961,0.537928,0.551972,0.365215,0.285221,0.647801,0.276881,0.335699,0.709159,0.327855,0.573117,0.714951,0.556362,0.651679,0.554789,0.348064,0.534582,0.452895,0.705587,0.570986,0.395522,0.656422,0.584776,0.588499,0.490698,0.489702,0.596466,0.445912,0.562342,0.645012,0.665509,0.523895,0.789665,0.589444,0.463732,0.577247,0.446606,0.465572,0.582246,0.392694,0.481616,0.623759,0.507034,0.593079,0.405316,0.492366,0.388207,0.567915,0.601361,0.650238,0.156000,0.348457,0.286801,0.554539,0.481709,0.753262,0.512131,0.676886,0.272533,0.838674,0.404312,0.588425,0.458689,0.477496,0.549166,0.404270,0.596793,0.253452,0.530215,0.655181,0.746009,0.428140,0.513003,0.691298,0.417797,0.413447,0.623926,0.577514,0.522842,0.590666,0.453098,0.463544,0.485261,0.536505,0.247883,0.620231,0.397293,0.404656,0.369318,0.564075,0.510483,0.696130,0.380127,0.680559,0.323835,0.338377,0.424211,0.643586,0.494491,0.402416,0.187394,0.423223,0.745166,0.762783,0.578662,0.437018,0.463791,0.756244,0.506333,0.308307,0.445909,0.403202,0.339942,0.575701,0.475672,0.366416,0.579756,0.386954,0.651562,0.525568,0.686365,0.730702,0.392253,0.443818,0.667690,0.603121,0.480205,0.352331,0.652992,0.612628,0.410958,0.638891,0.640574,0.452941,0.408149,0.525749,0.266541,0.577065,0.296723,0.489582,0.596008,0.490237,0.527502,0.471144,0.760647,0.550088,0.488447,0.437126,0.437230,0.416733,0.366858,0.393370,0.570929,0.567353,0.295226,0.702040,0.347862,0.407579,0.454277,0.610426,0.502547,0.527654,0.606519,0.620194,0.668045,0.606084,0.432566,0.267975,0.646769,0.429630,0.471488,0.359944,0.297225,0.0,0.0,0.205179,0.205179,0.205179,0.205179,0.205179,0.205179,0.205179,0.677222,0.12500,0.0,0.778734,0.209105,0.988692,0.940967,0.021418,1.0,0.858154,2,-1.438064,-0.571355,-0.415590
2,0030e86,4,0.002903,0.144918,0.905791,0.076517,0.001153,0.000443,0.505159,0.343446,0.630703,0.503413,0.484936,0.427307,0.477365,0.475448,0.567510,0.804423,0.560101,0.622611,0.408706,0.432259,0.539504,0.517804,0.390748,0.430929,0.767734,0.634666,0.542515,0.531280,0.690394,0.361314,0.492405,0.256759,0.408084,0.500781,0.467020,0.573553,0.548524,0.795735,0.690864,0.352567,0.308750,0.358335,0.188657,0.250838,0.253811,0.418842,0.523999,0.753805,0.691575,0.492303,0.700845,0.528151,0.622462,0.784988,0.438692,0.376164,0.330200,0.630164,0.373019,0.267666,0.412213,0.617758,0.874718,0.620845,0.378138,0.488473,0.524666,0.589924,0.326510,0.400116,0.433195,0.725258,0.655807,0.376610,0.396599,0.367965,0.721509,0.680933,0.516882,0.472454,0.506812,0.375360,0.405021,0.575190,0.558026,0.616908,0.434097,0.366607,0.628012,0.195884,0.628690,0.755145,0.435484,0.315264,0.572770,0.275422,0.583437,0.586126,0.448306,0.623469,0.592139,0.357254,0.395881,0.593948,0.336996,0.477440,0.503878,0.643134,0.588056,0.389143,0.438077,0.414326,0.491503,0.304552,0.448008,0.666495,0.560764,0.715216,0.149201,0.581782,0.472738,0.584187,0.560666,0.371788,0.377101,0.553019,0.300007,0.627602,0.437571,0.552459,0.347351,0.418071,0.796010,0.565898,0.289915,0.660893,0.422196,0.729589,0.571520,0.346469,0.579859,0.600452,0.597478,0.618270,0.471956,0.659484,0.682557,0.651911,0.529327,0.618310,0.781187,0.457255,0.452221,0.545302,0.605688,0.683036,0.602961,0.509054,0.338099,0.662852,0.684676,0.570674,0.564972,0.514953,0.486326,0.776547,0.464636,0.482126,0.531619,0.368478,0.167617,0.404590,0.439777,0.482883,0.589760,0.586393,0.739358,0.472674,0.560943,0.662629,0.539160,0.282102,0.575314,0.278108,0.782405,0.560020,0.467690,0.455569,0.379872,0.267114,0.666908,0.638457,0.539413,0.352665,0.381300,0.758689,0.359282,0.527507,0.480443,0.558211,0.619108,0.494768,0.148186,0.684753,0.298014,0.448663,0.732284,0.474642,0.391474,0.483098,0.760152,0.536484,0.423199,0.540590,0.475529,0.648052,0.684335,0.568511,0.348669,0.490478,0.649496,0.528922,0.363969,0.442951,0.473213,0.479237,0.226564,0.710626,0.302231,0.624998,0.574724,0.511538,0.620997,0.412060,0.620636,0.473623,0.697625,0.388475,0.537711,0.539067,0.562210,0.406163,0.697519,0.408888,0.406734,0.530301,0.298712,0.335936,0.870804,0.588828,0.477388,0.345017,0.738720,0.675253,0.564772,0.460612,0.611441,0.779759,0.331891,0.587220,0.422071,0.625795,0.283406,0.296662,0.555488,0.451058,0.377505,0.291203,0.443101,0.749247,0.379817,0.415803,0.542771,0.236226,0.678086,0.392393,0.683046,0.528907,0.453349,0.642474,0.653332,0.587427,0.595460,0.694753,0.420211,0.161484,0.557379,0.476051,0.552246,0.570169,0.255026,0.544636,0.461901,0.820923,0.522395,0.579019,0.519896,0.578223,0.709475,0.529749,0.392951,0.450576,0.485425,0.247878,0.549722,0.412589,0.0,0.0,0.175963,0.175963,0.175963,0.175963,0.175963,0.175963,0.175963,0.644790,0.28125,0.0,0.807970,0.180264,0.955767,0.935496,0.017774,1.0,0.863034,0,-0.214054,1.826528,-0.570376
3,0036253,2,0.451102,0.534446,0.054960,0.005387,0.001244,0.001826,0.606732,0.463040,0.415492,0.657886,0.503012,0.840322,0.571887,0.735142,0.544731,0.409075,0.488481,0.354317,0.483107,0.626029,0.588170,0.542653,0.729016,0.400417,0.676666,0.266102,0.475143,0.458918,0.389706,0.425360,0.645618,0.545160,0.734715,0.843234,0.299023,0.765907,0.669898,0.715339,0.484504,0.566061,0.464381,0.414315,0.295394,0.241755,0.516290,0.560607,0.678586,0.358210,0.600375,0.190119,0.480093,0.336100,0.484386,0.532731,0.410911,0.228398,0.570818,0.486802,0.104917,0.381503,0.389791,0.302460,0.562818,0.647121,0.420201,0.627987,0.579701,0.354821,0.468160,0.380038,0.307564,0.199047,0.450918,0.320616,0.212308,0.657935,0.307199,0.377456,0.277561,0.661512,0.391046,0.565871,0.147637,0.370931,0.462848,0.313882,0.576233,0.463057,0.636602,0.502373,0.746233,0.408740,0.319239,0.630262,0.262392,0.671389,0.531199,0.314600,0.465453,0.507727,0.353146,0.481413,0.498939,0.507382,0.492638,0.369240,0.653962,0.260282,0.511224,0.611819,0.576066,0.412236,0.254407,0.768304,0.301202,0.239502,0.406308,0.479983,0.496756,0.640311,0.288648,0.684401,0.187817,0.609296,0.605290,0.701613,0.196701,0.604115,0.558394,0.367667,0.511790,0.393206,0.396612,0.507149,0.695286,0.583561,0.247927,0.217297,0.512785,0.108713,0.215624,0.753978,0.123451,0.552888,0.914566,0.541076,0.685356,0.333372,0.287819,0.476222,0.232731,0.694263,0.729396,0.306517,0.648839,0.684821,0.434293,0.480504,0.550501,0.356109,0.418280,0.617957,0.623078,0.724416,0.553876,0.738584,0.543892,0.632273,0.657094,0.636681,0.518966,0.578034,0.313628,0.758519,0.675637,0.286734,0.577896,0.372854,0.540460,0.442565,0.656015,0.665136,0.720387,0.258597,0.334292,0.427973,0.662758,0.582523,0.670188,0.467808,0.676479,0.561046,0.670204,0.398585,0.536135,0.351281,0.399064,0.512277,0.415596,0.686348,0.250773,0.514213,0.722616,0.745671,0.372381,0.580445,0.659682,0.478169,0.486888,0.682519,0.417783,0.342520,0.711625,0.720048,0.361177,0.434170,0.539620,0.413643,0.689009,0.359443,0.286232,0.268385,0.564678,0.558697,0.642662,0.122701,0.718265,0.361519,0.429947,0.290119,0.607866,0.460115,0.665584,0.121250,0.421080,0.644675,0.628452,0.778423,0.161432,0.425173,0.517708,0.442037,0.278190,0.767773,0.400365,0.359516,0.468782,0.460247,0.342790,0.393868,0.464139,0.806697,0.481169,0.680655,0.777800,0.276784,0.583304,0.695868,0.653678,0.414765,0.165446,0.505664,0.538373,0.537081,0.676566,0.563117,0.494007,0.397640,0.335648,0.241716,0.495403,0.328005,0.589625,0.534581,0.473067,0.359261,0.338386,0.628466,0.575366,0.640842,0.503596,0.424080,0.420872,0.409768,0.479860,0.617701,0.460345,0.365098,0.649928,0.258094,0.551497,0.533363,0.643281,0.561959,0.634582,0.395024,0.683667,0.570312,0.525061,0.352576,0.358379,0.747138,0.446726,0.384808,0.178375,0.418580,0.0,0.0,0.108898,0.108898,0.108898,0.108898,0.108898,0.108898,0.108898,0.664335,0.28125,0.0,0.875083,0.111155,0.995897,0.924964,0.024957,1.0,0.826320,2,-1.757630,-0.568269,-0.553501
4,0065bd6,3,0.013700,0.883724,0.154178,0.001921,0.000076,0.000100,0.610151,0.638180,0.276050,0.565816,0.532929,0.378791,0.635004,0.102664,0.581982,0.662323,0.530125,0.578767,0.304845,0.716566,0.290691,0.303777,0.478323,0.645970,0.826598,0.458982,0.615786,0.447501,0.539052,0.395820,0.572417,0.535363,0.667362,0.618395,0.743450,0.224356,0.444177,0.515865,0.483855,0.666326,0.173521,0.592221,0.650604,0.486616,0.557542,0.555208,0.846592,0.416459,0.542966,0.618154,0.395314,0.596246,0.472928,0.521182,0.521299,0.662118,0.405178,0.352954,0.470894,0.487041,0.484535,0.554965,0.776000,0.382863,0.522943,0.482670,0.554690,0.512465,0.616341,0.591721,0.599581,0.506188,0.620430,0.317653,0.375684,0.656994,0.230182,0.502881,0.715236,0.578013,0.217005,0.338471,0.634074,0.388619,0.471925,0.724930,0.651109,0.419951,0.458604,0.551514,0.315746,0.549867,0.664311,0.371159,0.460377,0.189897,0.470565,0.711339,0.403007,0.360813,0.391021,0.538337,0.528496,0.455454,0.665550,0.557938,0.347212,0.708255,0.626999,0.475994,0.710123,0.374791,0.411090,0.661539,0.273077,0.690383,0.290640,0.700208,0.580647,0.528572,0.568083,0.391320,0.710162,0.334940,0.324532,0.237193,0.310818,0.221638,0.875040,0.228862,0.495543,0.351613,0.393482,0.407369,0.379114,0.527081,0.615281,0.603560,0.433751,0.555249,0.491989,0.347294,0.785303,0.156895,0.334196,0.472492,0.544479,0.402889,0.694016,0.489276,0.517193,0.441050,0.515372,0.382367,0.624061,0.579599,0.425154,0.452695,0.540644,0.722845,0.928790,0.404368,0.425410,0.448989,0.539574,0.786299,0.258798,0.721472,0.578497,0.590478,0.622783,0.388042,0.354163,0.597197,0.454777,0.636583,0.408798,0.435198,0.319131,0.491549,0.576797,0.527381,0.334833,0.526529,0.362203,0.512465,0.606501,0.617879,0.524663,0.398253,0.364617,0.611376,0.524453,0.455783,0.502003,0.628972,0.601393,0.578447,0.483463,0.556522,0.430828,0.385553,0.299944,0.430768,0.607649,0.701722,0.191368,0.476857,0.349065,0.313736,0.452121,0.750761,0.490759,0.571783,0.813751,0.572602,0.544708,0.274089,0.426466,0.697164,0.564047,0.522497,0.342704,0.657718,0.228875,0.447981,0.558148,0.632126,0.515391,0.571056,0.449609,0.429218,0.585798,0.547180,0.337916,0.254175,0.322428,0.585780,0.720248,0.417113,0.463977,0.599037,0.719356,0.487237,0.496555,0.614901,0.681312,0.538387,0.791585,0.603353,0.420848,0.271747,0.708555,0.511439,0.647177,0.622521,0.535768,0.449379,0.474903,0.565812,0.238028,0.356350,0.284026,0.301798,0.702798,0.598619,0.607718,0.470660,0.587226,0.399689,0.359263,0.503586,0.387596,0.650914,0.770420,0.430364,0.831718,0.481099,0.475604,0.730566,0.631351,0.714044,0.386587,0.523660,0.742019,0.438849,0.394661,0.272598,0.710006,0.518706,0.369099,0.555763,0.340772,0.662190,0.674601,0.317540,0.460384,0.437540,0.604095,0.259643,0.494522,0.314350,0.496317,0.339789,0.627540,0.570357,0.0,0.0,0.096282,0.096282,0.096282,0.096282,0.096282,0.096282,0.096282,0.467089,0.12500,0.0,0.893242,0.096519,0.004503,0.936823,0.020973,1.0,0.860668,1,1.223701,-0.206191,-0.073375

In [ ]:
# train_df.to_parquet('train_df.parquet')
# val_df.to_parquet('val_df.parquet')

In [28]:
import pandas as pd
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

df = train_df.copy()
# Downsample majority classes to 1,000 samples
target_samples = 1000
balanced_df = pd.DataFrame()

for class_label in df['score'].unique():
    class_subset = df[df['score'] == class_label]
    
    if len(class_subset) > target_samples:
        # Downsample to 1,000 samples for majority classes
        class_subset = resample(
            class_subset,
            replace=False,
            n_samples=target_samples,
            random_state=42
        )
    
    balanced_df = pd.concat([balanced_df, class_subset], axis=0)

# Now, let's apply SMOTE to balance the minority classes up to 1,000 samples
X = balanced_df.drop(columns = ['essay_id','score'], axis=1)
y = balanced_df['score']

# Create SMOTE instance to ensure all classes have 1,000 samples
smote = SMOTE(sampling_strategy={k: 1000 for k in y.unique()}, random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

# Create the resampled DataFrame
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['score'] = y_resampled

# Display the resampled class distribution to confirm the balancing
print("Resampled class distribution:")
print(df_resampled['score'].value_counts())

Resampled class distribution:
score
3    1000
4    1000
2    1000
1    1000
5    1000
6    1000
Name: count, dtype: int64

/tmp/ipykernel_9511/557032744.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_resampled['score'] = y_resampled

In [29]:
UPSAMPLE = False

if UPSAMPLE:
    
    # Balance only the training DataFrame
    train_df = df_resampled.copy()

    
else:
    pass

print(train_df['score'].value_counts())
print(val_df['score'].value_counts())

score
3    4706
2    3517
4    2988
1     926
5     731
6     112
Name: count, dtype: int64
score
3    1574
2    1206
4     938
1     326
5     239
6      44
Name: count, dtype: int64

In [30]:
# To convert features and targets to NumPy arrays for ML use
train_features = train_df.drop(columns=['essay_id','cosine_max','score'], axis=1).values
train_labels = train_df['score'].values

val_features = val_df.drop(columns=['essay_id','score', 'cosine_max'], axis=1).values
val_labels = val_df['score'].values


print("Features shape:", train_features.shape)
print("Target shape:", train_labels.shape)

print("Features shape:", val_features.shape)
print("Target shape:", val_labels.shape)

Features shape: (12980, 328)
Target shape: (12980,)
Features shape: (4327, 328)
Target shape: (4327,)

In [31]:

def quadratic_weighted_kappa_scorer(y_true, y_pred):
    """
    Compute the Quadratic Weighted Kappa (QWK), also known as Cohen's kappa.
    
    Parameters:
    y_true : array-like of shape (n_samples,)
        True labels.
    y_pred : array-liimport keras_tuner
from sklearn import ensemble
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
from sklearn import model_selection

def build_model(hp):
  model_type = hp.Choice('model_type', ['random_forest', 'ridge'])
  if model_type == 'random_forest':
    model = ensemble.RandomForestClassifier(
        n_estimators=hp.Int('n_estimators', 10, 50, step=10),
        max_depth=hp.Int('max_depth', 3, 10))
  else:
    model = linear_model.RidgeClassifier(
        alpha=hp.Float('alpha', 1e-3, 1, sampling='log'))
  return model

tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=100),
    hypermodel=build_model,
    scoring=metrics.make_scorer(metrics.accuracy_score),
    cv=model_selection.StratifiedKFold(10),
    directory='.',
    project_name='my_project')ke of shape (n_samples,)
        Predicted labels.
    
    Returns:
    score : float
        Quadratic Weighted Kappa score.
    """
    return cohen_kappa_score(y_true, y_pred, weights='quadratic')

In [32]:
# from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
# import keras_tuner as kt

# model_checkpoint = ModelCheckpoint('data/models/best_standard_model_epoch.keras', 
#                                    save_best_only=True, monitor='val_loss', mode='min')

# early_stopping = EarlyStopping(monitor='val_loss', patience=5, 
#                                restore_best_weights=True)

# call_backs = [model_checkpoint, early_stopping]

In [35]:
import keras_tuner
from sklearn import ensemble, linear_model, model_selection, svm
from sklearn.metrics import make_scorer, cohen_kappa_score
from lightgbm import LGBMClassifier


def build_model(hp):
    """
    Builds a more comprehensive machine learning model based on hyperparameters for multiclass classification.
    
    Parameters:
    hp : HyperParameters
        Hyperparameters for tuning the model.
    
    Returns:
    model : An instance of a Scikit-learn model.
    """
    # Adding 'lightgbm' as a new model type
    model_type = hp.Choice('model_type', ['random_forest',  'gradient_boosting', 'lightgbm'])

    if model_type == 'random_forest':
        model = ensemble.RandomForestClassifier(
            n_estimators=hp.Int('n_estimators', 10, 100, step=10),
            max_depth=hp.Int('max_depth', 3, 20),
            min_samples_split=hp.Int('min_samples_split', 2, 20),
            min_samples_leaf=hp.Int('min_samples_leaf', 1, 10),
            criterion=hp.Choice('criterion', ['gini', 'entropy']),
            class_weight=hp.Choice('class_weight', ['balanced', 'balanced_subsample']),
            max_samples=hp.Float('max_samples', 0.1, 1.0, sampling='log')
        )



    elif model_type == 'gradient_boosting':
        model = ensemble.GradientBoostingClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            max_depth=hp.Int('max_depth', 3, 15),
            subsample=hp.Float('subsample', 0.5, 1.0, step=0.1)
        )

    # Adding LightGBM as a new model type
    elif model_type == 'lightgbm':
        model = LGBMClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            num_leaves=hp.Int('num_leaves', 31, 127, step=16),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            min_child_samples=hp.Int('min_child_samples', 10, 50, step=10),
            class_weight=hp.Choice('class_weight', ['balanced', None])
        )

    return model


# Defining the custom QWK scorer
qwk_scorer = make_scorer(quadratic_weighted_kappa_scorer)

# Tuner configuration
tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=15),
    hypermodel=build_model,
    scoring=qwk_scorer,
    cv=model_selection.StratifiedKFold(3),
    directory='.',
    project_name='data/sklearn',
    overwrite=True)

# Starting the search
tuner.search(train_features, train_labels)      # class_weight=class_weights_dict,

# Retrieving the best model
best_model = tuner.get_best_models(num_models=1)[0]

Trial 4 Complete [00h 28m 41s]
score: 0.8341200075965767

Best score So Far: 0.8372792020368247
Total elapsed time: 00h 45m 16s

Search: Running Trial #5

Value             |Best Value So Far |Hyperparameter
gradient_boosting |random_forest     |model_type
90                |30                |n_estimators
3                 |15                |max_depth
4                 |2                 |min_samples_split
10                |4                 |min_samples_leaf
entropy           |entropy           |criterion
balanced          |balanced          |class_weight
0.22651           |0.39405           |max_samples
0.067449          |0.022712          |learning_rate
0.5               |0.7               |subsample

In [ ]:
best_model.fit(train_features, train_labels)

In [ ]:
predictions = best_model.predict(val_features)

y_true = val_labels

# predictions = target_scaler.inverse_transform(predictions.reshape(-1, 1)).flatten()

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix

confusion_matrix(y_true, predictions)

In [ ]:
# classification report

from sklearn.metrics import classification_report

print(classification_report(y_true, predictions))

In [ ]:
# cohens kappa

from sklearn.metrics import cohen_kappa_score

cohen = cohen_kappa_score(y_true, predictions)

In [ ]:
# quadratic weighted kappa

from sklearn.metrics import cohen_kappa_score

quadratic = cohen_kappa_score(y_true, predictions, weights='quadratic')

print(f"Cohen's Kappa: {cohen}")
print(f"Quadratic Weighted Kappa: {quadratic}")

In [ ]:
from joblib import dump, load

dump(best_model, 'standard_random_forest.joblib')

In [ ]:
# forest_model = load('random_forest.joblib')

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Generate and display the confusion matrix for the test predictions
cm = confusion_matrix(y_true, predictions, labels=best_model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()