# sklearn model with tensorflow keras tuner

In [ ]:
# ! python -m pip install --no-index --find-links=/kaggle/usr/lib/pip_install_permanent/my_packages -r /kaggle/usr/lib/pip_install_permanent/requirements.txt

In [ ]:
# import os
# os.environ['PACKAGE_DIR'] = '/kaggle/usr/lib/pip_install_permanent'

In [1]:
import sklearn
print(sklearn.__version__)

1.4.1.post1

In [2]:
from helper_func import *
# # import helper_functions as hf
# import sys
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import string
# from spellchecker import SpellChecker
# from textblob import TextBlob
# from multiprocessing import Pool
# from tqdm import tqdm
# import numpy as np
# import pandas as pd
# # Preprocessing
# from nltk.tokenize import word_tokenize, sent_tokenize
# import operator
# from spellchecker import SpellChecker
# from tqdm import tqdm  # Import tqdm
# import re
# import inflect
# from wordsegment import load, segment
# from nltk.corpus import words
# word_list = set(words.words())
# from spellchecker import SpellChecker

# from tqdm.contrib.concurrent import process_map  # If this import fails, you might need to update tqdm

# import multiprocessing
 
# # Import Packages
# # import shutup; shutup.please()
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import tensorflow as tf
# import keras_tuner as kt
# import seaborn as sns

# from nltk.corpus import stopwords, wordnet
# from nltk.tokenize import word_tokenize, sent_tokenize
# from nltk import pos_tag, ne_chunk
# from textblob import TextBlob

# from textstat import flesch_reading_ease, smog_index

# import spacy
# from collections import Counter
# from gensim import corpora, models
# import pyLDAvis.gensim as gen
# import pyLDAvis
# import re

# # Machine Learning & Data Preprocessing

# from sklearn.preprocessing import StandardScaler, MinMaxScaler
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

# # Deep Learning

# from tensorflow.keras import layers
# from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.sequence import pad_sequences

# # Gensim
# # from gensim.models import Word2Vec, KeyedVectors
# import pandas as pd
# # Progress bar
# from tqdm import tqdm

# # Keras Tuner
# from keras_tuner.tuners import RandomSearch

# # # Setting logging levels and environment variables
# # tf.get_logger().setLevel(logging.ERROR)
# # os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# from textstat import flesch_reading_ease

# # from helper_functions import *
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import string
# from spellchecker import SpellChecker
# from textblob import TextBlob
# from multiprocessing import Pool
# from tqdm import tqdm
# import numpy as np
# import pandas as pd
# # Preprocessing
# from nltk.tokenize import word_tokenize, sent_tokenize
# import operator
# from spellchecker import SpellChecker
# from tqdm import tqdm  # Import tqdm
# import re
# import inflect
# from wordsegment import load, segment
# from nltk.corpus import words
# word_list = set(words.words())
# print('Packages Instaled......')
import sklearn
print(sklearn.__version__)

1.4.1.post1

[nltk_data] Downloading package punkt to /home/laptop/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/laptop/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/laptop/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/laptop/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [3]:
import sklearn
print(sklearn.__version__)

1.4.1.post1

In [4]:
# import pandas as pd

# deberta_train = pd.read_csv('/home/jack/github/kaggle/scoring/deberta_train_predictions.csv')
# deberta_val = pd.read_csv('/home/jack/github/kaggle/scoring/deberta_val_predictions.csv')

In [5]:
# deberta_full = pd.concat([deberta_train, deberta_val])
# deberta_full.head()

In [6]:
pd.set_option('display.max_columns', None)

deberta_full = pd.read_csv('/home/laptop/github/kaggle/scoring/xlnet_hash.csv')
deberta_full.drop(columns=['score', 'labels'], inplace=True)
deberta_full.head()

,essay_id,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199
0,000fe60,i am a scientist at nasa that is discussing th...,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489,0.071429,0.023810,0.023810,0.000000,0.000000,0.119048,0.000000,0.02381,0.000000,0.047619,0.023810,0.023810,0.023810,0.0,0.119048,0.023810,0.02381,0.000000,0.119048,0.023810,0.000000,0.000000,0.000000,0.023810,0.000000,0.0,0.000000,0.023810,0.000000,0.047619,0.000000,0.000000,0.047619,0.071429,0.047619,0.071429,0.000000,0.142857,0.000000,0.000000,0.190476,0.000000,0.000000,0.023810,0.000000,0.190476,0.047619,0.000000,0.000000,0.000000,0.000000,0.095238,0.000000,0.000000,0.000000,0.095238,0.071429,0.047619,0.000000,0.023810,0.023810,0.119048,0.047619,0.000000,0.000000,0.000000,0.0,0.000000,0.023810,0.023810,0.0,0.000000,0.000000,0.023810,0.023810,0.071429,0.047619,0.285714,0.000000,0.000000,0.000000,0.047619,0.000000,0.000000,0.00000,0.023810,0.119048,0.047619,0.023810,0.023810,0.071429,0.214286,0.023810,0.095238,0.000000,0.261905,0.000000,0.047619,0.023810,0.071429,0.000000,0.02381,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.023810,0.071429,0.285714,0.023810,0.000000,0.000000,0.071429,0.000000,0.000000,0.190476,0.023810,0.000000,0.023810,0.000000,0.023810,0.238095,0.000000,0.047619,0.000000,0.000000,0.000000,0.000000,0.071429,0.000000,0.000000,0.000000,0.000000,0.142857,0.0,0.000000,0.023810,0.071429,0.0,0.023810,0.047619,0.000000,0.095238,0.000000,0.0,0.02381,0.000000,0.000000,0.000000,0.047619,0.190476,0.023810,0.142857,0.000000,0.071429,0.214286,0.023810,0.047619,0.000000,0.000000,0.023810,0.000000,0.000000,0.047619,0.0,0.000000,0.047619,0.000000,0.02381,0.00000,0.000000,0.000000,0.071429,0.000000,0.000000,0.02381,0.000000,0.000000,0.071429,0.142857,0.0,0.047619,0.023810,0.047619,0.047619,0.285714,0.095238,0.000000,0.119048,0.000000,0.000000,0.000000,0.023810,0.190476,0.071429,0.000000,0.02381
1,001ab80,people always wish they had the same technolog...,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192,0.014565,0.000000,0.058259,0.000000,0.014565,0.058259,0.189343,0.00000,0.014565,0.029130,0.014565,0.058259,0.000000,0.0,0.029130,0.014565,0.00000,0.014565,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.0,0.000000,0.029130,0.000000,0.160213,0.014565,0.029130,0.000000,0.029130,0.058259,0.043694,0.000000,0.145648,0.014565,0.029130,0.087389,0.029130,0.116519,0.000000,0.014565,0.116519,0.029130,0.000000,0.014565,0.043694,0.014565,0.014565,0.043694,0.029130,0.000000,0.043694,0.000000,0.014565,0.000000,0.000000,0.029130,0.131083,0.058259,0.014565,0.014565,0.000000,0.0,0.000000,0.014565,0.000000,0.0,0.000000,0.014565,0.029130,0.014565,0.072824,0.058259,0.145648,0.043694,0.029130,0.145648,0.000000,0.029130,0.000000,0.02913,0.029130,0.160213,0.029130,0.000000,0.131083,0.043694,0.305861,0.087389,0.087389,0.000000,0.189343,0.000000,0.014565,0.145648,0.014565,0.014565,0.00000,0.0,0.145648,0.000000,0.000000,0.000000,0.0,0.043694,0.000000,0.087389,0.160213,0.000000,0.014565,0.000000,0.029130,0.000000,0.014565,0.072824,0.029130,0.000000,0.029130,0.000000,0.014565,0.043694,0.014565,0.072824,0.029130,0.014565,0.000000,0.014565,0.087389,0.000000,0.101954,0.145648,0.116519,0.116519,0.0,0.014565,0.000000,0.000000,0.0,0.014565,0.014565,0.014565,0.160213,0.014565,0.0,0.00000,0.029130,0.000000,0.014565,0.087389,0.043694,0.000000,0.014565,0.043694,0.029130,0.407815,0.029130,0.000000,0.058259,0.014565,0.072824,0.000000,0.043694,0.029130,0.0,0.014565,0.058259,0.000000,0.00000,0.02913,0.000000,0.000000,0.000000,0.087389,0.014565,0.00000,0.000000,0.029130,0.029130,0.189343,0.0,0.101954,0.043694,0.087389,0.087389,0.189343,0.116519,0.029130,0.043694,0.014565,0.014565,0.000000,0.014565,0.262167,0.014565,0.000000,0.00000
2,002ba53,dear state senator this is a letter to argue i...,0.059430,0.691130,0.233244,0.014120,0.001189,0.000887,0.132971,0.113607,0.266656,0.112359,0.161093,0.213313,0.047637,0.000000,0.079395,0.015879,0.000000,0.000000,0.015879,0.00000,0.000000,0.000000,0.015879,0.079395,0.015879,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063516,0.000000,0.031758,0.0,0.000000,0.015879,0.000000,0.031758,0.031758,0.000000,0.000000,0.000000,0.063516,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.031758,0.031758,0.079395,0.000000,0.206427,0.015879,0.000000,0.000000,0.015879,0.095274,0.095274,0.047637,0.015879,0.015879,0.000000,0.031758,0.015879,0.015879,0.000000,0.111153,0.015879,0.079395,0.000000,0.0,0.000000,0.000000,0.015879,0.0,0.000000,0.015879,0.015879,0.000000,0.047637,0.031758,0.238185,0.015879,0.000000,0.031758,0.000000,0.000000,0.015879,0.00000,0.000000,0.063516,0.285822,0.031758,0.238185,0.063516,0.079395,0.047637,0.031758,0.000000,0.127032,0.142911,0.031758,0.047637,0.127032,0.000000,0.00000,0.0,0.000000,0.031758,0.000000,0.031758,0.0,0.015879,0.000000,0.063516,0.031758,0.015879,0.000000,0.031758,0.000000,0.000000,0.000000,0.127032,0.000000,0.000000,0.000000,0.047637,0.015879,0.015879,0.047637,0.000000,0.000000,0.000000,0.000000,0.015879,0.031758,0.031758,0.000000,0.047637,0.000000,0.031758,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.015879,0.0,0.00000,0.015879,0.063516,0.000000,0.015879,0.015879,0.015879,0.000000,0.015879,0.000000,0.619282,0.000000,0.000000,0.079395,0.015879,0.031758,0.047637,0.000000,0.063516,0.0,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.015879,0.000000,0.015879,0.000000,0.00000,0.031758,0.000000,0.000000,0.031758,0.0,0.015879,0.031758,0.015879,0.063516,0.095274,0.031758,0.000000,0.031758,0.000000,0.000000,0.000000,0.000000,0.381096,0.000000,0.031758,0.00000
3,0033037,the posibilty of a face reconizing computer wo...,0.110127,0.875540,0.012530,0.000799,0.000427,0.000577,0.133904,0.109733,0.257915,0.112806,0.166446,0.219196,0.000000,0.000000,0.000000,0.000000,0.000000,0.039073,0.000000,0.00000,0.000000,0.078146,0.156293,0.117220,0.000000,0.0,0.039073,0.000000,0.00000,0.000000,0.000000,0.000000,0.039073,0.039073,0.000000,0.000000,0.000000,0.0,0.039073,0.000000,0.039073,0.000000,0.000000,0.039073,0.078146,0.000000,0.039073,0.000000,0.039073,0.039073,0.039073,0.039073,0.039073,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.000000,0.000000,0.078146,0.000000,0.039073,0.039073,0.000000,0.000000,0.000000,0.000000,0.078146,0.000000,0.039073,0.000000,0.039073,0.039073,0.000000,0.156293,0.000000,0.0,0.078146,0.000000,0.000000,0.0,0.078146,0.000000,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.039073,0.000000,0.000000,0.000000,0.195366,0.00000,0.039073,0.156293,0.039073,0.000000,0.273513,0.078146,0.117220,0.000000,0.000000,0.000000,0.156293,0.078146,0.000000,0.039073,0.000000,0.039073,0.00000,0.0,0.117220,0.039073,0.000000,0.000000,0.0,0.000000,0.000000,0.117220,0.078146,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.039073,0.000000,0.000000,0.000000,0.039073,0.039073,0.000000,0.156293,0.000000,0.039073,0.000000,0.000000,0.078146,0.078146,0.078146,0.000000,0.156293,0.000000,0.0,0.000000,0.078146,0.156293,0.0,0.000000,0.000000,0.000000,0.039073,0.039073,0.0,0.00000,0.156293,0.000000,0.039073,0.000000,0.000000,0.078146,0.156293,0.000000,0.000000,0.468879,0.078146,0.000000,0.039073,0.039073,0.195366,0.000000,0.000000,0.039073,0.0,0.000000,0.000000,0.039073,0.00000,0.00000,0.000000,0.000000,0.234439,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.117220,0.000000,0.000000,0.156293,0.000000,0.000000,0.039073,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.000000,0.00000
4,0033bf4,what is the seagoing cowboys progam it was to ...,0.004650,0.469768,0.515730,0.009045,0.000419,0.000389,0.133583,0.111408,0.263863,0.108937,0.168764,0.213444,0.000000,0.019364,0.038727,0.019364,0.000000,0.019364,0.019364,0.00000,0.000000,0.116182,0.000000,0.038727,0.000000,0.0,0.038727,0.000000,0.00000,0.038727,0.019364,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.058091,0.000000,0.000000,0.000000,0.038727,0.038727,0.019364,0.019364,0.019364,0.058091,0.000000,0.058091,0.000000,0.019364,0.000000,0.000000,0.213001,0.000000,0.096819,0.000000,0.019364,0.000000,0.000000,0.019364,0.000000,0.000000,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.116182,0.019364,0.000000,0.019364,0.077455,0.0,0.000000,0.116182,0.077455,0.0,0.000000,0.019364,0.000000,0.019364,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.000000,0.038727,0.000000,0.00000,0.000000,0.038727,0.038727,0.000000,0.135546,0.000000,0.251728,0.000000,0.154910,0.038727,0.135546,0.000000,0.000000,0.116182,0.058091,0.000000,0.00000,0.0,0.000000,0.000000,0.019364,0.000000,0.0,0.000000,0.135546,0.077455,0.058091,0.000000,0.077455,0.000000,0.154910,0.019364,0.000000,0.116182,0.058091,0.019364,0.096819,0.000000,0.096819,0.000000,0.000000,0.038727,0.038727,0.038727,0.077455,0.019364,0.000000,0.000000,0.038727,0.019364,0.077455,0.077455,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.116182,0.019364,0.0,0.00000,0.058091,0.000000,0.000000,0.000000,0.058091,0.000000,0.000000,0.000000,0.077455,0.426002,0.058091,0.154910,0.038727,0.000000,0.077455,0.116182,0.019364,0.058091,0.0,0.000000,0.038727,0.000000,0.00000,0.00000,0.019364,0.000000,0.174273,0.019364,0.000000,0.00000,0.019364,0.077455,0.000000,0.019364,0.0,0.213001,0.077455,0.019364,0.038727,0.445365,0.000000,0.019364,0.019364,0.000000,0.019364,0.019364,0.000000,0.096819,0.193637,0.000000,0.00000

In [7]:
# # drop columns with hash in the name

# hash_cols = [col for col in deberta_full.columns if 'hash' in col]

# deberta_full.drop(columns=hash_cols, inplace=True)

# deberta_full.head()

In [8]:
# import pandas as pd
# from sklearn.feature_extraction.text import HashingVectorizer


# # Initialize the HashingVectorizer
# n_features = 500  # Number of columns in the hashed vector
# hashing_vectorizer = HashingVectorizer(n_features=n_features, alternate_sign=False)

# # Transform the text column into hash vector features
# hashed_features = hashing_vectorizer.transform(deberta_full['clean_text'])

# # Convert the hashed features to a dense representation for easier manipulation
# hashed_features_dense = hashed_features.todense()

# # Create new column names based on the number of features
# hashed_columns = [f'hash_{i}' for i in range(n_features)]

# # Convert dense representation to a dataframe
# hashed_df = pd.DataFrame(hashed_features_dense, columns=hashed_columns)

# # Concatenate the original dataframe with the hashed dataframe

# deberta_full = pd.concat([deberta_full, hashed_df], axis=1)

In [9]:
# deberta_full.tail()

In [10]:
# deberta_full = deberta_full.merge(xlnet, on='essay_id', how='left')
# deberta_full.head()deberta_full.drop(columns=['score', 'labels'], inplace=True)

In [11]:
# deberta_full.tail()

In [12]:
# deberta_full.drop(columns=[ 'score'], inplace=True)

In [13]:
train = pd.read_csv('/home/laptop/github/kaggle/scoring/data/train.csv')

In [14]:
print(deberta_full.shape, train.shape)

(17307, 214) (17307, 3)

In [15]:
# Combine train and deberta_full on essay_id

train = train.merge(deberta_full, on='essay_id')

In [16]:
train.head()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199
0,000d118,Many people have car where they live. The thin...,3,many people have car where they live the thing...,0.156896,0.756281,0.079829,0.005163,0.000922,0.000909,0.116983,0.173203,0.157604,0.287849,0.154709,0.109652,0.031439,0.00000,0.047158,0.031439,0.015719,0.015719,0.220070,0.015719,0.031439,0.047158,0.000000,0.078597,0.015719,0.0,0.031439,0.000000,0.000000,0.031439,0.015719,0.000000,0.078597,0.000000,0.015719,0.015719,0.000000,0.00000,0.000000,0.031439,0.015719,0.204351,0.000000,0.015719,0.015719,0.015719,0.062877,0.000000,0.00000,0.094316,0.062877,0.015719,0.078597,0.047158,0.015719,0.000000,0.000000,0.204351,0.047158,0.062877,0.031439,0.031439,0.000000,0.015719,0.078597,0.015719,0.015719,0.015719,0.000000,0.078597,0.000000,0.047158,0.031439,0.047158,0.062877,0.000000,0.000000,0.015719,0.031439,0.0,0.015719,0.015719,0.062877,0.00000,0.047158,0.015719,0.000000,0.047158,0.015719,0.125754,0.000000,0.000000,0.015719,0.015719,0.015719,0.015719,0.078597,0.047158,0.047158,0.015719,0.015719,0.251509,0.000000,0.314386,0.000000,0.141474,0.0,0.345825,0.015719,0.015719,0.015719,0.031439,0.031439,0.00000,0.0,0.015719,0.000000,0.0,0.000000,0.000000,0.000000,0.031439,0.172912,0.125754,0.015719,0.000000,0.000000,0.000000,0.0,0.000000,0.062877,0.031439,0.015719,0.062877,0.110035,0.000000,0.031439,0.000000,0.047158,0.000000,0.000000,0.157193,0.015719,0.078597,0.031439,0.015719,0.000000,0.031439,0.157193,0.047158,0.015719,0.047158,0.078597,0.000000,0.000000,0.000000,0.015719,0.062877,0.000000,0.000000,0.00000,0.000000,0.000000,0.031439,0.062877,0.015719,0.015719,0.000000,0.015719,0.015719,0.330105,0.015719,0.015719,0.031439,0.000000,0.062877,0.015719,0.015719,0.062877,0.0,0.015719,0.000000,0.031439,0.031439,0.015719,0.00000,0.031439,0.000000,0.015719,0.015719,0.047158,0.031439,0.00000,0.047158,0.094316,0.0,0.094316,0.015719,0.031439,0.141474,0.204351,0.000000,0.00000,0.094316,0.015719,0.031439,0.015719,0.015719,0.267228,0.031439,0.000000,0.015719
1,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489,0.071429,0.02381,0.023810,0.000000,0.000000,0.119048,0.000000,0.023810,0.000000,0.047619,0.023810,0.023810,0.023810,0.0,0.119048,0.023810,0.023810,0.000000,0.119048,0.023810,0.000000,0.000000,0.000000,0.023810,0.000000,0.00000,0.000000,0.023810,0.000000,0.047619,0.000000,0.000000,0.047619,0.071429,0.047619,0.071429,0.00000,0.142857,0.000000,0.000000,0.190476,0.000000,0.000000,0.023810,0.000000,0.190476,0.047619,0.000000,0.000000,0.000000,0.000000,0.095238,0.000000,0.000000,0.000000,0.095238,0.071429,0.047619,0.000000,0.023810,0.023810,0.119048,0.047619,0.000000,0.000000,0.000000,0.000000,0.0,0.023810,0.023810,0.000000,0.00000,0.000000,0.023810,0.023810,0.071429,0.047619,0.285714,0.000000,0.000000,0.000000,0.047619,0.000000,0.000000,0.000000,0.023810,0.119048,0.047619,0.023810,0.023810,0.071429,0.214286,0.023810,0.095238,0.0,0.261905,0.000000,0.047619,0.023810,0.071429,0.000000,0.02381,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.023810,0.071429,0.285714,0.023810,0.000000,0.000000,0.071429,0.0,0.000000,0.190476,0.023810,0.000000,0.023810,0.000000,0.023810,0.238095,0.000000,0.047619,0.000000,0.000000,0.000000,0.000000,0.071429,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.023810,0.071429,0.000000,0.023810,0.047619,0.000000,0.095238,0.000000,0.000000,0.02381,0.000000,0.000000,0.000000,0.047619,0.190476,0.023810,0.142857,0.000000,0.071429,0.214286,0.023810,0.047619,0.000000,0.000000,0.023810,0.000000,0.000000,0.047619,0.0,0.000000,0.047619,0.000000,0.023810,0.000000,0.00000,0.000000,0.071429,0.000000,0.000000,0.023810,0.000000,0.00000,0.071429,0.142857,0.0,0.047619,0.023810,0.047619,0.047619,0.285714,0.095238,0.00000,0.119048,0.000000,0.000000,0.000000,0.023810,0.190476,0.071429,0.000000,0.023810
2,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192,0.014565,0.00000,0.058259,0.000000,0.014565,0.058259,0.189343,0.000000,0.014565,0.029130,0.014565,0.058259,0.000000,0.0,0.029130,0.014565,0.000000,0.014565,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.00000,0.000000,0.029130,0.000000,0.160213,0.014565,0.029130,0.000000,0.029130,0.058259,0.043694,0.00000,0.145648,0.014565,0.029130,0.087389,0.029130,0.116519,0.000000,0.014565,0.116519,0.029130,0.000000,0.014565,0.043694,0.014565,0.014565,0.043694,0.029130,0.000000,0.043694,0.000000,0.014565,0.000000,0.000000,0.029130,0.131083,0.058259,0.014565,0.014565,0.000000,0.000000,0.0,0.014565,0.000000,0.000000,0.00000,0.014565,0.029130,0.014565,0.072824,0.058259,0.145648,0.043694,0.029130,0.145648,0.000000,0.029130,0.000000,0.029130,0.029130,0.160213,0.029130,0.000000,0.131083,0.043694,0.305861,0.087389,0.087389,0.0,0.189343,0.000000,0.014565,0.145648,0.014565,0.014565,0.00000,0.0,0.145648,0.000000,0.0,0.000000,0.000000,0.043694,0.000000,0.087389,0.160213,0.000000,0.014565,0.000000,0.029130,0.0,0.014565,0.072824,0.029130,0.000000,0.029130,0.000000,0.014565,0.043694,0.014565,0.072824,0.029130,0.014565,0.000000,0.014565,0.087389,0.000000,0.101954,0.145648,0.116519,0.116519,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.014565,0.160213,0.014565,0.000000,0.00000,0.029130,0.000000,0.014565,0.087389,0.043694,0.000000,0.014565,0.043694,0.029130,0.407815,0.029130,0.000000,0.058259,0.014565,0.072824,0.000000,0.043694,0.029130,0.0,0.014565,0.058259,0.000000,0.000000,0.029130,0.00000,0.000000,0.000000,0.087389,0.014565,0.000000,0.000000,0.02913,0.029130,0.189343,0.0,0.101954,0.043694,0.087389,0.087389,0.189343,0.116519,0.02913,0.043694,0.014565,0.014565,0.000000,0.014565,0.262167,0.014565,0.000000,0.000000
3,001bdc0,"We all heard about Venus, the planet without a...",4,we all heard about venus the planet without al...,0.009681,0.273882,0.657448,0.056872,0.001404,0.000713,0.118487,0.169333,0.149879,0.299778,0.153946,0.108576,0.000000,0.00000,0.000000,0.000000,0.000000,0.017090,0.000000,0.000000,0.017090,0.034179,0.000000,0.187986,0.000000,0.0,0.051269,0.000000,0.034179,0.034179,0.034179,0.017090,0.051269,0.034179,0.017090,0.017090,0.034179,0.01709,0.051269,0.017090,0.017090,0.051269,0.000000,0.034179,0.085448,0.051269,0.068359,0.000000,0.01709,0.034179,0.017090,0.017090,0.068359,0.000000,0.000000,0.000000,0.017090,0.222165,0.034179,0.017090,0.017090,0.034179,0.000000,0.034179,0.017090,0.000000,0.034179,0.119628,0.068359,0.085448,0.034179,0.017090,0.017090,0.017090,0.205076,0.017090,0.000000,0.017090,0.068359,0.0,0.017090,0.000000,0.051269,0.01709,0.034179,0.017090,0.000000,0.068359,0.102538,0.136717,0.000000,0.034179,0.051269,0.000000,0.068359,0.000000,0.000000,0.034179,0.290524,0.051269,0.034179,0.068359,0.068359,0.273434,0.000000,0.051269,0.0,0.187986,0.085448,0.000000,0.034179,0.068359,0.000000,0.00000,0.0,0.034179,0.017090,0.0,0.000000,0.051269,0.000000,0.000000,0.068359,0.068359,0.017090,0.000000,0.017090,0.153807,0.0,0.000000,0.068359,0.000000,0.000000,0.017090,0.051269,0.000000,0.000000,0.068359,0.000000,0.068359,0.017090,0.000000,0.000000,0.017090,0.034179,0.034179,0.017090,0.017090,0.034179,0.000000,0.017090,0.153807,0.000000,0.034179,0.068359,0.034179,0.000000,0.000000,0.034179,0.051269,0.01709,0.017090,0.017090,0.000000,0.000000,0.051269,0.017090,0.017090,0.017090,0.051269,0.529779,0.017090,0.017090,0.051269,0.017090,0.034179,0.000000,0.000000,0.034179,0.0,0.000000,0.017090,0.000000,0.034179,0.000000,0.01709,0.000000,0.102538,0.000000,0.017090,0.017090,0.000000,0.00000,0.034179,0.102538,0.0,0.085448,0.034179,0.000000,0.051269,0.085448,0.017090,0.00000,0.119628,0.017090,0.017090,0.034179,0.000000,0.256345,0.068359,0.051269,0.000000
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,dear state senator this is a letter to argue i...,0.059430,0.691130,0.233244,0.014120,0.001189,0.000887,0.132971,0.113607,0.266656,0.112359,0.161093,0.213313,0.047637,0.00000,0.079395,0.015879,0.000000,0.000000,0.015879,0.000000,0.000000,0.000000,0.015879,0.079395,0.015879,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063516,0.000000,0.031758,0.00000,0.000000,0.015879,0.000000,0.031758,0.031758,0.000000,0.000000,0.000000,0.063516,0.015879,0.00000,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.031758,0.031758,0.079395,0.000000,0.206427,0.015879,0.000000,0.000000,0.015879,0.095274,0.095274,0.047637,0.015879,0.015879,0.000000,0.031758,0.015879,0.015879,0.000000,0.111153,0.015879,0.079395,0.000000,0.000000,0.0,0.000000,0.015879,0.000000,0.00000,0.015879,0.015879,0.000000,0.047637,0.031758,0.238185,0.015879,0.000000,0.031758,0.000000,0.000000,0.015879,0.000000,0.000000,0.063516,0.285822,0.031758,0.238185,0.063516,0.079395,0.047637,0.031758,0.0,0.127032,0.142911,0.031758,0.047637,0.127032,0.000000,0.00000,0.0,0.000000,0.031758,0.0,0.031758,0.000000,0.015879,0.000000,0.063516,0.031758,0.015879,0.000000,0.031758,0.000000,0.0,0.000000,0.127032,0.000000,0.000000,0.000000,0.047637,0.015879,0.015879,0.047637,0.000000,0.000000,0.000000,0.000000,0.015879,0.031758,0.031758,0.000000,0.047637,0.000000,0.031758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015879,0.000000,0.00000,0.015879,0.063516,0.000000,0.015879,0.015879,0.015879,0.000000,0.015879,0.000000,0.619282,0.000000,0.000000,0.079395,0.015879,0.031758,0.047637,0.000000,0.063516,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.015879,0.000000,0.015879,0.000000,0.000000,0.031758,0.00000,0.000000,0.031758,0.0,0.015879,0.031758,0.015879,0.063516,0.095274,0.031758,0.00000,0.031758,0.000000,0.000000,0.000000,0.000000,0.381096,0.000000,0.031758,0.000000

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
import pandas as pd
import pickle
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import re

# Custom Preprocessing
def custom_preprocessing(text):
    # Lowercasing
    text = text.lower()
    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)
    # Tokenization
    tokens = word_tokenize(text)
    # Remove stop words
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    # Stemming
    ps = PorterStemmer()
    tokens = [ps.stem(word) for word in tokens]
    # Join tokens back into text
    return ' '.join(tokens)

# Initialize a TfidfVectorizer with n-gram range from 1 to 3 (unigrams to trigrams)
vectorizer = TfidfVectorizer(ngram_range=(1, 3), preprocessor=custom_preprocessing, max_features=750)

# Assuming 'essay' column contains the text data
X_ngrams = vectorizer.fit_transform(train['full_text'])

# Convert the matrix to a DataFrame
df_ngrams = pd.DataFrame(X_ngrams.toarray(), columns=vectorizer.get_feature_names_out())

# Use TruncatedSVD for dimensionality reduction
svd = TruncatedSVD(n_components=100)
X_svd = svd.fit_transform(X_ngrams)

# Convert the matrix to a DataFrame
df_svd = pd.DataFrame(X_svd, columns=[f'svd_{i}' for i in range(100)])

# Concatenate n-gram features with SVD features
df = pd.concat([train.reset_index(drop=True), df_svd.reset_index(drop=True)], axis=1)
df.tail()

# Serialize and save the PCA model and vectorizer
with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

In [18]:
df_ngrams.head()

,1976,2000,2001,25,3d,800,800 degre,90,90 time,97,abl,accid,accord,acid,action,action code,action code system,actual,ad,addit,advanc,advantag,ago,agre,air,air pollut,alert,alien,allow,almost,along,alot,alreadi,also,also help,although,alway,amaz,america,american,amount,angri,anim,anoth,anoth reason,answer,anyon,anyth,appear,april,area,arent,argu,argument,around,around world,articl,ask,assist,atmospher,attent,author,author state,author support,averag,avoid,awar,away,back,bad,ban,base,basic,becom,becom confus,becuas,begin,behind,believ,benefit,best,better,big,bike,blame,boat,bogota,bore,brake,break,bring,build,butt,buy,calcul,call,came,camera,campaign,candid,canid,cant,car,car car,car come,car could,car drive,car usag,car use,car would,carbon,carbon dioxid,care,carfre,case,caus,certain,challeng,challeng explor,challeng explor venu,chanc,chang,china,choos,citi,citizen,claim,class,classroom,classroom comput,clear,close,closer,closest,cloud,code,code system,colleg,come,common,commun,compani,compar,complet,comput,comput could,conclus,condit,confus,confus bore,congress,consid,continu,control,cool,cost,could,could also,could help,count,countri,cover,cowboy,cowboy program,crash,creat,creat alien,cut,cydonia,danger,danger present,day,deal,dear,decid,decreas,degre,degre fahrenheit,depend,despit,despit danger,detail,detect,develop,devic,didnt,differ,dioxid,discov,distanc,doesnt,done,dont,dont know,dont think,doubt,dr,dr huang,drive,drive car,driveless,driveless car,driven,driver,driverless,driverless car,driverless car would,due,earth,easi,easier,educ,effect,either,elect,elect presid,elector,elector colleg,elector vote,electron,els,emiss,emot,emot express,end,enjoy,enough,environ,equal,europ,even,even though,ever,everi,everyday,everyon,everyth,evid,exampl,expens,experi,explain,explor,explor venu,express,extrem,eye,fac,face,face mar,facial,facial action,facial action code,facial express,fact,factor,fahrenheit,fail,fair,famili,far,fault,fear,featur,feel,feel like,figur,final,find,fine,first,fix,focu,follow,food,form,form life,format,found,franc,free,friend,fuel,fun,futur,ga,gain,game,gener,germani,get,give,given,global,go,goe,good,good idea,good thing,googl,got,govern,great,greater,greenhous,greenhous ga,ground,half,hand,handl,happen,happi,happier,hard,harm,head,heat,help,help peopl,help student,help us,hide,high,highli,hit,hold,home,hope,hot,hour,hous,hover,howev,huang,huge,human,human driver,hurt,idea,identifi,im,imag,imagin,import,improv,includ,increas,individu,inform,innov,instead,interest,invent,isnt,issu,jam,job,join,join seago,join seago cowboy,keep,kid,kind,know,known,land,landform,larg,last,lastli,law,lead,learn,leav,left,less,lesson,let,level,licens,lie,life,life mar,light,like,like earth,like face,limit,limit car,limit car usag,lisa,littl,live,long,look,look like,lose,lot,love,lower,luke,machin,made,main,major,make,make sure,mani,mani peopl,mani thing,manufactur,mar,martian,matter,may,mayb,mean,meet,mention,mesa,method,might,mile,million,mind,mission,model,modifi,modifi lesson,mona,mona lisa,money,mountain,mouth,move,movement,much,muscl,must,nasa,nation,natur,natur landform,near,need,neg,never,new,new technolog,next,night,normal,noth,number,object,occur,ocean,often,old,one,one day,open,opinion,opportun,option,order,other,overal,paint,paragraph,pari,park,part,parti,pass,passag,passeng,past,pay,pay attent,peopl,peopl dont,peopl think,peopl vote,peopl want,peopl would,percent,person,phone,photo,pick,pictur,place,plan,planet,planet earth,planet solar,planet solar system,planet venu,plant,play,point,pollut,popul,popular,popular vote,posit,possibl,power,present,presid,presidenti,pressur,pretti,prevent,probabl,problem,process,produc,program,prove,provid,public,public transport,pursuit,pursuit despit,pursuit despit danger,put,question,quot,rather,read,read emot,reader,readi,real,realli,reason,recogn,recogn student,reduc,repres,requir,research,respons,result,ride,right,risk,road,rock,run,sad,safe,safer,safeti,said,save,say,school,scientist,sea,seago,seago cowboy,seago cowboy program,second,see,seem,seen,select,self,senat,send,sens,sensor,sent,set,shadow,ship,shouldnt,show,side,sign,similar,simpl,simpli,sinc,singl,situat,size,skill,slate,small,smart,smart car,smile,smog,societi,softwar,solar,solar system,solut,someon,someth,sometim,soon,sound,sourc,space,spacecraft,speed,spend,star,start,state,stay,still,stop,store,stori,street,stress,student,student becom,student becom confus,student classroom,studi,studi venu,studi venu worthi,stuff,suggest,sun,support,support idea,sure,surfac,surfac temperatur,surviv,system,take,take away,take care,taken,talk,taxi,teach,teacher,technolog,technolog read,tell,temperatur,test,text,that,there,therefor,theyr,thing,think,think would,though,thought,three,tie,time,time greater,today,took,toward,traffic,transport,travel,tri,trip,true,trust,turn,twin,two,type,understand,unfair,unit,unit state,us,usag,use,use car,use technolog,valu,valuabl,variou,vauban,vehicl,venu,venu author,venu worthi,venu worthi pursuit,venu would,venuss,video,vike,visit,vote,vote elector,vote presid,voter,wait,walk,want,war,wasnt,wast,watch,water,way,weather,week,well,went,what,wheel,whether,whole,win,winner,without,without car,wonder,wont,work,world,world war,worri,worth,worthi,worthi pursuit,worthi pursuit despit,would,would abl,would help,would like,would make,wouldnt,wrong,ye,year,yet,young,your
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.000000,0.0,0.000000,0.000000,0.055916,0.155229,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.043435,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.03502,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.104764,0.0,0.083375,0.0,0.0,0.000000,0.0,0.0,0.000000,0.544080,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.035572,0.0,0.0,0.048721,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.104470,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.047981,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.091139,0.059163,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.037020,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.051189,0.116746,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.052246,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.038881,0.000000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.054348,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.057682,0.0,0.0,0.000000,0.000000,0.094868,0.0,0.0,0.0,0.0,0.023406,0.000000,0.0,0.0,0.075931,0.0,0.151056,0.110097,0.05938,0.0,0.0,0.0,0.0,0.0,0.120065,0.127836,0.000000,0.0,0.0,0.0,0.037232,0.0,0.0,0.000000,0.0,0.0,0.000000,0.028013,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.09933,0.000000,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.066537,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.027599,0.0,0.000000,0.000000,0.049850,0.000000,0.0,0.051977,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.032664,0.000000,0.0,0.020559,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.075564,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.023719,0.0,0.050787,0.046312,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.048845,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.050357,0.0,0.032288,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.059431,0.084551,0.000000,0.000000,0.031480,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.023861,0.0,0.0,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.0,0.058917,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.103523,0.0,0.0,0.0,0.0,0.0,0.250065,0.0,0.0,0.0,0.0,0.000000,0.142588,0.056738,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.050626,0.0,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.033776,0.030698,0.000000,0.0,0.051101,0.0,0.0,0.0,0.054627,0.0,0.053576,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.116236,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.058342,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.041990,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.056431,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.039648,0.000000,0.00000,0.0,0.0,0.0,0.098859,0.0,0.0,0.0,0.0,0.043228,0.083528,0.000000,0.000000,0.000000,0.0,0.0,0.105836,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.0000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.00000,0.0,0.084692,0.000000,0.0,0.0,0.105348,0.077619,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.148030,0.000000,0.000000,0.0,0.054998,0.000000,0.000000,0.0,0.04454,0.000000,0.0,0.0,0.088919,0.095915,0.000000,0.0,0.104198,0.166563,0.0,0.0,0.0,0.0,0.359985,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.203523,0.000000,0.055902,0.0,0.000000,0.0,0.0,0.025656,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.050192,0.000000,0.032294,0.060974,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.07506,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.081077,0.0,0.000000,0.000000,0.0,0.064993,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.054072,0.0,0.0,0.0,0.0,0.000000,0.0,0.040758,0.0,0.000000,0.0,0.0,0.000000,0.05765,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.052978,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.076282,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.055769,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.073163,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.073504,0.000000,0.142787,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.089569,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.050893,0.0,0.051105,0.0,0.000000,0.000000,0.000000,0.0,0.1178,0.0,0.0,0.0,0.0,0.0,0.0,0.252082,0.123152,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.057988,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.043972,0.0,0.0,0.0,0.0,0.04911,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.028315,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.067828,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.055731,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.066776,0.0,0.057567,0.604468,0.000000,0.053996,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.079031,0.080117,0.0,0.099487,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.085262,0.126007,0.000000,0.000000,0.0,0.0,0.0,0.0,0.042258,0.0,0.0,0.028694,0.0,0.061439,0.000000,0.0,0.000000,0.265935,0.358668,0.0,0.000000,0.0,0.046115,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.244111,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.056162,0.000000,0.000000,0.057328,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.115462,0.0,0.0,0.0,0.0,0.000000,0.0,0.05649,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.025047,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.056188,0.000000,0.000000,0.044486,0.000000,0.0,0.0,0.0,0.078966,0.000000,0.0,0.0,0.000000,0.000000,0.00000,0.000000,0.049361,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.131141,0.0,0.052343,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.050797,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.041198,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.07577,0.0,0.0,0.0000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.032946,0.0,0.0,0.0,0.052679,0.0,0.0,0.0,0.00000,0.0,0.045435,0.000000,0.00000,0.0,0.000000,0.000000,0.0,0.0,0.063722,0.062600,0.074478,0.00000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.043924,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.062842,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.061785,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.143564,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.073305,0.0,0.0,0.068217,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.000000,0.028354,0.143742,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0000,0.0,0.043926,0.0,0.000000,0.000000,0.000000,0.000000,0.040028,0.036733,0.0,0.040062,0.033458,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.044801,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.055398,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.0,0.000000,0.000000,0.049751,0.0,0.0,0.000000,0.0,0.0,0.0,0.063785,0.0,0.0,0.0,0.0,0.0,0.0,0.037903,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.043065,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.578872,0.049283,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.086079,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.040055,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.02847,0.0,0.0,0.0,0.0,0.085889,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.038296,0.0,0.047497,0.056850,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.044056,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.039447,0.0,0.0,0.000000,0.000000,0.050488,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.222229,0.041792,0.0,0.0,0.0,0.032366,0.201897,0.135279,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.037824,0.0,0.0,0.0,0.0,0.000000,0.120416,0.0,0.0,0.000000,0.0,0.034731,0.0,0.000000,0.000000,0.050114,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.048252,0.000000,0.0,0.030039,0.051054,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.118926,0.000000,0.000000,0.0,0.0,0.0,0.0,0.096214,0.000000,0.0,0.0,0.041617,0.0,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.030610,0.0,0.0,0.039066,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.00000,0.042124,0.0,0.0,0.0,0.00000,0.080951,0.0,0.0,0.023048,0.0,0.0,0.136756,0.0,0.0,0.0,0.000000,0.0,0.083212,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.086322,0.022690,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.085465,0.0,0.0,0.0,0.0,0.034478,0.0,0.036101,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.033806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.034328,0.000000,0.000000,0.000000,0.030651,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.039000,0.0,0.125261,0.000000,0.0,0.178884,0.000000,0.000000,0.0,0.135857,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.075299,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.048860,0.046342,0.048559,0.000000,0.258807,0.091985,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.039234,0.0,0.0,0.0,0.0,0.144914,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.047435,0.0,0.0,0.0,0.038594,0.0,0.051066,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.041621,0.0,0.0,0.000000,0.039319,0.00000,0.043074,0.033545,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.065371,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.087685,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.033605,0.042632,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.148078,0.045237,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.103564,0.0,0.043805,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.097789,0.027998,0.03804,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.035539,0.045781,0.000000,0.027570,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.0000,0.000000,0.0,0.000000,0.000000,0.0,0.053149,0.022390,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.26992,0.0,0.000000,0.000000,0.03982,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.021271,0.000000,0.03435,0.0,0.0,0.0,0.020028,0.0,0.0,0.0,0.0,0.039577,0.081134,0.000000,0.089552,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.042707,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.049058,0.000000,0.0,0.050792,0.0,0.0,0.042186,0.000000,0.0,0.028523,0.0,0.0,0.0,0.049706,0.041989,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.024391,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0

In [19]:
import spacy

# Load a spaCy model

nlp = spacy.load("en_core_web_sm")

# Function to count POS tags and return a dictionary
def pos_counts(text):
    doc = nlp(text)
    pos_counts = doc.count_by(spacy.attrs.POS)
    return {doc.vocab.strings[pos_id]: count for pos_id, count in pos_counts.items()}

# Create a DataFrame with POS counts for each document
df_pos = df['full_text'].apply(pos_counts).apply(pd.Series).fillna(0)
df_pos.columns = [f'pos_{col}' for col in df_pos.columns]

# Concatenate POS feature DataFrame back to the original DataFrame
# df = pd.concat([df, df_pos], axis=1)

In [20]:
df_pos.head()

,pos_ADJ,pos_NOUN,pos_VERB,pos_SCONJ,pos_PRON,pos_PUNCT,pos_DET,pos_AUX,pos_PART,pos_ADP,pos_SPACE,pos_CCONJ,pos_PROPN,pos_NUM,pos_ADV,pos_SYM,pos_INTJ,pos_X
0,33.0,106.0,66.0,31.0,53.0,31.0,41.0,37.0,20.0,55.0,6.0,19.0,26.0,12.0,15.0,1.0,0.0,0.0
1,12.0,51.0,44.0,17.0,53.0,35.0,34.0,38.0,11.0,35.0,4.0,10.0,10.0,2.0,20.0,0.0,1.0,0.0
2,43.0,115.0,69.0,20.0,49.0,52.0,60.0,54.0,30.0,54.0,4.0,15.0,0.0,2.0,44.0,0.0,0.0,0.0
3,31.0,113.0,57.0,14.0,33.0,54.0,48.0,22.0,14.0,57.0,4.0,21.0,21.0,6.0,19.0,0.0,0.0,2.0
4,33.0,76.0,35.0,9.0,23.0,37.0,62.0,26.0,11.0,54.0,7.0,9.0,31.0,4.0,9.0,0.0,0.0,2.0

In [21]:
# Extract named entities and count by types
def named_entities(text):
    doc = nlp(text)
    entities = {}
    for ent in doc.ents:
        entities[ent.label_] = entities.get(ent.label_, 0) + 1
    return entities

# Create a DataFrame with named entity counts
df_entities = df['full_text'].apply(named_entities).apply(pd.Series).fillna(0)
df_entities.columns = [f'ner_{col}' for col in df_entities.columns]

# Concatenate entity feature DataFrame back to the original DataFrame
# df = pd.concat([df, df_entities], axis=1)

In [22]:
df_entities.head()

,ner_GPE,ner_PERCENT,ner_NORP,ner_ORG,ner_CARDINAL,ner_MONEY,ner_DATE,ner_LOC,ner_PERSON,ner_QUANTITY,ner_EVENT,ner_ORDINAL,ner_WORK_OF_ART,ner_LAW,ner_PRODUCT,ner_TIME,ner_FAC,ner_LANGUAGE
0,4.0,5.0,2.0,3.0,2.0,1.0,3.0,2.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,0.0,1.0,5.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,3.0,2.0,2.0,0.0,0.0,15.0,1.0,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,2.0,14.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0

In [23]:
def dependency_tags(text):
    doc = nlp(text)
    dep_counts = doc.count_by(spacy.attrs.DEP)
    return {doc.vocab.strings[dep_id]: count for dep_id, count in dep_counts.items()}

df_deps = df['full_text'].apply(dependency_tags).apply(pd.Series).fillna(0)

df_deps.columns = [f'dep_{col}' for col in df_deps.columns]

# df = pd.concat([df, df_deps], axis=1)

In [24]:
df_deps.head()

,dep_amod,dep_nsubj,dep_ROOT,dep_dobj,dep_advmod,dep_relcl,dep_punct,dep_det,dep_aux,dep_neg,dep_mark,dep_csubj,dep_compound,dep_prep,dep_pobj,dep_ccomp,dep_dep,dep_advcl,dep_cc,dep_acomp,dep_attr,dep_appos,dep_conj,dep_nummod,dep_poss,dep_case,dep_nsubjpass,dep_nmod,dep_auxpass,dep_npadvmod,dep_expl,dep_xcomp,dep_dative,dep_oprd,dep_acl,dep_quantmod,dep_pcomp,dep_agent,dep_intj,dep_predet,dep_prt,dep_meta,dep_preconj,dep_parataxis,dep_csubjpass
0,26.0,59.0,13.0,25.0,21.0,12.0,31.0,41.0,30.0,6.0,22.0,1.0,22.0,52.0,47.0,19.0,7.0,12.0,19.0,6.0,7.0,3.0,19.0,9.0,4.0,2.0,7.0,3.0,5.0,4.0,2.0,6.0,1.0,2.0,2.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,6.0,44.0,20.0,15.0,26.0,10.0,35.0,32.0,26.0,6.0,7.0,1.0,3.0,35.0,32.0,11.0,5.0,6.0,9.0,3.0,15.0,0.0,9.0,1.0,2.0,0.0,1.0,0.0,1.0,0.0,5.0,2.0,0.0,0.0,2.0,0.0,2.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0
2,29.0,59.0,25.0,25.0,46.0,12.0,52.0,60.0,46.0,12.0,17.0,1.0,8.0,49.0,42.0,11.0,4.0,15.0,16.0,11.0,11.0,0.0,15.0,0.0,5.0,3.0,2.0,2.0,2.0,2.0,4.0,13.0,1.0,0.0,1.0,0.0,6.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
3,28.0,38.0,21.0,29.0,20.0,3.0,54.0,49.0,19.0,2.0,13.0,1.0,12.0,50.0,48.0,11.0,4.0,9.0,21.0,2.0,9.0,2.0,19.0,6.0,9.0,4.0,2.0,0.0,2.0,4.0,2.0,2.0,2.0,0.0,7.0,2.0,5.0,2.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0
4,25.0,32.0,16.0,22.0,10.0,9.0,37.0,63.0,7.0,3.0,8.0,1.0,19.0,50.0,43.0,3.0,8.0,5.0,9.0,7.0,3.0,1.0,9.0,2.0,6.0,4.0,4.0,1.0,5.0,1.0,0.0,2.0,0.0,0.0,1.0,0.0,9.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [25]:
# from gensim.scripts.glove2word2vec import glove2word2vec

# glove_input_file = '/home/jack/github/kaggle/scoring/data/glove.6B.100d.txt'
# word2vec_output_file = 'word2vec.glove.6B.100d.txt'
# glove2word2vec(glove_input_file, word2vec_output_file)

In [26]:
# from sklearn.feature_extraction.text import CountVectorizer
# import pandas as pd
# import spacy
# import numpy as np
# import pickle
# from gensim.models import KeyedVectors
# from sklearn.decomposition import PCA

# df_train = train.copy()

# # Load spaCy model

# # Load GloVe model
# glove_model = KeyedVectors.load_word2vec_format('glove.840B.300d.word2vec.clean', binary=False, no_header=True)

# # Initialize CountVectorizer with tokens that exist in the GloVe vocabulary
# vectorizer = CountVectorizer(ngram_range=(1, 3), max_features=500, vocabulary=set(glove_model.key_to_index.keys()))

# # Function to embed text using GloVe embeddings
# def embed_text(text, model, vectorizer):
#     matrix = vectorizer.transform([text])
#     words = vectorizer.get_feature_names_out()
#     embeddings = np.zeros((300,))  # Corrected to 300 dimensions
#     for word in words:
#         if word in model:
#             embeddings += model[word] * matrix[0, vectorizer.vocabulary_[word]]
#     return embeddings / len(words) if len(words) > 0 else embeddings

# # Embed the text data

# # Collect and embed tags
# def get_tag_embeddings(text, model):
#     doc = nlp(text)
#     tag_vector = np.zeros((300,))  # Corrected to 300 dimensions
#     tags = doc.count_by(spacy.attrs.POS)
#     for tag_id, count in tags.items():
#         tag = doc.vocab.strings[tag_id]
#         if tag.lower() in model:
#             tag_vector += model[tag.lower()] * count
#     return tag_vector

# df_train['tag_embeddings'] = df_train['full_text'].apply(lambda x: get_tag_embeddings(x, glove_model))

# # Apply PCA to reduce dimensionality
# pca = PCA(n_components=50)  # Reduce to 50 features for example
# features = np.vstack(df_train['text_embeddings'].values)
# tag_features = np.vstack(df_train['tag_embeddings'].values)
# combined_features = np.hstack((features, tag_features))

# pca_features = pca.fit_transform(combined_features)

# # Create a DataFrame from the PCA features
# df_train_pca = pd.DataFrame(pca_features, columns=[f'pca_feature_{i}' for i in range(pca_features.shape[1])])

# # Concatenate PCA features back to the original DataFrame
# df_train_final = pd.concat([df_train.reset_index(drop=True), df_train_pca], axis=1)

# # Serialize and save the PCA model and vectorizer
# with open('vectorizer.pkl', 'wb') as f:
#     pickle.dump(vectorizer, f)
# with open('pca_model.pkl', 'wb') as f:
#     pickle.dump(pca, f)

In [27]:
import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis

# Function to calculate statistical features for a list of tag counts
def calculate_statistical_features(tag_counts):
    # Calculate statistical features
    mean = np.mean(tag_counts)
    std = np.std(tag_counts)
    max_count = np.max(tag_counts)
    min_count = np.min(tag_counts)
    skewness = skew(tag_counts)
    kurt = kurtosis(tag_counts)
    return mean, std, max_count, min_count, skewness, kurt

# Function to extract statistical features from tag dataframes
def extract_statistical_features(tag_df,tag=None):
    # Calculate statistical features across rows
    tag_df[f'{tag}_mean'], tag_df[f'{tag}_std'], tag_df[f'{tag}_max'], tag_df[f'{tag}_min'], tag_df[f'{tag}_skew'], tag_df[f'{tag}_kurtosis'] = \
        zip(*tag_df.apply(lambda row: calculate_statistical_features(row), axis=1))

    tag_df.drop(columns=tag_df.columns[:-6], inplace=True)
    
    return tag_df

# Assuming you have separate dataframes for each tag type: pos_df, ner_df, dep_df
# You would pass these dataframes to the function accordingly
# For example:

pos_df = df_pos.copy()    # dataframe containing POS tag counts
ner_df = df_entities.copy()  # dataframe containing named entity tag counts
dep_df = df_deps.copy()  # dataframe containing dependency tag counts

# Extract statistical features for each tag type
pos_features = extract_statistical_features(pos_df,tag='pos')
ner_features = extract_statistical_features(ner_df,tag='ner')
dep_features = extract_statistical_features(dep_df,tag='dep')

# Concatenate statistical features DataFrames back to the original DataFrame
df_train_final = pd.concat([df.reset_index(drop=True), pos_features, ner_features, dep_features], axis=1)

In [28]:
df_train_final.tail()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,svd_0,svd_1,svd_2,svd_3,svd_4,svd_5,svd_6,svd_7,svd_8,svd_9,svd_10,svd_11,svd_12,svd_13,svd_14,svd_15,svd_16,svd_17,svd_18,svd_19,svd_20,svd_21,svd_22,svd_23,svd_24,svd_25,svd_26,svd_27,svd_28,svd_29,svd_30,svd_31,svd_32,svd_33,svd_34,svd_35,svd_36,svd_37,svd_38,svd_39,svd_40,svd_41,svd_42,svd_43,svd_44,svd_45,svd_46,svd_47,svd_48,svd_49,svd_50,svd_51,svd_52,svd_53,svd_54,svd_55,svd_56,svd_57,svd_58,svd_59,svd_60,svd_61,svd_62,svd_63,svd_64,svd_65,svd_66,svd_67,svd_68,svd_69,svd_70,svd_71,svd_72,svd_73,svd_74,svd_75,svd_76,svd_77,svd_78,svd_79,svd_80,svd_81,svd_82,svd_83,svd_84,svd_85,svd_86,svd_87,svd_88,svd_89,svd_90,svd_91,svd_92,svd_93,svd_94,svd_95,svd_96,svd_97,svd_98,svd_99,pos_mean,pos_std,pos_max,pos_min,pos_skew,pos_kurtosis,ner_mean,ner_std,ner_max,ner_min,ner_skew,ner_kurtosis,dep_mean,dep_std,dep_max,dep_min,dep_skew,dep_kurtosis
17302,ffd378d,"the story "" The Challenge of Exploing Venus "" ...",2,the story the challenge of exploing venus is a...,0.150013,0.835257,0.012670,0.000888,0.000525,0.000646,0.119509,0.170006,0.154826,0.292306,0.154355,0.108999,0.0,0.000000,0.000000,0.000000,0.080128,0.080128,0.0,0.0,0.040064,0.040064,0.0,0.160257,0.000000,0.000000,0.040064,0.000000,0.000000,0.040064,0.080128,0.000000,0.000000,0.000000,0.000000,0.080128,0.000000,0.0,0.040064,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.040064,0.000000,0.000000,0.000000,0.000000,0.000000,0.080128,0.000000,0.120192,0.040064,0.040064,0.240385,0.000000,0.080128,0.000000,0.040064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.080128,0.080128,0.000000,0.000000,0.040064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.080128,0.120192,0.160257,0.000000,0.040064,0.040064,0.040064,0.000000,0.000000,0.040064,0.080128,0.240385,0.000000,0.000000,0.040064,0.040064,0.200321,0.000000,0.000000,0.000000,0.080128,0.040064,0.000000,0.000000,0.000000,0.000000,0.0,0.040064,0.040064,0.0,0.000000,0.000000,0.040064,0.000000,0.000000,0.040064,0.040064,0.040064,0.000000,0.040064,0.160257,0.0,0.0,0.120192,0.000000,0.0,0.120192,0.000000,0.000000,0.000000,0.040064,0.120192,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.040064,0.040064,0.000000,0.040064,0.0,0.160257,0.000000,0.040064,0.040064,0.000000,0.000000,0.080128,0.040064,0.040064,0.0,0.080128,0.000000,0.000000,0.040064,0.120192,0.000000,0.000000,0.000000,0.040064,0.641026,0.000000,0.000000,0.040064,0.0,0.080128,0.000000,0.000000,0.000000,0.000000,0.000000,0.040064,0.040064,0.040064,0.000000,0.000000,0.000000,0.040064,0.000000,0.000000,0.000000,0.080128,0.040064,0.040064,0.120192,0.0,0.040064,0.000000,0.000000,0.000000,0.080128,0.000000,0.000000,0.000000,0.000000,0.040064,0.0,0.000000,0.240385,0.000000,0.000000,0.000000,0.214177,0.459036,-0.233979,-0.205699,-0.039363,-0.018007,-0.014196,-0.002807,-0.003657,-0.026082,0.131188,0.081606,0.005771,-0.013425,-0.042102,0.067407,0.031176,0.025881,-0.122788,0.035872,-0.176617,0.098293,0.028595,-0.035031,-0.068678,0.101317,-0.013141,0.003266,0.006489,0.040043,-0.080548,0.008567,-0.052535,-0.036138,0.087091,0.029054,0.060669,-0.027633,0.085886,-0.046112,0.026840,-0.045974,-0.010615,-0.041346,0.065945,-0.013621,0.026439,-0.027549,-0.027042,0.019292,0.046645,-0.036446,0.004270,0.039065,0.006126,0.039381,-0.032295,0.026743,-0.029638,-0.033399,0.000135,0.013069,-0.035875,0.002265,-0.001092,0.000583,-0.027432,0.029894,-0.034258,-0.001918,-0.025885,-0.040081,0.012777,-0.063423,-0.021517,0.023339,-0.030030,0.026478,-0.006447,-0.021586,-0.015591,0.015276,-0.026445,-0.005091,-0.016481,-0.003349,0.001071,-0.050408,0.010631,0.025434,-0.078938,-0.017031,-0.012172,-0.023046,0.018644,0.004834,-0.007631,-0.015422,0.014459,0.020009,9.444444,9.598740,39.0,0.0,1.506702,2.445340,0.111111,0.314270,1.0,0.0,2.474874,4.125000,3.777778,5.431958,23.0,0.0,1.643783,2.182621
17303,ffddf1f,Technology has changed a lot of ways that we l...,4,technology has changed a lot of ways that we l...,0.009600,0.255906,0.622500,0.109013,0.002178,0.000803,0.133139,0.110119,0.256705,0.116726,0.168298,0.215013,0.0,0.014075,0.042224,0.000000,0.028149,0.239271,0.0,0.0,0.028149,0.028149,0.0,0.098523,0.042224,0.042224,0.028149,0.014075,0.028149,0.014075,0.014075,0.000000,0.042224,0.042224,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.140747,0.0,0.000000,0.056299,0.000000,0.014075,0.028149,0.000000,0.000000,0.014075,0.042224,0.056299,0.014075,0.000000,0.028149,0.028149,0.182972,0.000000,0.000000,0.014075,0.000000,0.098523,0.014075,0.014075,0.042224,0.028149,0.028149,0.000000,0.0,0.0,0.028149,0.070374,0.112598,0.211121,0.042224,0.014075,0.014075,0.070374,0.014075,0.042224,0.000000,0.014075,0.084448,0.014075,0.014075,0.014075,0.014075,0.028149,0.168897,0.028149,0.014075,0.168897,0.014075,0.042224,0.000000,0.028149,0.042224,0.084448,0.014075,0.000000,0.154822,0.000000,0.182972,0.014075,0.056299,0.014075,0.211121,0.028149,0.014075,0.140747,0.070374,0.014075,0.0,0.014075,0.056299,0.0,0.042224,0.000000,0.056299,0.028149,0.000000,0.042224,0.070374,0.000000,0.028149,0.000000,0.014075,0.0,0.0,0.126673,0.098523,0.0,0.000000,0.098523,0.028149,0.056299,0.000000,0.056299,0.028149,0.014075,0.014075,0.014075,0.042224,0.028149,0.098523,0.042224,0.112598,0.098523,0.000000,0.0,0.056299,0.098523,0.028149,0.014075,0.014075,0.014075,0.140747,0.014075,0.000000,0.0,0.084448,0.042224,0.000000,0.028149,0.042224,0.000000,0.098523,0.014075,0.070374,0.506691,0.098523,0.014075,0.028149,0.0,0.028149,0.014075,0.014075,0.014075,0.014075,0.000000,0.056299,0.014075,0.000000,0.014075,0.028149,0.056299,0.000000,0.014075,0.042224,0.028149,0.000000,0.014075,0.000000,0.056299,0.0,0.028149,0.000000,0.014075,0.168897,0.056299,0.042224,0.000000,0.056299,0.028149,0.028149,0.0,0.000000,0.211121,0.182972,0.028149,0.014075,0.252578,0.177398,0.025485,0.431817,-0.253414,-0.106381,0.017448,-0.198941,-0.105102,-0.093676,0.136606,-0.098067,0.015432,0.026495,-0.035193,-0.005151,0.009591,0.040695,-0.113803,-0.015406,0.009116,0.002108,-0.033568,0.005397,0.005547,0.036186,-0.056294,0.005248,0.074781,0.021982,0.112217,-0.079898,0.047224,-0.035821,0.116172,0.089135,-0.013071,0.159688,0.071287,0.030098,0.000839,0.130504,-0.071156,-0.104472,-0.008456,0.104515,-0.123109,0.006903,-0.122611,0.110430,0.063738,-0.104236,0.053189,-0.001091,-0.078543,0.108543,0.078269,-0.080328,-0.004958,0.128319,-0.006320,0.065196,-0.030314,0.046678,-0.023336,-0.034163,0.005730,0.015826,0.049925,0.025181,0.020276,-0.069861,-0.005573,0.030130,-0.062834,-0.009959,0.005017,-0.000142,-0.011233,-0.003252,-0.075449,0.017608,0.038338,0.059678,-0.001962,0.014981,0.031429,0.033917,0.016844,-0.012393,-0.022382,-0.049494,0.022410,0.027576,0.017285,-0.019598,-0.030205,-0.061618,-0.072090,-0.042735,36.111111,34.170957,128.0,0.0,1.034236,0.563065,0.777778,1.474055,5.0,0.0,1.843331,2.116736,14.444444,18.214226,68.0,0.0,1.418084,1.032358
17304,fff016d,If you don't like sitting around all day than ...,2,if you do not like sitting around all day than...,0.086867,0.899410,0.012025,0.000749,0.000382,0.000567,0.137695,0.118079,0.254256,0.107214,0.166540,0.216215,0.0,0.000000,0.000000,0.026764,0.026764,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.080293,0.000000,0.000000,0.080293,0.000000,0.000000,0.026764,0.133822,0.026764,0.000000,0.000000,0.000000,0.000000,0.026764,0.0,0.000000,0.053529,0.0,0.000000,0.0,0.026764,0.000000,0.026764,0.053529,0.000000,0.000000,0.107058,0.026764,0.000000,0.080293,0.000000,0.000000,0.000000,0.000000,0.107058,0.026764,0.000000,0.000000,0.000000,0.000000,0.026764,0.000000,0.000000,0.026764,0.026764,0.000000,0.0,0.0,0.000000,0.026764,0.026764,0.026764,0.000000,0.000000,0.053529,0.000000,0.000000,0.026764,0.000000,0.000000,0.000000,0.026764,0.026764,0.000000,0.026764,0.000000,0.133822,0.000000,0.000000,0.000000,0.026764,0.000000,0.026764,0.026764,0.026764,0.000000,0.000000,0.000000,0.053529,0.000000,0.321173,0.000000,0.107058,0.000000,0.080293,0.000000,0.000000,0.026764,0.000000,0.026764,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.026764,0.133822,0.000000,0.000000,0.000000,0.000000,0.026764,0.0,0.0,0.107058,0.160586,0.0,0.000000,0.000000,0.000000,0.080293,0.026764,0.000000,0.000000,0.026764,0.026764,0.000000,0.026764,0.000000,0.053529,0.000000,0.026764,0.187351,0.000000,0.0,0.026764,0.000000,0.000000,0.000000,0.000000,0.000000,0.187351,0.000000,0.000000,0.0,0.133822,0.000000,0.000000,0.026764,0.000000,0.026764,0.000000,0.000000,0.080293,0.160586,0.000000,0.026764,0.053529,0.0,0.000000,0.214115,0.000000,0.026764,0.000000,0.026764,0.026764,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.026764,0.000000,0.026764,0.000000,0.026764,0.000000,0.107058,0.0,0.187351,0.053529,0.026764,0.000000,0.588817,0.026764,0.187351,0.133822,0.026764,0.000000,0.0,0.000000,0.267644,0.000000,0.053529,0.000000,0.167997,0.071449,0.026181,0.136978,-0.032241,0.447435,-0.048748,-0.005931,0.008201,-0.021611,-0.019912,0.013260,-0.206401,-0.040271,-0.104341,-0.043548,-0.013737,0.098323,0.103531,-0.128960,0.110889,0.189912,0.355740,-0.193759,0.260343,0.093990,0.026572,0.025459,-0.001824,0.047824,0.020315,0.030168,-0.022961,0.008042,-0.018474,-0.013465,-0.015593,0.074621,-0.006588,-0.043136,0.002649,0.007577,-0.015550,-0.026118,0.009631,-0.016571,-0.040340,0.002145,0.025173,-0.005386,0.036404,-0.009485,-0.038530,-0.054053,-0.021586,-0.006167,0.035097,-0.012098,0.030505,-0.026604,0.041415,0.053348,-0.011761,-0.019985,-0.041130,0.085076,-0.043086,0.001572,-0.047477,0.044660,0.000192,0.013304,0.029189,-0.003896,0.024987,-0.011491,0.025300,0.019417,-0.027412,0.052522,0.061980,0.006212,-0.059859,-0.020701,-0.036570,0.000771,-0.039668,0.056864,-0.034313,0.012625,-0.004323,-0.077225,0.008319,0.003641,-0.046841,0.007083,-0.040058,0.002620,-0.021648,0.005228,13.166667,12.711543,40.0,0.0,0.865333,-0.271338,0.166667,0.372678,1.0,0.0,1.788854,1.200000,5.266667,6.971051,29.0,0.0,1.424120,1.418718
17305,fffb49b,"In ""The Challenge of Exporing Venus,"" the auth...",1,in the challenge of exporing venus the author ...,0.470797,0.505351,0.019677,0.002093,0.000977,0.001105,0.118225,0.164676,0.154792,0.305532,0.149845,0.106930,0.0,0.000000,0.000000,0.000000,0.000000,0.028296,0.0,0.0,0.056591,0.028296,0.0,0.084887,0.000000,0.000000,0.056591,0.028296,0.056591,0.056591,0.028296,0.056591,0.028296,0.084887,0.028296,0.000000,0.000000,0.0,0.000000,0.056591,0.0,0.028296,0.0,0.000000,0.000000,0.056591,0.141478,0.000000,0.028296,0.000000,0.113182,0.000000,0.084887,0.000000,0.028296,0.056591,0.000000,0.169774,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.056591,0.084887,0.000000,0.0,0.0,0.000000,0.028296,0.000000,0.000000,0.000000,0.000000,0.000000,0.113182,0.000000,0.028296,0.028296,0.028296,0.000000,0.000000,0.000000,0.000000,0.028296,0.056591,0.226365,0.000000,0.028296,0.000000,0.028296,0.000000,0.000000,0.028296,0.000000,0.396138,0.000000,0.028296,0.198069,0.028296,0.282956,0.000000,0.000000,0.000000,0.113182,0.000000,0.000000,0.056591,0.000000,0.028296,0.0,0.056591,0.000000,0.0,0.056591,0.028296,0.000000,0.000000,0.000000,0.056591,0.113182,0.056591,0.000000,0.056591,0.084887,0.0,0.0,0.169774,0.000000,0.0,0.056591,0.028296,0.000000,0.028296,0.056591,0.028296,0.028296,0.000000,0.028296,0.000000,0.000000,0.000000,0.028296,0.056591,0.028296,0.141478,0.000000,0.0,0.000000,0.000000,0.084887,0.000000,0.000000,0.000000,0.056591,0.000000,0.000000,0.0,0.028296,0.028296,0.000000,0.000000,0.000000,0.028296,0.028296,0.000000,0.000000,0.481025,0.028296,0.113182,0.028296,0.0,0.028296,0.000000,0.000000,0.000000,0.000000,0.028296,0.028296,0.028296,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.028296,0.000000,0.000000,0.028296,0.000000,0.084887,0.0,0.028296,0.028296,0.000000,0.056591,0.056591,0.028296,0.000000,0.056591,0.000000,0.028296,0.0,0.056591,0.339547,0.028296,0.028296,0.000000,0.227337,0.609747,-0.317610,-0.308665,-0.040692,-0.044530,-0.001835,0.028513,-0.081218,0.043296,-0.020465,-0.065867,-0.000262,0.035889,0.047942,-0.140807,-0.090914,-0.075678,0.083182,-0.016053,0.103357,-0.041942,0.000593,-0.015137,-0.034364,0.020961,0.028144,-0.026239,0.059927,-0.021849,0.026186,0.025615,0.061783,0.141088,-0.036687,0.079231,0.079068,0.076164,-0.179985,-0.043132,-0.043802,0.004820,0.011555,0.058317,0.028803,0.033223,-0.029309,-0.029855,-0.042709,0.020581,0.037516,0.025078,0.055081,-0.042825,0.060515,0.031437,0.017387,0.020253,-0.060806,-0.031058,-0.015727,-0.023105,-0.011255,0.005385,-0.031572,-0.054252,-0.032370,-0.001762,0.003787,-0.032628,0.000227,-0.014860,0.045490,-0.031515,-0.041877,-0.000196,-0.001531,-0.017098,0.004899,0.036325,0.023459,-0.008238,0.020579,0.026040,-0.018902,0.018510,-0.022624,0.008335,0.029709,0.026158,-0.007303,0.002466,-0.034653,-0.024135,-0.026745,-0.051284,-0.053300,0.038272,-0.010083,-0.018030,15.000000,13.723459,51.0,0.0,0.887054,0.304751,1.444444,3.818409,17.0,0.0,3.728588,12.312041,6.000000,8.584223,34.0,0.0,1.852994,2.440799
17306,fffed3e,Venus is worthy place to study but dangerous. ...,2,venus is worthy place to study but dangerous t...,0.416230,0.571381,0.008966,0.001295,0.000857,0.001271,0.138152,0.112553,0.257051,0.111632,0.164506,0.216106,0.0,0.000000,0.038866,0.000000,0.000000,0.038866,0.0,0.0,0.000000,0.038866,0.0,0.077732,0.000000,0.000000,0.038866,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.038866,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.077732,0.0,0.038866,0.038866,0.038866,0.000000,0.155464,0.000000,0.116598,0.077732,0.000000,0.116598,0.038866,0.000000,0.038866,0.000000,0.077732,0.038866,0.000000,0.038866,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.038866,0.077732,0.0,0.0,0.000000,0.000000,0.038866,0.116598,0.000000,0.038866,0.038866,0.000000,0.000000,0.038866,0.000000,0.000000,0.038866,0.000000,0.000000,0.000000,0.000000,0.000000,0.194331,0.038866,0.000000,0.000000,0.000000,0.000000,0.000000,0.038866,0.000000,0.077732,0.000000,0.000000,0.077732,0.038866,0.544125,0.000000,0.038866,0.000000,0.233197,0.000000,0.038866,0.000000,0.000000,0.038866,0.0,0.000000,0.077732,0.0,0.038866,0.000000,0.000000,0.000000,0.000000,0.077732,0.000000,0.038866,0.000000,0.000000,0.155464,0.0,0.0,0.155464,0.155464,0.0,0.000000,0.000000,0.038866,0.038866,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.038866,0.000000,0.000000,0.077732,0.038866,0.000000,0.0,0.038866,0.000000,0.000000,0.000000,0.000000,0.000000,0.116598,0.000000,0.000000,0.0,0.038866,0.038866,0.038866,0.077732,0.000000,0.000000,0.038866,0.038866,0.000000,0.427527,0.000000,0.000000,0.000000,0.0,0.155464,0.077732,0.000000,0.000000,0.000000,0.038866,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.116598,0.000000,0.038866,0.038866,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.116598,0.116598,0.077732,0.000000,0.038866,0.000000,0.000000,0.0,0.000000,0.272063,0.000000,0.000000,0.000000,0.203476,0.276427,-0.120171,-0.079315,-0.031678,0.078580,-0.000674,-0.023075,0.104725,-0.001022,-0.086470,0.019797,0.051753,-0.013317,-0.007099,-0.082227,-0.034587,-0.021159,0.049328,-0.083726,-0.007360,-0.021531,0.011125,0.087386,-0.009785,0.097898,-0.080809,-0.021888,0.036754,-0.022633,-0.062419,0.058433,-0.061934,0.026312,0.030353,0.028916,0.006516,-0.098885,0.123571,0.108714,-0.030929,0.057583,0.014335,-0.093161,0.018975,-0.040856,0.044302,-0.028672,-0.020250,0.009443,0.063419,-0.035265,-0.009903,0.034476,-0.065984,0.016296,-0.068974,0.038907,-0.123647,0.007043,0.015522,0.004473,-0.029860,-0.073755,-0.022039,0.023191,-0.095144,-0.001412,0.002261,-0.036462,-0.026443,0.013675,0.024987,-0.008543,-0.008870,0.039746,-0.001909,0.007753,0.017436,-0.059184,0.015657,-0.010545,-0.028138,-0.113522,-0.010962,-0.036580,0.023464,0.066632,-0.002800,0.006662,-0.026645,0.034977,-0.019695,-0.009767,0.058412,-0.031872,-0.019413,-0.024908,0.008813,-0.066980,9.555556,7.551469,29.0,0.0,0.873956,0.361400,0.444444,0.761739,2.0,0.0,1.318992,0.013581,3.822222,5.169521,20.0,0.0,1.459867,1.214925

In [29]:
df_train_final.to_parquet('train_with_deberta.parquet')

In [30]:
train = df_train_final.copy()

In [31]:
train.head()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,svd_0,svd_1,svd_2,svd_3,svd_4,svd_5,svd_6,svd_7,svd_8,svd_9,svd_10,svd_11,svd_12,svd_13,svd_14,svd_15,svd_16,svd_17,svd_18,svd_19,svd_20,svd_21,svd_22,svd_23,svd_24,svd_25,svd_26,svd_27,svd_28,svd_29,svd_30,svd_31,svd_32,svd_33,svd_34,svd_35,svd_36,svd_37,svd_38,svd_39,svd_40,svd_41,svd_42,svd_43,svd_44,svd_45,svd_46,svd_47,svd_48,svd_49,svd_50,svd_51,svd_52,svd_53,svd_54,svd_55,svd_56,svd_57,svd_58,svd_59,svd_60,svd_61,svd_62,svd_63,svd_64,svd_65,svd_66,svd_67,svd_68,svd_69,svd_70,svd_71,svd_72,svd_73,svd_74,svd_75,svd_76,svd_77,svd_78,svd_79,svd_80,svd_81,svd_82,svd_83,svd_84,svd_85,svd_86,svd_87,svd_88,svd_89,svd_90,svd_91,svd_92,svd_93,svd_94,svd_95,svd_96,svd_97,svd_98,svd_99,pos_mean,pos_std,pos_max,pos_min,pos_skew,pos_kurtosis,ner_mean,ner_std,ner_max,ner_min,ner_skew,ner_kurtosis,dep_mean,dep_std,dep_max,dep_min,dep_skew,dep_kurtosis
0,000d118,Many people have car where they live. The thin...,3,many people have car where they live the thing...,0.156896,0.756281,0.079829,0.005163,0.000922,0.000909,0.116983,0.173203,0.157604,0.287849,0.154709,0.109652,0.031439,0.00000,0.047158,0.031439,0.015719,0.015719,0.220070,0.015719,0.031439,0.047158,0.000000,0.078597,0.015719,0.0,0.031439,0.000000,0.000000,0.031439,0.015719,0.000000,0.078597,0.000000,0.015719,0.015719,0.000000,0.00000,0.000000,0.031439,0.015719,0.204351,0.000000,0.015719,0.015719,0.015719,0.062877,0.000000,0.00000,0.094316,0.062877,0.015719,0.078597,0.047158,0.015719,0.000000,0.000000,0.204351,0.047158,0.062877,0.031439,0.031439,0.000000,0.015719,0.078597,0.015719,0.015719,0.015719,0.000000,0.078597,0.000000,0.047158,0.031439,0.047158,0.062877,0.000000,0.000000,0.015719,0.031439,0.0,0.015719,0.015719,0.062877,0.00000,0.047158,0.015719,0.000000,0.047158,0.015719,0.125754,0.000000,0.000000,0.015719,0.015719,0.015719,0.015719,0.078597,0.047158,0.047158,0.015719,0.015719,0.251509,0.000000,0.314386,0.000000,0.141474,0.0,0.345825,0.015719,0.015719,0.015719,0.031439,0.031439,0.00000,0.0,0.015719,0.000000,0.0,0.000000,0.000000,0.000000,0.031439,0.172912,0.125754,0.015719,0.000000,0.000000,0.000000,0.0,0.000000,0.062877,0.031439,0.015719,0.062877,0.110035,0.000000,0.031439,0.000000,0.047158,0.000000,0.000000,0.157193,0.015719,0.078597,0.031439,0.015719,0.000000,0.031439,0.157193,0.047158,0.015719,0.047158,0.078597,0.000000,0.000000,0.000000,0.015719,0.062877,0.000000,0.000000,0.00000,0.000000,0.000000,0.031439,0.062877,0.015719,0.015719,0.000000,0.015719,0.015719,0.330105,0.015719,0.015719,0.031439,0.000000,0.062877,0.015719,0.015719,0.062877,0.0,0.015719,0.000000,0.031439,0.031439,0.015719,0.00000,0.031439,0.000000,0.015719,0.015719,0.047158,0.031439,0.00000,0.047158,0.094316,0.0,0.094316,0.015719,0.031439,0.141474,0.204351,0.000000,0.00000,0.094316,0.015719,0.031439,0.015719,0.015719,0.267228,0.031439,0.000000,0.015719,0.544825,-0.189884,-0.010533,-0.051079,0.012280,0.073776,0.281282,-0.050995,0.047948,0.045735,-0.007755,-0.010318,0.024401,0.010347,-0.098132,-0.160383,0.003923,-0.062895,-0.036259,0.088925,0.018202,0.129021,-0.010308,0.058141,0.026209,0.041230,-0.005461,0.120057,0.055210,-0.174005,-0.065167,-0.078753,0.008007,-0.051039,0.006475,0.133725,-0.047937,-0.014881,-0.051736,0.060226,0.039396,-0.023538,-0.045470,0.106766,-0.050663,0.001495,0.000571,-0.017743,-0.023689,0.100732,0.016265,-0.096240,-0.090763,0.102225,0.096276,-0.050531,-0.077765,-0.021038,-0.003110,-0.014012,0.058317,-0.035382,-0.050896,0.058633,0.083828,0.008253,-0.089623,0.040854,0.071474,-0.030355,-0.025904,0.006697,0.011512,-0.050107,-0.004740,-0.030036,-0.024568,0.031643,-0.034755,-0.022855,0.006315,-0.073811,-0.093401,0.032384,0.003544,0.059571,0.005125,0.000443,-0.015434,0.050374,0.034458,-0.013548,0.021799,-0.015298,-0.031860,0.006069,-0.023470,0.047083,-0.046250,-0.005484,30.666667,26.248809,106.0,0.0,1.187275,1.389150,1.500000,1.536591,5.0,0.0,0.689073,-0.607059,12.266667,14.800000,59.0,0.0,1.525231,1.642529
1,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489,0.071429,0.02381,0.023810,0.000000,0.000000,0.119048,0.000000,0.023810,0.000000,0.047619,0.023810,0.023810,0.023810,0.0,0.119048,0.023810,0.023810,0.000000,0.119048,0.023810,0.000000,0.000000,0.000000,0.023810,0.000000,0.00000,0.000000,0.023810,0.000000,0.047619,0.000000,0.000000,0.047619,0.071429,0.047619,0.071429,0.00000,0.142857,0.000000,0.000000,0.190476,0.000000,0.000000,0.023810,0.000000,0.190476,0.047619,0.000000,0.000000,0.000000,0.000000,0.095238,0.000000,0.000000,0.000000,0.095238,0.071429,0.047619,0.000000,0.023810,0.023810,0.119048,0.047619,0.000000,0.000000,0.000000,0.000000,0.0,0.023810,0.023810,0.000000,0.00000,0.000000,0.023810,0.023810,0.071429,0.047619,0.285714,0.000000,0.000000,0.000000,0.047619,0.000000,0.000000,0.000000,0.023810,0.119048,0.047619,0.023810,0.023810,0.071429,0.214286,0.023810,0.095238,0.0,0.261905,0.000000,0.047619,0.023810,0.071429,0.000000,0.02381,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.023810,0.071429,0.285714,0.023810,0.000000,0.000000,0.071429,0.0,0.000000,0.190476,0.023810,0.000000,0.023810,0.000000,0.023810,0.238095,0.000000,0.047619,0.000000,0.000000,0.000000,0.000000,0.071429,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.023810,0.071429,0.000000,0.023810,0.047619,0.000000,0.095238,0.000000,0.000000,0.02381,0.000000,0.000000,0.000000,0.047619,0.190476,0.023810,0.142857,0.000000,0.071429,0.214286,0.023810,0.047619,0.000000,0.000000,0.023810,0.000000,0.000000,0.047619,0.0,0.000000,0.047619,0.000000,0.023810,0.000000,0.00000,0.000000,0.071429,0.000000,0.000000,0.023810,0.000000,0.00000,0.071429,0.142857,0.0,0.047619,0.023810,0.047619,0.047619,0.285714,0.095238,0.00000,0.119048,0.000000,0.000000,0.000000,0.023810,0.190476,0.071429,0.000000,0.023810,0.205040,0.217370,-0.031039,0.272461,0.453655,-0.037745,-0.019981,0.009856,0.049202,-0.001963,-0.024337,0.006589,-0.006597,0.002178,0.009909,-0.018456,-0.057011,0.170369,0.085651,0.106610,-0.030153,-0.027684,-0.015578,0.041678,-0.009675,0.050569,0.136401,-0.083315,0.042187,-0.066536,0.036520,-0.011886,-0.066255,-0.113199,-0.004897,-0.003619,-0.057104,-0.086686,0.035855,-0.035598,0.032015,0.086592,0.052601,0.074656,-0.015745,-0.002698,0.028011,-0.044304,-0.041321,0.019398,-0.040185,0.118903,-0.031578,-0.034999,-0.012981,-0.055997,0.070947,-0.049436,-0.087271,0.016408,0.018653,0.042151,-0.002066,0.080365,0.045594,-0.018101,0.006542,-0.036857,-0.076236,-0.063488,-0.064376,-0.063611,0.012086,-0.024745,-0.028877,0.037434,-0.065357,0.022080,0.002638,0.001128,-0.033116,0.019474,0.059367,0.020719,-0.020409,-0.025308,-0.067791,-0.032011,0.005550,0.062103,-0.050343,-0.016034,0.092190,0.104312,0.012233,-0.018585,0.034503,0.010248,-0.047225,0.081963,20.944444,17.755976,53.0,0.0,0.424048,-1.241849,0.666667,1.247219,5.0,0.0,2.367171,5.295918,8.377778,11.654830,44.0,0.0,1.563887,1.260918
2,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192,0.014565,0.00000,0.058259,0.000000,0.014565,0.058259,0.189343,0.000000,0.014565,0.029130,0.014565,0.058259,0.000000,0.0,0.029130,0.014565,0.000000,0.014565,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.00000,0.000000,0.029130,0.000000,0.160213,0.014565,0.029130,0.000000,0.029130,0.058259,0.043694,0.00000,0.145648,0.014565,0.029130,0.087389,0.029130,0.116519,0.000000,0.014565,0.116519,0.029130,0.000000,0.014565,0.043694,0.014565,0.014565,0.043694,0.029130,0.000000,0.043694,0.000000,0.014565,0.000000,0.000000,0.029130,0.131083,0.058259,0.014565,0.014565,0.000000,0.000000,0.0,0.014565,0.000000,0.000000,0.00000,0.014565,0.029130,0.014565,0.072824,0.058259,0.145648,0.043694,0.029130,0.145648,0.000000,0.029130,0.000000,0.029130,0.029130,0.160213,0.029130,0.000000,0.131083,0.043694,0.305861,0.087389,0.087389,0.0,0.189343,0.000000,0.014565,0.145648,0.014565,0.014565,0.00000,0.0,0.145648,0.000000,0.0,0.000000,0.000000,0.043694,0.000000,0.087389,0.160213,0.000000,0.014565,0.000000,0.029130,0.0,0.014565,0.072824,0.029130,0.000000,0.029130,0.000000,0.014565,0.043694,0.014565,0.072824,0.029130,0.014565,0.000000,0.014565,0.087389,0.000000,0.101954,0.145648,0.116519,0.116519,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.014565,0.160213,0.014565,0.000000,0.00000,0.029130,0.000000,0.014565,0.087389,0.043694,0.000000,0.014565,0.043694,0.029130,0.407815,0.029130,0.000000,0.058259,0.014565,0.072824,0.000000,0.043694,0.029130,0.0,0.014565,0.058259,0.000000,0.000000,0.029130,0.00000,0.000000,0.000000,0.087389,0.014565,0.000000,0.000000,0.02913,0.029130,0.189343,0.0,0.101954,0.043694,0.087389,0.087389,0.189343,0.116519,0.02913,0.043694,0.014565,0.014565,0.000000,0.014565,0.262167,0.014565,0.000000,0.000000,0.687501,-0.266419,-0.035382,-0.049885,-0.030061,-0.044606,-0.083800,-0.013786,0.026421,0.028490,0.041332,-0.050998,-0.005691,0.018673,-0.056219,-0.031236,0.008812,0.032260,-0.098160,-0.035661,-0.003174,-0.026700,-0.125245,0.021099,0.129486,0.101162,-0.015486,0.002999,-0.011790,0.004190,0.098894,0.035090,0.027681,0.038791,0.051883,0.041869,-0.135450,0.051997,0.027452,-0.023337,-0.045703,-0.085838,-0.007777,-0.059742,0.005840,0.100018,-0.029266,-0.035098,0.053366,0.038389,0.044539,0.006135,-0.052506,-0.037970,0.038048,-0.051751,0.046251,0.038150,-0.001206,0.011612,0.091752,-0.039690,0.057636,-0.007038,-0.042313,-0.045293,0.032674,0.010734,-0.042492,0.000679,0.026521,-0.080046,-0.031703,-0.043368,0.016350,-0.061957,0.038121,-0.047929,-0.017938,-0.018440,-0.008830,0.007855,0.006062,0.015039,0.068533,-0.092163,0.037666,0.025114,-0.045514,-0.000045,0.040887,-0.027900,-0.012989,0.019213,-0.058602,-0.013689,0.008837,0.011720,0.015783,-0.051454,33.944444,30.833734,115.0,0.0,0.748649,0.254957,0.111111,0.314270,1.0,0.0,2.474874,4.125000,13.577778,17.633918,60.0,0.0,1.410024,0.717690
3,001bdc0,"We all heard about Venus, the planet without a...",4,we all heard about venus the planet without al...,0.009681,0.273882,0.657448,0.056872,0.001404,0.000713,0.118487,0.169333,0.149879,0.299778,0.153946,0.108576,0.000000,0.00000,0.000000,0.000000,0.000000,0.017090,0.000000,0.000000,0.017090,0.034179,0.000000,0.187986,0.000000,0.0,0.051269,0.000000,0.034179,0.034179,0.034179,0.017090,0.051269,0.034179,0.017090,0.017090,0.034179,0.01709,0.051269,0.017090,0.017090,0.051269,0.000000,0.034179,0.085448,0.051269,0.068359,0.000000,0.01709,0.034179,0.017090,0.017090,0.068359,0.000000,0.000000,0.000000,0.017090,0.222165,0.034179,0.017090,0.017090,0.034179,0.000000,0.034179,0.017090,0.000000,0.034179,0.119628,0.068359,0.085448,0.034179,0.017090,0.017090,0.017090,0.205076,0.017090,0.000000,0.017090,0.068359,0.0,0.017090,0.000000,0.051269,0.01709,0.034179,0.017090,0.000000,0.068359,0.102538,0.136717,0.000000,0.034179,0.051269,0.000000,0.068359,0.000000,0.000000,0.034179,0.290524,0.051269,0.034179,0.068359,0.068359,0.273434,0.000000,0.051269,0.0,0.187986,0.085448,0.000000,0.034179,0.068359,0.000000,0.00000,0.0,0.034179,0.017090,0.0,0.000000,0.051269,0.000000,0.000000,0.068359,0.068359,0.017090,0.000000,0.017090,0.153807,0.0,0.000000,0.068359,0.000000,0.000000,0.017090,0.051269,0.000000,0.000000,0.068359,0.000000,0.068359,0.017090,0.000000,0.000000,0.017090,0.034179,0.034179,0.017090,0.017090,0.034179,0.000000,0.017090,0.153807,0.000000,0.034179,0.068359,0.034179,0.000000,0.000000,0.034179,0.051269,0.01709,0.017090,0.017090,0.000000,0.000000,0.051269,0.017090,0.017090,0.017090,0.051269,0.529779,0.017090,0.017090,0.051269,0.017090,0.034179,0.000000,0.000000,0.034179,0.0,0.000000,0.017090,0.000000,0.034179,0.000000,0.01709,0.000000,0.102538,0.000000,0.017090,0.017090,0.000000,0.00000,0.034179,0.102538,0.0,0.085448,0.034179,0.000000,0.051269,0.085448,0.017090,0.00000,0.119628,0.017090,0.017090,0.034179,0.000000,0.256345,0.068359,0.051269,0.000000,0.281380,0.583974,-0.287298,-0.250244,-0.054857,-0.037031,0.011803,-0.005103,-0.034663,0.002127,-0.005117,-0.022249,0.002925,-0.000781,-0.028364,0.045355,0.037422,-0.006060,-0.013822,0.013149,0.075274,-0.089940,0.103589,0.019310,-0.110465,0.130037,-0.105881,0.049014,-0.045152,-0.084381,0.037319,0.012755,0.042786,-0.051966,-0.014208,-0.046379,-0.043154,-0.039114,0.087373,-0.055309,0.029274,0.090240,0.015093,-0.018132,0.048475,-0.004822,0.042664,0.006894,0.027298,0.044310,-0.011012,-0.009658,-0.020360,0.030824,-0.038189,-0.090558,-0.012865,-0.056070,0.034004,0.003470,-0.050513,0.049282,-0.004327,-0.035919,-0.011728,-0.031122,0.027209,-0.043494,0.011648,0.007296,0.019443,0.028884,0.045502,0.015648,0.025653,-0.040580,0.034176,0.026044,-0.042871,-0.019505,-0.017890,0.016700,0.028477,0.023827,-0.003119,0.059362,-0.050197,-0.013285,0.014047,-0.022912,0.026219,0.007983,-0.047548,-0.072501,0.025585,0.005009,0.048430,0.017436,0.031691,-0.015029,28.666667,27.808871,113.0,0.0,1.466586,2.111442,1.611111,3.417909,15.0,0.0,3.288367,10.112290,11.466667,15.031227,54.0,0.0,1.590025,1.434855
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,dear state senator this is a letter to argue i...,0.059430,0.691130,0.233244,0.014120,0.001189,0.000887,0.132971,0.113607,0.266656,0.112359,0.161093,0.213313,0.047637,0.00000,0.079395,0.015879,0.000000,0.000000,0.015879,0.000000,0.000000,0.000000,0.015879,0.079395,0.015879,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063516,0.000000,0.031758,0.00000,0.000000,0.015879,0.000000,0.031758,0.031758,0.000000,0.000000,0.000000,0.063516,0.015879,0.00000,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.031758,0.031758,0.079395,0.000000,0.206427,0.015879,0.000000,0.000000,0.015879,0.095274,0.095274,0.047637,0.015879,0.015879,0.000000,0.031758,0.015879,0.015879,0.000000,0.111153,0.015879,0.079395,0.000000,0.000000,0.0,0.000000,0.015879,0.000000,0.00000,0.015879,0.015879,0.000000,0.047637,0.031758,0.238185,0.015879,0.000000,0.031758,0.000000,0.000000,0.015879,0.000000,0.000000,0.063516,0.285822,0.031758,0.238185,0.063516,0.079395,0.047637,0.031758,0.0,0.127032,0.142911,0.031758,0.047637,0.127032,0.000000,0.00000,0.0,0.000000,0.031758,0.0,0.031758,0.000000,0.015879,0.000000,0.063516,0.031758,0.015879,0.000000,0.031758,0.000000,0.0,0.000000,0.127032,0.000000,0.000000,0.000000,0.047637,0.015879,0.015879,0.047637,0.000000,0.000000,0.000000,0.000000,0.015879,0.031758,0.031758,0.000000,0.047637,0.000000,0.031758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015879,0.000000,0.00000,0.015879,0.063516,0.000000,0.015879,0.015879,0.015879,0.000000,0.015879,0.000000,0.619282,0.000000,0.000000,0.079395,0.015879,0.031758,0.047637,0.000000,0.063516,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.015879,0.000000,0.015879,0.000000,0.000000,0.031758,0.00000,0.000000,0.031758,0.0,0.015879,0.031758,0.015879,0.063516,0.095274,0.031758,0.00000,0.031758,0.000000,0.000000,0.000000,0.000000,0.381096,0.000000,0.031758,0.000000,0.151348,0.241555,0.776680,-0.197532,0.018671,-0.047295,-0.015960,0.039621,-0.072211,0.024053,0.032644,-0.070850,0.020442,-0.194149,0.008192,-0.011022,-0.015245,-0.002659,0.004816,0.020391,0.003484,-0.000490,-0.008179,-0.017140,0.010346,-0.000049,0.005370,0.006800,0.011052,0.025029,0.010626,0.005678,0.003944,0.004844,-0.012312,-0.024092,0.032662,0.024605,0.031665,-0.058857,-0.022696,-0.004376,0.074859,-0.005810,-0.101222,-0.013842,0.032072,0.003517,-0.005772,0.048595,0.010759,-0.033125,0.009872,0.014331,0.029457,-0.046831,-0.050309,-0.045821,-0.025609,0.064919,-0.011102,-0.021133,0.024420,-0.006113,-0.041362,0.045987,0.003051,0.025262,-0.017258,-0.005575,-0.009320,-0.002335,0.013284,0.020240,0.008621,0.018747,0.006448,0.015626,-0.021991,-0.035641,-0.032441,0.041076,0.005107,0.006283,0.003581,-0.015700,0.011017,-0.025927,0.007209,-0.009422,-0.032358,0.025959,-0.005796,-0.012012,-0.037741,0.012490,-0.003095,0.052917,0.019762,-0.003915,23.777778,21.910311,76.0,0.0,0.894298,-0.172640,1.222222,3.189489,14.0,0.0,3.537019,11.325785,9.511111,14.282269,63.0,0.0,2.142648,4.039383

In [32]:
import gc

del df_train_final, df, df_ngrams, df_svd, df_pos, df_entities, df_deps, pos_df, ner_df, dep_df, pos_features, ner_features, dep_features

gc.collect()

0

In [ ]:
# import os
# from tqdm import tqdm

# glove_path = 'data/glove-840B-300d.txt'

# paragram_path = '/home/jack/github/kaggle/scoring/data/paragram-300-sl999.txt'

# wiki_news_path = 'data/wiki-news-1M-300d.vec'


# # Load embeddings

# embeddings = parallel_load_embeddings([glove_path, paragram_path, wiki_news_path])

# glove = embeddings["glove"]
# paragram = embeddings["paragram"]
# fasttext = embeddings["fasttext"]

In [ ]:
# train, oov_glove, oov_paragram, oov_fasttxt = spellcheck_and_correct_text(train, embeddings)

In [ ]:
# train.to_parquet('train_full_clean_process.parquet')

In [ ]:
train = clean_text(train)

train.head()

In [ ]:
def custom_train_validation_split(essays, test_size=0.2, random_state=56):
    
    """
    Custom function to perform train-validation split ensuring that
    the same prompt IDs are in both training and validation sets.

    Parameters:
    - summaries: DataFrame containing summaries and associated prompt_ids
    - prompts: DataFrame containing prompts and associated prompt_ids
    - test_size: Proportion of the dataset to be used as the validation set
    - random_state: Random seed for reproducibility

    Returns:
    - train_summaries: Training set containing summaries
    - validation_summaries: Validation set containing summaries
    - train_prompts: Training set containing prompts
    - validation_prompts: Validation set containing prompts
    """

    from sklearn.model_selection import train_test_split

    
    # Extract unique prompt IDs
    unique_essay_ids = essays['essay_id'].unique()

    # Split the unique prompt IDs into training and validation sets
    train_ids, validation_ids = train_test_split(unique_essay_ids, test_size=test_size, random_state=random_state)

    # Use these IDs to filter the original summaries and prompts DataFrames
    train_essays = essays[essays['essay_id'].isin(train_ids)]
    validation_essays = essays[essays['essay_id'].isin(validation_ids)]

    return train_essays, validation_essays

In [ ]:
train_essays, val_essays = custom_train_validation_split(train, test_size=0.25, random_state=42)

In [ ]:
train_essays.head()

In [ ]:
# import pandas as pd

# train_essays = pd.read_parquet('/home/jack/github/kaggle/scoring/train_essays.parquet')
# val_essays = pd.read_parquet('/home/jack/github/kaggle/scoring/validation_essays.parquet')

In [ ]:

train_essays.head()

In [ ]:
train_essays['score'].value_counts()

In [ ]:
drop_cols = [ 'full_text', 'clean_text' , 'lowered', 'min_word_length'] # , 'combined_dense_vector']   


train_df = train_essays.copy()
val_df = val_essays.copy()

train_df.drop(columns=drop_cols, inplace= True)
val_df.drop(columns=drop_cols, inplace= True)

In [ ]:
train_df.head()

In [ ]:
feature_cols = []

for col in train_df.columns:
    if (col != 'essay_id') and (col != 'score'):
        feature_cols.append(col)

In [ ]:
pd.set_option('display.max_columns', None)
feature_cols

In [ ]:
# save the order of the column names to a txt file

with open('feature_cols.txt', 'w') as f:
    for item in feature_cols:
        f.write("%s\n" % item)

In [ ]:
# # read in the feature columns

# with open('feature_cols.txt', 'r') as f:
#     feature_cols = f.read().splitlines()

In [ ]:
# !pip install scikit-learn==1.2.2

In [ ]:
import sklearn
print(sklearn.__version__)

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pickle
import numpy as np

# Extract labels from the training and validation datasets
train_labels = train_df['score']  # Extracts 'score' column as the label
val_labels = val_df['score']

# Extract features for scaling
train_features = train_df[feature_cols] # Subset with only feature columns
val_features = val_df[feature_cols]

# Initialize the scaler
scaler = MinMaxScaler()  # Using StandardScaler for scaling

# Fit the scaler to the training features
scaler.fit(train_features)  # This defines the transformation based on the training data

# Transform training and validation features
train_feats_scaled = scaler.transform(train_features)  # Transforms the training data
val_feats_scaled = scaler.transform(val_features)  # Transforms the validation data

# Reassign the scaled features to the original DataFrames, keeping the same column names
train_df[feature_cols] = train_feats_scaled  # Replace the original features with scaled ones
val_df[feature_cols] = val_feats_scaled

# Save the scaler for later use
with open('sklearn_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)  # Persist the scaler for future use or reference

In [ ]:
# Check if the file has been written correctly and is not empty
import os
scaler_path = 'sklearn_scaler.pkl'
if os.path.getsize(scaler_path) > 0:
    print(f"Scaler saved successfully in {scaler_path}.")
else:
    print(f"Failed to save scaler to {scaler_path}. File is empty.")

In [ ]:
# Check if the scaler is StandardScaler
if isinstance(scaler, StandardScaler):
    print("The scaler is a StandardScaler.")
elif isinstance(scaler, MinMaxScaler):
    print("The scaler is a MinMaxScaler.")
else:
    print("The scaler is neither StandardScaler nor MinMaxScaler.")

In [ ]:
# train_df = pca_dataframe(train_df)
# val_df = pca_dataframe(val_df)

In [ ]:
train_df.head()

In [ ]:
val_df.head()

In [ ]:
# train_df.to_parquet('train_df.parquet')
# val_df.to_parquet('val_df.parquet')

In [ ]:
import pandas as pd
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

df = train_df.copy()
# Downsample majority classes to 1,000 samples
target_samples = 1000
balanced_df = pd.DataFrame()

for class_label in df['score'].unique():
    class_subset = df[df['score'] == class_label]
    
    if len(class_subset) > target_samples:
        # Downsample to 1,000 samples for majority classes
        class_subset = resample(
            class_subset,
            replace=False,
            n_samples=target_samples,
            random_state=42
        )
    
    balanced_df = pd.concat([balanced_df, class_subset], axis=0)

# Now, let's apply SMOTE to balance the minority classes up to 1,000 samples
X = balanced_df.drop(columns = ['essay_id','score'], axis=1)
y = balanced_df['score']

# Create SMOTE instance to ensure all classes have 1,000 samples
smote = SMOTE(sampling_strategy={k: 1000 for k in y.unique()}, random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

# Create the resampled DataFrame
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['score'] = y_resampled

# Display the resampled class distribution to confirm the balancing
print("Resampled class distribution:")
print(df_resampled['score'].value_counts())

In [ ]:
UPSAMPLE = False

if UPSAMPLE:
    
    # Balance only the training DataFrame
    train_df = df_resampled.copy()

    
else:
    pass

print(train_df['score'].value_counts())
print(val_df['score'].value_counts())

In [ ]:
train_df.head()

In [ ]:
# To convert features and targets to NumPy arrays for ML use

if UPSAMPLE:
    train_features = train_df.drop(columns=['score'], axis=1).values
    train_labels = train_df['score'].values

    val_features = val_df.drop(columns=['essay_id','score'], axis=1).values
    val_labels = val_df['score'].values

else:
    
    train_features = train_df.drop(columns=['essay_id','score'], axis=1).values
    train_labels = train_df['score'].values

    val_features = val_df.drop(columns=['essay_id','score'], axis=1).values
    val_labels = val_df['score'].values


print("Features shape:", train_features.shape)
print("Target shape:", train_labels.shape)

print("Features shape:", val_features.shape)
print("Target shape:", val_labels.shape)



#####     Features shape: (3, 1389)

In [ ]:
from sklearn.metrics import make_scorer, cohen_kappa_score

def quadratic_weighted_kappa_scorer(y_true, y_pred):
    """
    Compute the Quadratic Weighted Kappa (QWK), also known as Cohen's kappa.
    
    Parameters:
    y_true : array-like of shape (n_samples,)
        True labels.
    y_pred : array-liimport keras_tuner
from sklearn import ensemble
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
from sklearn import model_selection

def build_model(hp):
  model_type = hp.Choice('model_type', ['random_forest', 'ridge'])
  if model_type == 'random_forest':
    model = ensemble.RandomForestClassifier(
        n_estimators=hp.Int('n_estimators', 10, 50, step=10),
        max_depth=hp.Int('max_depth', 3, 10))
  else:
    model = linear_model.RidgeClassifier(
        alpha=hp.Float('alpha', 1e-3, 1, sampling='log'))
  return model

tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=100),
    hypermodel=build_model,
    scoring=metrics.make_scorer(metrics.accuracy_score),
    cv=model_selection.StratifiedKFold(10),
    directory='.',
    project_name='my_project')ke of shape (n_samples,)
        Predicted labels.
    
    Returns:
    score : float
        Quadratic Weighted Kappa score.
    """
    return cohen_kappa_score(y_true, y_pred, weights='quadratic')

In [ ]:
# from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
# import keras_tuner as kt

# model_checkpoint = ModelCheckpoint('data/models/best_standard_model_epoch.keras', 
#                                    save_best_only=True, monitor='val_loss', mode='min')

# early_stopping = EarlyStopping(monitor='val_loss', patience=5, 
#                                restore_best_weights=True)

# call_backs = [model_checkpoint, early_stopping]

In [ ]:
import keras_tuner
from sklearn import ensemble, linear_model, model_selection, svm
from lightgbm import LGBMClassifier


def build_model(hp):
    """
    Builds a more comprehensive machine learning model based on hyperparameters for multiclass classification.
    
    Parameters:
    hp : HyperParameters
        Hyperparameters for tuning the model.
    
    Returns:
    model : An instance of a Scikit-learn model.
    """
    # Adding 'lightgbm' as a new model type
    model_type = hp.Choice('model_type', ['random_forest',  'gradient_boosting', 'lightgbm'])

    if model_type == 'random_forest':
        model = ensemble.RandomForestClassifier(
            n_estimators=hp.Int('n_estimators', 10, 100, step=10),
            max_depth=hp.Int('max_depth', 3, 20),
            min_samples_split=hp.Int('min_samples_split', 2, 20),
            min_samples_leaf=hp.Int('min_samples_leaf', 1, 10),
            criterion=hp.Choice('criterion', ['gini', 'entropy']),
            class_weight=hp.Choice('class_weight', ['balanced', 'balanced_subsample']),
            max_samples=hp.Float('max_samples', 0.1, 1.0, sampling='log')
        )



    elif model_type == 'gradient_boosting':
        model = ensemble.GradientBoostingClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            max_depth=hp.Int('max_depth', 3, 15),
            subsample=hp.Float('subsample', 0.5, 1.0, step=0.1)
        )

    # Adding LightGBM as a new model type
    elif model_type == 'lightgbm':
        model = LGBMClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            num_leaves=hp.Int('num_leaves', 31, 127, step=16),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            min_child_samples=hp.Int('min_child_samples', 10, 50, step=10),
            class_weight=hp.Choice('class_weight', ['balanced', 'balanced_sample']),
        )

    return model


# Defining the custom QWK scorer
qwk_scorer = make_scorer(quadratic_weighted_kappa_scorer)

# Tuner configuration
tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=30),
    hypermodel=build_model,
    scoring=qwk_scorer,
    cv=model_selection.StratifiedKFold(3),
    directory='.',
    project_name='data/sklearn',
    overwrite=True)

# Starting the search
tuner.search(train_features, train_labels)      # class_weight=class_weights_dict,

# Retrieving the best model
best_model = tuner.get_best_models(num_models=1)[0]

In [ ]:
best_model.fit(train_features, train_labels)

In [ ]:
predictions = best_model.predict(val_features)

y_true = val_labels

# predictions = target_scaler.inverse_transform(predictions.reshape(-1, 1)).flatten()

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix

confusion_matrix(y_true, predictions)

In [ ]:
# classification report

from sklearn.metrics import classification_report

print(classification_report(y_true, predictions))

In [ ]:
# cohens kappa

from sklearn.metrics import cohen_kappa_score

cohen = cohen_kappa_score(y_true, predictions)

In [ ]:
# quadratic weighted kappa

from sklearn.metrics import cohen_kappa_score

quadratic = cohen_kappa_score(y_true, predictions, weights='quadratic')

print(f"Cohen's Kappa: {cohen}")
print(f"Quadratic Weighted Kappa: {quadratic}")

In [ ]:
from joblib import dump, load

if UPSAMPLE:
    
    dump(best_model, 'upsampled_random_forest.joblib')

else:
    
    dump(best_model, 'standard_random_forest.joblib')

In [ ]:
# forest_model = load('random_forest.joblib')

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Generate and display the confusion matrix for the test predictions
cm = confusion_matrix(y_true, predictions, labels=best_model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# Identifying misclassified samples
misclassified_indices = (y_true != predictions)
misclassified_samples = val_features[misclassified_indices]
misclassified_true_labels = y_true[misclassified_indices]
misclassified_predicted_labels = predictions[misclassified_indices]

In [ ]:
# Examining features of misclassified samples
import pandas as pd
misclassified_df = pd.DataFrame(misclassified_samples)
misclassified_df['True_Label'] = misclassified_true_labels
misclassified_df['Predicted_Label'] = misclassified_predicted_labels
# Display the first few rows of the misclassified samples
misclassified_df.head()

In [ ]:
# # Feature importance from LightGBM
# feature_importance = best_model.feature_importance(importance_type='gain')
# feature_names = val_features.columns
# feature_importance_df = pd.DataFrame({
#     'Feature': feature_names,
#     'Importance': feature_importance
# })
# # Sort features by importance
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
# print(feature_importance_df)

In [ ]:
# Checking class distribution in the true labels
label_counts = pd.Series(y_true).value_counts()
print(label_counts)

In [ ]:
# from sklearn.model_selection import GridSearchCV
# # Define the hyperparameters to tune
# param_grid = {
#     'learning_rate': [0.01, 0.05, 0.1],
#     'num_leaves': [31, 62, 128],
#     'n_estimators': [50, 100, 200]
# }
# grid_search = GridSearchCV(best_model, param_grid, scoring='', cv=5)
# grid_search.fit(val_features, val_labels)
# print("Best parameters:", grid_search.best_params_)

In [ ]:
# Check LightGBM version
import lightgbm as lgb
print(lgb.__version__)

In [ ]:
# # Ensure the model is fitted
# if not hasattr(best_model, 'feature_importance_'):
#     best_model.fit(val_features, val_labels)  # Train or re-train the model

# # Retrieve feature importance
# feature_importance = best_model.feature_importance_  # Underscore at the end
# feature_names = val_features.columns

# # Create DataFrame for feature importance
# feature_importance_df = pd.DataFrame({
#     'Feature': feature_names,
#     'Importance': feature_importance
# })
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# print(feature_importance_df)

In [ ]:
# Assuming `df` is the original DataFrame and `predictions` is a list/array of predicted labels
# If there's a subset used for predictions, ensure it aligns with the DataFrame
val_df['Predicted_Label'] = predictions

In [ ]:
print(len(val_features), len(val_df), len(predictions))

In [ ]:
val_df.tail()

In [ ]:
# merge 'clean_text' column back with val df 

text = val_essays[['essay_id', 'clean_text']]

val_df = val_df.merge(text, on = 'essay_id')

val_df.head()

In [ ]:
# Assuming `df` has the original labels in a column named 'True_Label'
misclassified_samples = val_df[val_df['score'] != val_df['Predicted_Label']]

# Display misclassified samples
print(misclassified_samples[['score', 'Predicted_Label', 'clean_text']][:15])

In [ ]:
# Example: Analyze original text of misclassified samples
misclassified_text = misclassified_samples['clean_text']  # Assuming 'Text' is the original text data
print(misclassified_text.head())

In [ ]:
# load tf model
len(misclassified_text)

In [ ]:
# add full mis classified text to a txt file seperated by  '---' and a new line after every 10 words in each essay

with open('misclassified_text.txt', 'w') as f:
    for essay in misclassified_text:
        f.write("%s\n" % essay)
        f.write('---\n')

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Assuming `df` has your model's features and labels
X = val_df[feature_cols]
y = val_df['score'] == val_df['Predicted_Label']

# Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit a RandomForest to see feature importances
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

# Get the most important features
importances = clf.feature_importances_
features = feature_cols
important_features = {features[i]: importances[i] for i in range(len(features))}

# convert to percentages rounded and sort

important_features = {k: round(v, 5) for k, v in important_features.items()}

print("Most predictive features of misclassification:", sorted(important_features.items(), key=lambda x: x[1], reverse=True))

In [ ]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt

# # Assume val_df and feature_cols are already defined

# # Set the option to display all rows
# pd.set_option('display.max_rows', None)

# # Selecting the features and the target
# X = val_df[feature_cols]
# y = val_df['score']

# # Calculate the correlation between features and the target
# corr = X.corrwith(y)

# # Sort the correlation values
# corr = corr.sort_values(ascending=False)

# # Convert the Series to a DataFrame for heatmap compatibility
# corr_df = pd.DataFrame(corr, columns=['Correlation'])

# corr_df

In [ ]:
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import classification_report

# # Define the feature set with and without the specific features
# X_with = val_df[feature_cols]  # including all features
# X_without = val_df.drop(columns=['misspelling_count', 'sentence_length'], axis=1) # excluding problematic features

# y = val_df['score']  # target variable

# # Split the data
# X_train_with, X_test_with, y_train, y_test = train_test_split(X_with, y, test_size=0.3, random_state=42)
# X_train_without, X_test_without, _ , _ = train_test_split(X_without, y, test_size=0.3, random_state=42)

# # Train models
# model_with = RandomForestClassifier().fit(X_train_with, y_train)
# model_without = RandomForestClassifier().fit(X_train_without, y_train)

# # Evaluate models
# print("With features:")
# print(classification_report(y_test, model_with.predict(X_test_with)))

# print("Without features:")
# print(classification_report(y_test, model_without.predict(X_test_without)))