In [1]:
# ! python -m pip install --no-index --find-links=/kaggle/usr/lib/pip_install_permanent/my_packages -r /kaggle/usr/lib/pip_install_permanent/requirements.txt

In [2]:
# import os

# os.environ['PACKAGE_DIR'] = '/kaggle/usr/lib/pip_install_permanent'

In [3]:
from helper_func import *
# # import helper_functions as hf
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import string
# from spellchecker import SpellChecker
# from textblob import TextBlob
# from multiprocessing import Pool
# from tqdm import tqdm
# import numpy as np
# import pandas as pd
# # Preprocessing
# from nltk.tokenize import word_tokenize, sent_tokenize
# import operator
# from spellchecker import SpellChecker
# from tqdm import tqdm  # Import tqdm
# import re
# import inflect
# from wordsegment import load, segment
# from nltk.corpus import words
# word_list = set(words.words())
# from spellchecker import SpellChecker

# from tqdm.contrib.concurrent import process_map  # If this import fails, you might need to update tqdm

# import multiprocessing
 
# # Import Packages
# # import shutup; shutup.please()

# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import tensorflow as tf
# import keras_tuner as kt
# import seaborn as sns

# from nltk.corpus import stopwords, wordnet
# from nltk.tokenize import word_tokenize, sent_tokenize
# from nltk import pos_tag, ne_chunk
# from textblob import TextBlob

# from textstat import flesch_reading_ease, smog_index

# import spacy
# from collections import Counter
# from gensim import corpora, models
# import pyLDAvis.gensim as gen
# import pyLDAvis
# import re

# # Machine Learning & Data Preprocessing

# from sklearn.preprocessing import StandardScaler, MinMaxScaler
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

# # Deep Learning

# from tensorflow.keras import layers
# from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.sequence import pad_sequences

# # Gensim
# # from gensim.models import Word2Vec, KeyedVectors

# # Progress bar
# from tqdm import tqdm

# # Keras Tuner
# from keras_tuner.tuners import RandomSearch

# # # Setting logging levels and environment variables
# # tf.get_logger().setLevel(logging.ERROR)
# # os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# from textstat import flesch_reading_ease
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import string
# from spellchecker import SpellChecker
# from textblob import TextBlob
# from multiprocessing import Pool
# from tqdm import tqdm
# import numpy as np
# import pandas as pd
# # Preprocessing
# from nltk.tokenize import word_tokenize, sent_tokenize
# import operator
# from spellchecker import SpellChecker
# from tqdm import tqdm  # Import tqdm
# import re
# import inflect
# from wordsegment import load, segment
# from nltk.corpus import words
# word_list = set(words.words())
# print('Packages Instaled......')

/home/jack/envs/scoring/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package punkt to /home/jack/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/jack/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [4]:
laptop = False

if laptop:
    csv_path = '/home/laptop/github/kaggle/scoring/xlnet_hash.csv'

if not laptop:
    csv_path = '/home/jack/github/kaggle/scoring/xlnet_hash.csv'

In [5]:
pd.set_option('display.max_columns', None)

deberta_full = pd.read_csv(csv_path)
deberta_full.drop(columns=['score', 'labels'], inplace=True)
deberta_full.head()

,essay_id,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199
0,000fe60,i am a scientist at nasa that is discussing th...,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489,0.071429,0.023810,0.023810,0.000000,0.000000,0.119048,0.000000,0.02381,0.000000,0.047619,0.023810,0.023810,0.023810,0.0,0.119048,0.023810,0.02381,0.000000,0.119048,0.023810,0.000000,0.000000,0.000000,0.023810,0.000000,0.0,0.000000,0.023810,0.000000,0.047619,0.000000,0.000000,0.047619,0.071429,0.047619,0.071429,0.000000,0.142857,0.000000,0.000000,0.190476,0.000000,0.000000,0.023810,0.000000,0.190476,0.047619,0.000000,0.000000,0.000000,0.000000,0.095238,0.000000,0.000000,0.000000,0.095238,0.071429,0.047619,0.000000,0.023810,0.023810,0.119048,0.047619,0.000000,0.000000,0.000000,0.0,0.000000,0.023810,0.023810,0.0,0.000000,0.000000,0.023810,0.023810,0.071429,0.047619,0.285714,0.000000,0.000000,0.000000,0.047619,0.000000,0.000000,0.00000,0.023810,0.119048,0.047619,0.023810,0.023810,0.071429,0.214286,0.023810,0.095238,0.000000,0.261905,0.000000,0.047619,0.023810,0.071429,0.000000,0.02381,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.023810,0.071429,0.285714,0.023810,0.000000,0.000000,0.071429,0.000000,0.000000,0.190476,0.023810,0.000000,0.023810,0.000000,0.023810,0.238095,0.000000,0.047619,0.000000,0.000000,0.000000,0.000000,0.071429,0.000000,0.000000,0.000000,0.000000,0.142857,0.0,0.000000,0.023810,0.071429,0.0,0.023810,0.047619,0.000000,0.095238,0.000000,0.0,0.02381,0.000000,0.000000,0.000000,0.047619,0.190476,0.023810,0.142857,0.000000,0.071429,0.214286,0.023810,0.047619,0.000000,0.000000,0.023810,0.000000,0.000000,0.047619,0.0,0.000000,0.047619,0.000000,0.02381,0.00000,0.000000,0.000000,0.071429,0.000000,0.000000,0.02381,0.000000,0.000000,0.071429,0.142857,0.0,0.047619,0.023810,0.047619,0.047619,0.285714,0.095238,0.000000,0.119048,0.000000,0.000000,0.000000,0.023810,0.190476,0.071429,0.000000,0.02381
1,001ab80,people always wish they had the same technolog...,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192,0.014565,0.000000,0.058259,0.000000,0.014565,0.058259,0.189343,0.00000,0.014565,0.029130,0.014565,0.058259,0.000000,0.0,0.029130,0.014565,0.00000,0.014565,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.0,0.000000,0.029130,0.000000,0.160213,0.014565,0.029130,0.000000,0.029130,0.058259,0.043694,0.000000,0.145648,0.014565,0.029130,0.087389,0.029130,0.116519,0.000000,0.014565,0.116519,0.029130,0.000000,0.014565,0.043694,0.014565,0.014565,0.043694,0.029130,0.000000,0.043694,0.000000,0.014565,0.000000,0.000000,0.029130,0.131083,0.058259,0.014565,0.014565,0.000000,0.0,0.000000,0.014565,0.000000,0.0,0.000000,0.014565,0.029130,0.014565,0.072824,0.058259,0.145648,0.043694,0.029130,0.145648,0.000000,0.029130,0.000000,0.02913,0.029130,0.160213,0.029130,0.000000,0.131083,0.043694,0.305861,0.087389,0.087389,0.000000,0.189343,0.000000,0.014565,0.145648,0.014565,0.014565,0.00000,0.0,0.145648,0.000000,0.000000,0.000000,0.0,0.043694,0.000000,0.087389,0.160213,0.000000,0.014565,0.000000,0.029130,0.000000,0.014565,0.072824,0.029130,0.000000,0.029130,0.000000,0.014565,0.043694,0.014565,0.072824,0.029130,0.014565,0.000000,0.014565,0.087389,0.000000,0.101954,0.145648,0.116519,0.116519,0.0,0.014565,0.000000,0.000000,0.0,0.014565,0.014565,0.014565,0.160213,0.014565,0.0,0.00000,0.029130,0.000000,0.014565,0.087389,0.043694,0.000000,0.014565,0.043694,0.029130,0.407815,0.029130,0.000000,0.058259,0.014565,0.072824,0.000000,0.043694,0.029130,0.0,0.014565,0.058259,0.000000,0.00000,0.02913,0.000000,0.000000,0.000000,0.087389,0.014565,0.00000,0.000000,0.029130,0.029130,0.189343,0.0,0.101954,0.043694,0.087389,0.087389,0.189343,0.116519,0.029130,0.043694,0.014565,0.014565,0.000000,0.014565,0.262167,0.014565,0.000000,0.00000
2,002ba53,dear state senator this is a letter to argue i...,0.059430,0.691130,0.233244,0.014120,0.001189,0.000887,0.132971,0.113607,0.266656,0.112359,0.161093,0.213313,0.047637,0.000000,0.079395,0.015879,0.000000,0.000000,0.015879,0.00000,0.000000,0.000000,0.015879,0.079395,0.015879,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063516,0.000000,0.031758,0.0,0.000000,0.015879,0.000000,0.031758,0.031758,0.000000,0.000000,0.000000,0.063516,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.031758,0.031758,0.079395,0.000000,0.206427,0.015879,0.000000,0.000000,0.015879,0.095274,0.095274,0.047637,0.015879,0.015879,0.000000,0.031758,0.015879,0.015879,0.000000,0.111153,0.015879,0.079395,0.000000,0.0,0.000000,0.000000,0.015879,0.0,0.000000,0.015879,0.015879,0.000000,0.047637,0.031758,0.238185,0.015879,0.000000,0.031758,0.000000,0.000000,0.015879,0.00000,0.000000,0.063516,0.285822,0.031758,0.238185,0.063516,0.079395,0.047637,0.031758,0.000000,0.127032,0.142911,0.031758,0.047637,0.127032,0.000000,0.00000,0.0,0.000000,0.031758,0.000000,0.031758,0.0,0.015879,0.000000,0.063516,0.031758,0.015879,0.000000,0.031758,0.000000,0.000000,0.000000,0.127032,0.000000,0.000000,0.000000,0.047637,0.015879,0.015879,0.047637,0.000000,0.000000,0.000000,0.000000,0.015879,0.031758,0.031758,0.000000,0.047637,0.000000,0.031758,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.015879,0.0,0.00000,0.015879,0.063516,0.000000,0.015879,0.015879,0.015879,0.000000,0.015879,0.000000,0.619282,0.000000,0.000000,0.079395,0.015879,0.031758,0.047637,0.000000,0.063516,0.0,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.015879,0.000000,0.015879,0.000000,0.00000,0.031758,0.000000,0.000000,0.031758,0.0,0.015879,0.031758,0.015879,0.063516,0.095274,0.031758,0.000000,0.031758,0.000000,0.000000,0.000000,0.000000,0.381096,0.000000,0.031758,0.00000
3,0033037,the posibilty of a face reconizing computer wo...,0.110127,0.875540,0.012530,0.000799,0.000427,0.000577,0.133904,0.109733,0.257915,0.112806,0.166446,0.219196,0.000000,0.000000,0.000000,0.000000,0.000000,0.039073,0.000000,0.00000,0.000000,0.078146,0.156293,0.117220,0.000000,0.0,0.039073,0.000000,0.00000,0.000000,0.000000,0.000000,0.039073,0.039073,0.000000,0.000000,0.000000,0.0,0.039073,0.000000,0.039073,0.000000,0.000000,0.039073,0.078146,0.000000,0.039073,0.000000,0.039073,0.039073,0.039073,0.039073,0.039073,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.000000,0.000000,0.078146,0.000000,0.039073,0.039073,0.000000,0.000000,0.000000,0.000000,0.078146,0.000000,0.039073,0.000000,0.039073,0.039073,0.000000,0.156293,0.000000,0.0,0.078146,0.000000,0.000000,0.0,0.078146,0.000000,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.039073,0.000000,0.000000,0.000000,0.195366,0.00000,0.039073,0.156293,0.039073,0.000000,0.273513,0.078146,0.117220,0.000000,0.000000,0.000000,0.156293,0.078146,0.000000,0.039073,0.000000,0.039073,0.00000,0.0,0.117220,0.039073,0.000000,0.000000,0.0,0.000000,0.000000,0.117220,0.078146,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.039073,0.000000,0.000000,0.000000,0.039073,0.039073,0.000000,0.156293,0.000000,0.039073,0.000000,0.000000,0.078146,0.078146,0.078146,0.000000,0.156293,0.000000,0.0,0.000000,0.078146,0.156293,0.0,0.000000,0.000000,0.000000,0.039073,0.039073,0.0,0.00000,0.156293,0.000000,0.039073,0.000000,0.000000,0.078146,0.156293,0.000000,0.000000,0.468879,0.078146,0.000000,0.039073,0.039073,0.195366,0.000000,0.000000,0.039073,0.0,0.000000,0.000000,0.039073,0.00000,0.00000,0.000000,0.000000,0.234439,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.117220,0.000000,0.000000,0.156293,0.000000,0.000000,0.039073,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.000000,0.00000
4,0033bf4,what is the seagoing cowboys progam it was to ...,0.004650,0.469768,0.515730,0.009045,0.000419,0.000389,0.133583,0.111408,0.263863,0.108937,0.168764,0.213444,0.000000,0.019364,0.038727,0.019364,0.000000,0.019364,0.019364,0.00000,0.000000,0.116182,0.000000,0.038727,0.000000,0.0,0.038727,0.000000,0.00000,0.038727,0.019364,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.058091,0.000000,0.000000,0.000000,0.038727,0.038727,0.019364,0.019364,0.019364,0.058091,0.000000,0.058091,0.000000,0.019364,0.000000,0.000000,0.213001,0.000000,0.096819,0.000000,0.019364,0.000000,0.000000,0.019364,0.000000,0.000000,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.116182,0.019364,0.000000,0.019364,0.077455,0.0,0.000000,0.116182,0.077455,0.0,0.000000,0.019364,0.000000,0.019364,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.000000,0.038727,0.000000,0.00000,0.000000,0.038727,0.038727,0.000000,0.135546,0.000000,0.251728,0.000000,0.154910,0.038727,0.135546,0.000000,0.000000,0.116182,0.058091,0.000000,0.00000,0.0,0.000000,0.000000,0.019364,0.000000,0.0,0.000000,0.135546,0.077455,0.058091,0.000000,0.077455,0.000000,0.154910,0.019364,0.000000,0.116182,0.058091,0.019364,0.096819,0.000000,0.096819,0.000000,0.000000,0.038727,0.038727,0.038727,0.077455,0.019364,0.000000,0.000000,0.038727,0.019364,0.077455,0.077455,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.116182,0.019364,0.0,0.00000,0.058091,0.000000,0.000000,0.000000,0.058091,0.000000,0.000000,0.000000,0.077455,0.426002,0.058091,0.154910,0.038727,0.000000,0.077455,0.116182,0.019364,0.058091,0.0,0.000000,0.038727,0.000000,0.00000,0.00000,0.019364,0.000000,0.174273,0.019364,0.000000,0.00000,0.019364,0.077455,0.000000,0.019364,0.0,0.213001,0.077455,0.019364,0.038727,0.445365,0.000000,0.019364,0.019364,0.000000,0.019364,0.019364,0.000000,0.096819,0.193637,0.000000,0.00000

In [6]:
# drop columns with hash in the name

hash_cols = [col for col in deberta_full.columns if 'hash' in col]

deberta_full.drop(columns=hash_cols, inplace=True)

deberta_full.head()

,essay_id,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5
0,000fe60,i am a scientist at nasa that is discussing th...,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489
1,001ab80,people always wish they had the same technolog...,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192
2,002ba53,dear state senator this is a letter to argue i...,0.059430,0.691130,0.233244,0.014120,0.001189,0.000887,0.132971,0.113607,0.266656,0.112359,0.161093,0.213313
3,0033037,the posibilty of a face reconizing computer wo...,0.110127,0.875540,0.012530,0.000799,0.000427,0.000577,0.133904,0.109733,0.257915,0.112806,0.166446,0.219196
4,0033bf4,what is the seagoing cowboys progam it was to ...,0.004650,0.469768,0.515730,0.009045,0.000419,0.000389,0.133583,0.111408,0.263863,0.108937,0.168764,0.213444

In [7]:
import pandas as pd
from sklearn.feature_extraction.text import HashingVectorizer


# Initialize the HashingVectorizer
n_features = 500  # Number of columns in the hashed vector
hashing_vectorizer = HashingVectorizer(n_features=n_features, alternate_sign=False)

# Transform the text column into hash vector features
hashed_features = hashing_vectorizer.transform(deberta_full['clean_text'])

# Convert the hashed features to a dense representation for easier manipulation
hashed_features_dense = hashed_features.todense()

# Create new column names based on the number of features
hashed_columns = [f'hash_{i}' for i in range(n_features)]

# Convert dense representation to a dataframe
hashed_df = pd.DataFrame(hashed_features_dense, columns=hashed_columns)

# Concatenate the original dataframe with the hashed dataframe

deberta_full = pd.concat([deberta_full, hashed_df], axis=1)

In [8]:
if laptop:
    csv_path = '/home/laptop/github/kaggle/scoring/data/train.csv'

if not laptop:
    csv_path = '/home/jack/github/kaggle/scoring/data/train.csv'

In [9]:
train = pd.read_csv(csv_path)

In [10]:
train = clean_text(train)

train.head()

Starting text cleaning process.

In [ ]:
print(deberta_full.shape, train.shape)

In [ ]:
# Combine train and deberta_full on essay_id

train = train.merge(deberta_full, on='essay_id')

train.head()

In [ ]:
df = train.copy()

In [ ]:
import pandas as pd
import dill
import spacy
import re
from collections import Counter
from sklearn.decomposition import LatentDirichletAllocation
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sentence_transformers import SentenceTransformer
import nltk
from nltk.corpus import stopwords
from spellchecker import SpellChecker
from textstat import flesch_reading_ease, flesch_kincaid_grade, gunning_fog, smog_index, dale_chall_readability_score
import textstat

# Load spaCy model
nlp = spacy.load("en_core_web_sm")
stop_words = set(stopwords.words('english'))
sentiment_analyzer = SentimentIntensityAnalyzer()
spell = SpellChecker()
bert_model = SentenceTransformer('all-MiniLM-L6-v2')

# Initialize a CountVectorizer with n-gram range from 1 to 3 (unigrams to trigrams)
vectorizer = CountVectorizer(ngram_range=(1, 3), max_features=1000, stop_words='english')

# Function to clean and preprocess text
def clean_text(text):
    text = re.sub(r'\W', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = text.lower()
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text

# Function to count POS tags
def pos_counts(text):
    doc = nlp(text)
    pos_counts = doc.count_by(spacy.attrs.POS)
    return {f'pos_{doc.vocab.strings[pos_id]}': count for pos_id, count in pos_counts.items()}

# Function to count Named Entities
def named_entities(text):
    doc = nlp(text)
    entities = {}
    for ent in doc.ents:
        entities[ent.label_] = entities.get(ent.label_, 0) + 1
    return {f'ner_{label}': count for label, count in entities.items()}

# Function to count Dependency Tags
def dependency_tags(text):
    doc = nlp(text)
    dep_counts = doc.count_by(spacy.attrs.DEP)
    return {f'dep_{doc.vocab.strings[dep_id]}': count for dep_id, count in dep_counts.items()}

# Function to calculate advanced linguistic features
def compute_linguistic_features(text):
    doc = nlp(text)

    # Verb Tense Consistency
    tenses = [token.tag_ for token in doc if token.pos_ == "VERB"]
    tense_counts = Counter(tenses)
    most_common_tense = tense_counts.most_common(1)[0][0] if tense_counts else None
    verb_tense_consistency = tense_counts[most_common_tense] / len(tenses) if tenses else 0

    # Passive Voice Usage
    passive_count = sum(1 for token in doc if token.dep_ == "nsubjpass")
    passive_voice_usage = passive_count / len([token for token in doc if token.pos_ == "VERB"]) if doc else 0

    # Modal Verb Usage
    modal_verbs = {"can", "could", "will", "would", "shall", "should", "may", "might", "must"}
    modal_count = sum(1 for token in doc if token.lemma_ in modal_verbs)
    modal_verb_usage = modal_count / len(doc) if doc else 0

    # Lexical Diversity
    lexical_diversity = len(set(doc)) / len(doc) if doc else 0

    # Readability Measures using textstat
    dale_chall_readability = textstat.dale_chall_readability_score(text)
    automated_readability_index = textstat.automated_readability_index(text)
    coleman_liau_index = textstat.coleman_liau_index(text)

    # Conjunction Usage
    conjunction_count = sum(1 for token in doc if token.pos_ in {"CCONJ", "SCONJ"})

    # Clause Density
    clause_count = sum(1 for token in doc if token.dep_ in {"csubj", "advcl", "ccomp", "xcomp"})
    clause_density = clause_count / max(len([token for token in doc if token.dep_ in {"ROOT", "nsubj"}]), 1)

    return {
        "verb_tense_consistency": verb_tense_consistency,
        "passive_voice_usage": passive_voice_usage,
        "modal_verb_usage": modal_verb_usage,
        "lexical_diversity": lexical_diversity,
        "dale_chall_readability": dale_chall_readability,
        "automated_readability_index": automated_readability_index,
        "coleman_liau_index": coleman_liau_index,
        "conjunction_usage": conjunction_count,
        "clause_density": clause_density
    }

# Function to calculate sentiment features
def compute_sentiment_features(text):
    sentiment_scores = sentiment_analyzer.polarity_scores(text)
    return {
        "vader_compound": sentiment_scores["compound"],
        "vader_positive": sentiment_scores["pos"],
        "vader_negative": sentiment_scores["neg"],
        "vader_neutral": sentiment_scores["neu"]
    }

# Extract BERT embeddings
def extract_bert_embedding(text):
    embedding = bert_model.encode([text])[0]
    return {f'bert_dim_{i}': value for i, value in enumerate(embedding)}

# Extract topic distribution features using LDA
def extract_topic_features(text, lda_model, vectorizer):
    text_vector = vectorizer.transform([text])
    topic_distribution = lda_model.transform(text_vector)[0]
    return {f'topic_{i}': prob for i, prob in enumerate(topic_distribution)}

# Function to extract text length features
def extract_text_length_features(text):
    words = text.split()
    sentences = re.split(r'[.!?]', text)
    return {
        "char_count": len(text),
        "word_count": len(words),
        "sentence_count": len(sentences),
        "avg_word_length": np.mean([len(word) for word in words]) if words else 0,
        "avg_sentence_length": np.mean([len(sentence.split()) for sentence in sentences]) if sentences else 0
    }

# Function to extract spelling and grammar errors
def extract_spelling_grammar_errors(text):
    misspelled = spell.unknown(text.split())
    return {
        "spelling_errors": len(misspelled),
        "grammar_errors": sum(1 for token in nlp(text) if token.dep_ == "pcomp") # Placeholder for grammar errors
    }

# Function to calculate advanced readability scores
def compute_advanced_readability_scores(text):
    return {
        "linsear_write_formula": textstat.linsear_write_formula(text),
        "ari_score": textstat.automated_readability_index(text),
    }

# Apply POS, NER, Dependency counts and linguistic features to data
def apply_feature_extraction(df, lda_model, vectorizer):
    df_pos = df['full_text'].apply(pos_counts).apply(pd.Series).fillna(0)
    df_entities = df['full_text'].apply(named_entities).apply(pd.Series).fillna(0)
    df_deps = df['full_text'].apply(dependency_tags).apply(pd.Series).fillna(0)
    df_linguistic = df['full_text'].apply(compute_linguistic_features).apply(pd.Series)
    df_sentiment = df['full_text'].apply(compute_sentiment_features).apply(pd.Series)
    df_bert = df['full_text'].apply(extract_bert_embedding).apply(pd.Series)
    df_topics = df['full_text'].apply(lambda x: extract_topic_features(x, lda_model, vectorizer)).apply(pd.Series)
    df_length = df['full_text'].apply(extract_text_length_features).apply(pd.Series)
    df_spelling_grammar = df['full_text'].apply(extract_spelling_grammar_errors).apply(pd.Series)
    df_readability = df['full_text'].apply(compute_advanced_readability_scores).apply(pd.Series)

    return pd.concat([df.reset_index(drop=True), df_pos.reset_index(drop=True), 
                      df_entities.reset_index(drop=True), df_deps.reset_index(drop=True), 
                      df_linguistic.reset_index(drop=True), df_sentiment.reset_index(drop=True),
                      df_bert.reset_index(drop=True), df_topics.reset_index(drop=True),
                      df_length.reset_index(drop=True), df_spelling_grammar.reset_index(drop=True),
                      df_readability.reset_index(drop=True)], axis=1)

# Example usage:

# Train LDA topic model for topic distribution features
tf_vectorizer = TfidfVectorizer(max_features=1000, stop_words='english')
tf = tf_vectorizer.fit_transform(df['full_text'])
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_model.fit(tf)

# Apply feature extraction
df_train_features = apply_feature_extraction(df, lda_model, tf_vectorizer)

# Initialize a CountVectorizer for n-grams (1-3 grams)
X_ngrams_train = vectorizer.fit_transform(df['full_text'])
df_ngrams_train = pd.DataFrame(X_ngrams_train.toarray(), columns=vectorizer.get_feature_names_out())

# Save the vectorizer
with open('/home/jack/github/kaggle/scoring/model_data/vectorizer.pkl', 'wb') as f:
    dill.dump(vectorizer, f)

# TF-IDF Features
tfidf_vectorizer = TfidfVectorizer(max_features=50)
tfidf_features_train = tfidf_vectorizer.fit_transform(df['full_text']).toarray()
df_tfidf_train = pd.DataFrame(tfidf_features_train, columns=[f"tfidf_{i}" for i in range(tfidf_features_train.shape[1])])

# Save the TF-IDF vectorizer
with open('/home/jack/github/kaggle/scoring/model_data/tfidf_vectorizer.pkl', 'wb') as f:
    dill.dump(tfidf_vectorizer, f)

# Combine all features
df_train_combined = pd.concat([df_train_features.reset_index(drop=True), df_ngrams_train.reset_index(drop=True), 
                               df_tfidf_train.reset_index(drop=True)], axis=1)

In [ ]:
# from sentence_transformers import SentenceTransformer
# model = SentenceTransformer('all-MiniLM-L6-v2')
# model.save('all-MiniLM-L6-v2')

In [ ]:
df = df_train_combined.copy()

In [ ]:
import spacy
import numpy as np
import pandas as pd
from gensim.corpora import Dictionary
from gensim.models import LdaModel
from gensim.models.coherencemodel import CoherenceModel
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sentence_transformers import SentenceTransformer
import nltk
from nltk.corpus import stopwords
from spellchecker import SpellChecker
import textstat

# Load spaCy model for text processing
nlp = spacy.load('en_core_web_sm')
stop_words = set(stopwords.words('english'))
sentiment_analyzer = SentimentIntensityAnalyzer()
bert_model = SentenceTransformer('all-MiniLM-L6-v2')
spell = SpellChecker()

# Custom syntactic complexity function
def compute_syntactic_complexity(doc):
    parsed = nlp(doc)
    # Ensure that some logic sets 'yngve' scores; here we're setting them to a default value for illustration
    for token in parsed:
        token._.yngve = token.i  # Example: set yngve score to token index, replace this with actual computation
    yngve_scores = [token._.yngve for token in parsed]
    dependency_distances = [abs(token.head.i - token.i) for token in parsed]
    return np.mean(yngve_scores), np.mean(dependency_distances)

# Discourse markers
discourse_markers = [
    "However", "Nevertheless", "On the other hand", "Conversely", "Though", 
    "Although", "Yet", "But", "And", "Also", "Furthermore", "Moreover", "Plus", 
    "Additionally", "In addition", "Therefore", "Thus", "Hence", "Consequently", 
    "As a result", "So", "Because", "Due to", "As a consequence", "That is to say", 
    "In other words", "To clarify", "Namely", "Simply put", "This means", 
    "For example", "For instance", "Such as", "Like", "Then", "Next", "After", 
    "Afterwards", "Subsequently", "Previously", "First", "Second", "Third", 
    "Finally", "Meanwhile", "In summary", "To sum up", "In conclusion", "Overall", 
    "To conclude", "In short", "Indeed", "In fact", "Certainly", "Definitely", 
    "Obviously", "Clearly", "If", "Unless", "Provided that", "In case", 
    "Fortunately", "Unfortunately", "Interestingly", "Surprisingly", "Importantly", 
    "Similarly", "Likewise", "Equally"
]

def count_discourse_markers(doc):
    words = doc.split()
    return sum(word in discourse_markers for word in words)

# Preprocessing function
def preprocess(text):
    doc = nlp(text)
    return [token.lemma_ for token in doc if not token.is_stop and not token.is_punct and len(token) > 2]

# Assuming df is your DataFrame and 'full_text' is the column with essays
df['processed_docs'] = df['full_text'].apply(preprocess)

dictionary = Dictionary(df['processed_docs'])
corpus = [dictionary.doc2bow(doc) for doc in df['processed_docs']]

lda_model = LdaModel(corpus=corpus, num_topics=10, id2word=dictionary, passes=10, random_state=42)

def document_topics(bow):
    return lda_model.get_document_topics(bow, minimum_probability=0.0)

df['topics'] = [document_topics(bow) for bow in corpus]

# Compute global coherence
coherence_model_lda = CoherenceModel(model=lda_model, texts=df['processed_docs'].tolist(), dictionary=dictionary, coherence='c_v')
global_coherence = coherence_model_lda.get_coherence()
df['global_coherence'] = global_coherence

# Compute diversity for each document
def calculate_diversity(topics):
    unique_terms = set()
    for topic_id, prob in topics:
        unique_terms.update([term for term, _ in lda_model.show_topic(topic_id)])
    return len(unique_terms) / len(topics) if topics else 0

df['topic_diversity'] = df['topics'].apply(calculate_diversity)

# Store main topic per document
df['main_topic'] = df['topics'].apply(lambda x: sorted(x, key=lambda y: y[1], reverse=True)[0][0])

# Expand topic proportions
def expand_topics(topics, num_topics=10):
    topic_proportions = [0] * num_topics
    for topic, proportion in topics:
        topic_proportions[topic] = proportion
    return topic_proportions

topic_features = df['topics'].apply(lambda x: expand_topics(x, num_topics=10))
topics_df = pd.DataFrame(topic_features.tolist(), columns=[f'topic_{i}' for i in range(10)])

df = pd.concat([df.reset_index(drop=True), topics_df.reset_index(drop=True)], axis=1)

# Add topic probabilities
num_topics = 10
for i in range(num_topics):
    df[f'topic_prob_{i}'] = 0.0

for index, row in df.iterrows():
    for topic, prob in row['topics']:
        df.at[index, f'topic_prob_{topic}'] = prob

# Additional features: Polarity shifts, advanced syntactic features, embedding aggregations, etc.
def compute_additional_features(text):
    doc = nlp(text)
    
    # Polarity shift detection
    sentiment_scores = sentiment_analyzer.polarity_scores(text)
    polarity_shift = abs(sentiment_scores['pos'] - sentiment_scores['neg'])
    
    # Embedding aggregation
    embedding = bert_model.encode([text])[0]
    mean_embedding = np.mean(embedding)
    max_embedding = np.max(embedding)
    min_embedding = np.min(embedding)
    
    return {
        "polarity_shift": polarity_shift,
        "mean_embedding": mean_embedding,
        "max_embedding": max_embedding,
        "min_embedding": min_embedding
    }

additional_features_df = df['full_text'].apply(compute_additional_features).apply(pd.Series)

# Concatenate all features
df = pd.concat([df, additional_features_df], axis=1)

In [ ]:

# Import necessary libraries
import pandas as pd
from itertools import combinations

# Assuming the DataFrame `df` and `score` are already defined
# and excluding irrelevant columns

# Calculate correlations with the target

cor = df.drop(columns=['essay_id', 'full_text', 'clean_text_x', 'clean_text_y', 'lowered' ,'processed_docs', 'topics', 'score'], axis=1)

correlations = cor.corrwith(df['score']).sort_values(ascending=False)



# Set a correlation threshold or select top N features
correlation_threshold = 0.3

top_features = correlations[abs(correlations) > correlation_threshold].index.tolist()

# Print the most correlated features
print("Top correlations with the score:")
print(top_features)

# Generate interaction terms between pairs of top features
for feature1, feature2 in combinations(top_features, 2):
    df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]


# Optional: print the list of created interaction terms
interaction_terms = [f'interaction_{feature1}_{feature2}' for feature1, feature2 in combinations(top_features, 2)]
print("Created interaction terms:")
print(interaction_terms)


# export top_features to text file

with open('/home/jack/github/kaggle/scoring/model_data/top_corelations.txt', 'w') as f:
    for item in top_features:
        f.write("%s\n" % item)

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
train = df.copy()

In [ ]:
# show columns with nan values greater than 0

nan_cols = train.isna().sum()

nan_cols = nan_cols[nan_cols > 0]

nan_cols

In [ ]:
def custom_train_validation_split(essays, test_size=0.2, random_state=56):
    
    """
    Custom function to perform train-validation split ensuring that
    the same prompt IDs are in both training and validation sets.

    Parameters:
    - summaries: DataFrame containing summaries and associated prompt_ids
    - prompts: DataFrame containing prompts and associated prompt_ids
    - test_size: Proportion of the dataset to be used as the validation set
    - random_state: Random seed for reproducibility

    Returns:
    - train_summaries: Training set containing summaries
    - validation_summaries: Validation set containing summaries
    - train_prompts: Training set containing prompts
    - validation_prompts: Validation set containing prompts
    """

    from sklearn.model_selection import train_test_split

    
    # Extract unique prompt IDs
    unique_essay_ids = essays['essay_id'].unique()

    # Split the unique prompt IDs into training and validation sets
    train_ids, validation_ids = train_test_split(unique_essay_ids, test_size=test_size, random_state=random_state)

    # Use these IDs to filter the original summaries and prompts DataFrames
    train_essays = essays[essays['essay_id'].isin(train_ids)]
    validation_essays = essays[essays['essay_id'].isin(validation_ids)]

    return train_essays, validation_essays

In [ ]:
train_essays, val_essays = custom_train_validation_split(train, test_size=0.25, random_state=42)

In [ ]:
train_essays.head()

In [ ]:
drop_cols = [ 'full_text', 'clean_text_x', 'clean_text_y','lowered', 
             'processed_docs', 'min_word_length', 
               'global_coherence', 'topics'] # ,'dep_min', 'ner_min', 'pos_min', 'combined_dense_vector']   


train_df = train_essays.copy()
val_df = val_essays.copy()

train_df.drop(columns=drop_cols, inplace= True)
val_df.drop(columns=drop_cols, inplace= True)

In [ ]:
train_df.head()

In [ ]:
feature_cols = []

for col in train_df.columns:
    if (col != 'essay_id') and (col != 'score'):
        feature_cols.append(col)

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pickle

# Assuming 'feature_cols' are defined elsewhere in your script

# Labels (stays the same)
train_labels = train_df['score']
val_labels = val_df['score']



# Features
train_features = train_df[feature_cols]
val_features = val_df[feature_cols]


# Initialize scaler
scaler = MinMaxScaler()

# Fit scaler to the original full training data
scaler.fit(train_features)

# Transform all datasets using the fitted scaler
train_feats_scaled = scaler.transform(train_features)
val_feats_scaled = scaler.transform(val_features)


# Save the scaler for later use
with open('/home/jack/github/kaggle/scoring/model_data/tf_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [ ]:
# Check if the file has been written correctly and is not empty
import os
scaler_path = '/home/jack/github/kaggle/scoring/model_data/tf_scaler.pkl'
if os.path.getsize(scaler_path) > 0:
    print(f"Scaler saved successfully in {scaler_path}.")
else:
    print(f"Failed to save scaler to {scaler_path}. File is empty.")

In [ ]:
import tensorflow as tf

# Assuming train_labels and val_labels are your label arrays with classes 1-6

train_labels_one_hot = tf.keras.utils.to_categorical(train_labels - 1, num_classes=6)
val_labels_one_hot = tf.keras.utils.to_categorical(val_labels - 1, num_classes=6)

In [ ]:
# Log shapes right before the fit call
print("Training features shape:", train_feats_scaled.shape)
print("Training labels shape:", train_labels_one_hot.shape)
print("Validation features shape:", val_feats_scaled.shape)
print("Validation labels shape:", val_labels_one_hot.shape)

In [ ]:
with open('/home/jack/github/kaggle/scoring/model_data/feature_cols.txt', 'w') as f:
    for item in feature_cols:
        f.write("%s\n" % item)

In [ ]:
# import tensorflow as tf

# train_class = tf.data.Dataset.from_tensor_slices((train_feats_scaled, 
#                                                 train_labels_one_hot)).batch(32)

# val_class = tf.data.Dataset.from_tensor_slices((val_feats_scaled, 
#                                               val_labels_one_hot)).batch(32)

In [ ]:
# from sklearn.utils import class_weight

# class_weights = class_weight.compute_class_weight('balanced', classes=np.unique(train_labels), y=train_labels)
# class_weights_dict = {i: weight for i, weight in enumerate(class_weights)}

# class_weights

In [ ]:
import tensorflow as tf
import numpy as np

def quadratic_weighted_kappa(y_true, y_pred):
    """
    Calculates the Quadratic Weighted Kappa (QWK) aka Cohen's Kappa with quadratic weights.
    
    Parameters:
    y_true (tensor): The ground truth labels as one-hot encoded vectors.
    y_pred (tensor): The predicted probability distributions.
    
    Returns:
    float: The QWK score.
    """
    # Convert predictions to class indices
    y_pred_classes = tf.argmax(y_pred, axis=-1)
    y_pred_one_hot = tf.one_hot(y_pred_classes, depth=y_true.shape[-1])

    # Calculate the confusion matrix
    confusion_matrix = tf.math.confusion_matrix(tf.argmax(y_true, axis=1), y_pred_classes, num_classes=y_true.shape[-1])

    # Normalize the confusion matrix
    confusion_matrix = tf.cast(confusion_matrix, dtype=tf.float32)
    confusion_matrix = confusion_matrix / tf.reduce_sum(confusion_matrix)

    # Calculate weights
    num_classes = tf.shape(confusion_matrix)[0]
    weights = tf.cast(tf.range(num_classes), dtype=tf.float32) / tf.cast(num_classes - 1, dtype=tf.float32)
    weights = tf.square(tf.expand_dims(weights, -1) - tf.expand_dims(weights, 0))

    # Calculate the observed and expected agreement
    observed = tf.reduce_sum(weights * confusion_matrix)
    expected = tf.reduce_sum(
        weights * tf.matmul(
            tf.reshape(tf.reduce_sum(confusion_matrix, axis=1), [-1, 1]),
            tf.reshape(tf.reduce_sum(confusion_matrix, axis=0), [1, -1])
        )
    )

    # Calculate the kappa score
    kappa = 1.0 - observed / expected
    return kappa

In [ ]:
import tensorflow as tf
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.optimizers import schedules, AdamW, RMSprop
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout, Input, Conv1D, GlobalAveragePooling1D, MultiHeadAttention, Reshape, LayerNormalization, Flatten

def build_classification_model(hp, input_shape=(train_feats_scaled.shape[1],)):

    n_hidden = hp.Int("n_hidden", min_value=0, max_value=8, default=2)  # number of hidden layers
    n_neurons = hp.Int("n_neurons", min_value=16, max_value=256)  # neurons in each hidden layer
    l2_reg = hp.Float("l2_reg", min_value=1e-6, max_value=1e-2, sampling="log")  # L2 regularization
    learning_rate = hp.Float("learning_rate", min_value=1e-4, max_value=1e-2, sampling="log")  # learning rate
    dropout_rate = hp.Float("dropout_rate", min_value=0.0, max_value=0.5, step=0.05)  # dropout rate
    n_attention_heads = hp.Int("n_attention_heads", min_value=2, max_value=8, step=1)  # attention heads

    optimizer_choice = hp.Choice("optimizer_choice", ['adam', 'sgd', 'RMSprop', 'Adagrad', 'Adadelta', 'Nadam', 'Ftrl', 'L-BFGS'])

    # Learning rate schedulers
    lr_schedule = schedules.ExponentialDecay(initial_learning_rate=learning_rate,
                                             decay_steps=10000,
                                             decay_rate=0.9)

    if optimizer_choice == 'adam':
        optimizer = AdamW(learning_rate=lr_schedule)
    elif optimizer_choice == 'sgd':
        optimizer = tf.keras.optimizers.SGD(learning_rate=lr_schedule)
    elif optimizer_choice == 'RMSprop':
        optimizer = RMSprop(learning_rate=lr_schedule)
    elif optimizer_choice == 'Adagrad':
        optimizer = tf.keras.optimizers.Adagrad(learning_rate=lr_schedule)
    elif optimizer_choice == 'Adadelta':
        optimizer = tf.keras.optimizers.Adadelta(learning_rate=lr_schedule)
    elif optimizer_choice == 'Nadam':
        optimizer = tf.keras.optimizers.Nadam(learning_rate=lr_schedule)
    else:
        optimizer = tf.keras.optimizers.Ftrl(learning_rate=lr_schedule)

    inputs = Input(shape=input_shape)
    x = Reshape((input_shape[0], 1))(inputs)  # Reshape to (batch_size, sequence_length, num_features)

    # Convolutional layer for feature extraction
    x = Conv1D(filters=n_neurons, kernel_size=3, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(l2_reg))(x)
    x = GlobalAveragePooling1D()(x)

    # Adding attention layer
    x = Reshape((1, -1))(x)  # Reshape to (batch_size, 1, n_neurons) for attention
    attention_output = MultiHeadAttention(num_heads=n_attention_heads, key_dim=x.shape[-1])(x, x)
    x = tf.keras.layers.Add()([x, attention_output])  # Residual connection
    x = LayerNormalization()(x)
    x = Flatten()(x)  # Always flatten before dense layers

    # Adding dense layers with Batch Normalization and Dropout
    for _ in range(n_hidden):
        x = Dense(n_neurons, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(l2_reg))(x)
        x = BatchNormalization()(x)
        x = Dropout(rate=dropout_rate)(x)

    outputs = Dense(6, activation='softmax')(x)

    model = tf.keras.Model(inputs, outputs)

    # Compile the model
    model.compile(optimizer=optimizer,
                  loss='categorical_crossentropy',
                  metrics=[
                      tf.keras.metrics.CategoricalAccuracy(),
                      tf.keras.metrics.AUC(curve='ROC', multi_label=True, num_labels=6),
                      tf.keras.metrics.Precision(name='precision'),
                      tf.keras.metrics.Recall(name='recall'),
                      #quadratic_weighted_kappa
                  ])

    return model

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
import keras_tuner as kt

model_checkpoint = ModelCheckpoint('data/models/best_standard_model_epoch.keras', 
                                   save_best_only=True, monitor='val_loss', mode='min')

early_stopping = EarlyStopping(monitor='val_loss', patience=5, 
                               restore_best_weights=True)

reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=1e-5)

callbacks = [model_checkpoint, early_stopping, reduce_lr]

tuner = kt.BayesianOptimization(
    build_classification_model,
    objective='val_loss',
    max_trials=20,
    num_initial_points=5,
    seed=1,
    overwrite=True,
    directory='data/models/tuner_2',
    project_name='standard',
)

tuner.search(train_feats_scaled, train_labels_one_hot, epochs=1000, 
             validation_data=(val_feats_scaled, val_labels_one_hot), callbacks=callbacks, verbose=2)

In [ ]:
best_standard_model = tuner.get_best_models(num_models=1)[0]

In [ ]:
best_standard_model.summary()

In [ ]:
# join the train and val data and then re  split with smaller val size

full_train = np.concatenate((train_feats_scaled, val_feats_scaled), axis=0)

full_labels = np.concatenate((train_labels_one_hot, val_labels_one_hot), axis=0)

In [ ]:
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
model = tuner.hypermodel.build(best_hps)
history = model.fit(full_train, full_labels, 
                    epochs=500, batch_size=32)

In [ ]:
import matplotlib.pyplot as plt

# Assuming you have a history object from model.fit()
plt.figure(figsize=(10, 5))
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

In [ ]:
# Evaluate the model on the validation dataset

results = model.evaluate(x = val_feats_scaled, y = val_labels_one_hot , verbose=0)

# Print all results

print(results)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Assuming val_reg is your validation dataset
# Extract true labels and convert from one-hot encoding to integer labels if necessary
y_true = val_labels

# Predict the classes with the best model on the validation data

y_pred = model.predict(val_feats_scaled)

y_pred_classes = np.argmax(y_pred, axis=1)  # Convert from probabilities to class labels

y_pred_classes = y_pred_classes + 1

In [ ]:
# Compute the confusion matrix

cm = confusion_matrix(y_true, y_pred_classes)
cm

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Generate and display the confusion matrix for the test predictions
cm = confusion_matrix(y_true, y_pred_classes, labels=sorted(val_labels.unique(), reverse=True))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=sorted(val_labels.unique(), reverse=False))
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

In [ ]:
print(sorted(val_labels.unique()))
print(sorted(pd.Series(y_pred_classes).unique()))

In [ ]:
from sklearn.metrics import cohen_kappa_score

# Calculate the Quadratic Weighted Kappa

qwk_score = cohen_kappa_score(y_true, y_pred_classes, weights='quadratic')

print("Quadratic Weighted Kappa score:", qwk_score)

In [ ]:
model.save('/home/jack/github/kaggle/scoring/model_data/best_classification_model.keras')