In [1]:
# ! python -m pip install --no-index --find-links=/kaggle/usr/lib/pip_install_permanent/my_packages -r /kaggle/usr/lib/pip_install_permanent/requirements.txt

In [2]:
# import os
# os.environ['PACKAGE_DIR'] = '/kaggle/usr/lib/pip_install_permanent'

In [3]:
from helper_func import *
# import helper_functions as hf
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string
from spellchecker import SpellChecker
from textblob import TextBlob
from multiprocessing import Pool
from tqdm import tqdm
import numpy as np
import pandas as pd
# Preprocessing
from nltk.tokenize import word_tokenize, sent_tokenize
import operator
from spellchecker import SpellChecker
from tqdm import tqdm  # Import tqdm
import re
import inflect
from wordsegment import load, segment
from nltk.corpus import words
word_list = set(words.words())
from spellchecker import SpellChecker

from tqdm.contrib.concurrent import process_map  # If this import fails, you might need to update tqdm

import multiprocessing
 
# Import Packages
# import shutup; shutup.please()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import keras_tuner as kt
import seaborn as sns

from nltk.corpus import stopwords, wordnet
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk import pos_tag, ne_chunk
from textblob import TextBlob

from textstat import flesch_reading_ease, smog_index

import spacy
from collections import Counter
from gensim import corpora, models
import pyLDAvis.gensim as gen
import pyLDAvis
import re

# Machine Learning & Data Preprocessing

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Deep Learning

from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Gensim
# from gensim.models import Word2Vec, KeyedVectors

# Progress bar
from tqdm import tqdm

# Keras Tuner
from keras_tuner.tuners import RandomSearch

# # Setting logging levels and environment variables
# tf.get_logger().setLevel(logging.ERROR)
# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

from textstat import flesch_reading_ease
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string
from spellchecker import SpellChecker
from textblob import TextBlob
from multiprocessing import Pool
from tqdm import tqdm
import numpy as np
import pandas as pd
# Preprocessing
from nltk.tokenize import word_tokenize, sent_tokenize
import operator
from spellchecker import SpellChecker
from tqdm import tqdm  # Import tqdm
import re
import inflect
from wordsegment import load, segment
from nltk.corpus import words
word_list = set(words.words())
print('Packages Instaled......')

2024-04-21 11:29:37.309773: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-21 11:29:37.339816: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-21 11:29:37.820250: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Packages Instaled......

[nltk_data] Downloading package punkt to /home/laptop/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/laptop/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/laptop/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/laptop/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [4]:
train = pd.read_csv('/home/laptop/github/kaggle/scoring/data/train.csv')

In [5]:
train

      essay_id                                          full_text  score
0      000d118  Many people have car where they live. The thin...      3
1      000fe60  I am a scientist at NASA that is discussing th...      3
2      001ab80  People always wish they had the same technolog...      4
3      001bdc0  We all heard about Venus, the planet without a...      4
4      002ba53  Dear, State Senator\n\nThis is a letter to arg...      3
...        ...                                                ...    ...
17302  ffd378d  the story " The Challenge of Exploing Venus " ...      2
17303  ffddf1f  Technology has changed a lot of ways that we l...      4
17304  fff016d  If you don't like sitting around all day than ...      2
17305  fffb49b  In "The Challenge of Exporing Venus," the auth...      1
17306  fffed3e  Venus is worthy place to study but dangerous. ...      2

[17307 rows x 3 columns]

In [6]:
import os

glove_path = '/home/laptop/github/kaggle/scoring/data/glove-840B-300d.txt'

paragram_path = '/home/laptop/github/kaggle/scoring/data/paragram-300-sl999.txt'

wiki_news_path = '/home/laptop/github/kaggle/scoring/data/wiki-news-1M-300d.vec'


# Load embeddings

embeddings = parallel_load_embeddings([glove_path, paragram_path, wiki_news_path])

# glove = embeddings["glove"]
# paragram = embeddings["paragram"]
# fasttext = embeddings["fasttext"]

Loading embeddings from /home/laptop/github/kaggle/scoring/data/paragram-300-sl999.txtLoading embeddings from /home/laptop/github/kaggle/scoring/data/glove-840B-300d.txtLoading embeddings from /home/laptop/github/kaggle/scoring/data/wiki-news-1M-300d.vec

Reading Embedding File: 999995it [00:39, 25192.38it/s]]

Loaded embeddings from /home/laptop/github/kaggle/scoring/data/wiki-news-1M-300d.vec

Reading Embedding File: 1703756it [00:54, 31227.66it/s]

Loaded embeddings from /home/laptop/github/kaggle/scoring/data/paragram-300-sl999.txt

Reading Embedding File: 2196017it [01:02, 35105.49it/s]

Loaded embeddings from /home/laptop/github/kaggle/scoring/data/glove-840B-300d.txt

In [7]:
train, glove, paragram, fastetxt = spellcheck_and_correct_text(train, embeddings)

Starting text cleaning process.

Mis-spelling Count.................

Checking Vocabulary.................

Processing dataset.
Building vocabulary.

Populating Vocabulary: 100%|██████████| 17307/17307 [00:00<00:00, 32947.65it/s]

Vocabulary built.
Checking coverage.

Checking Words: 100%|██████████| 65918/65918 [00:00<00:00, 1487395.93it/s]

Coverage checked.
Checking coverage.

Checking Words: 100%|██████████| 65918/65918 [00:00<00:00, 1728022.42it/s]

Coverage checked.
Checking coverage.

Checking Words: 100%|██████████| 65918/65918 [00:00<00:00, 2000796.98it/s]

Coverage checked.
Processed dataset.

  0%|          | 0/21 [00:00<?, ?it/s]

In [40]:
train.head()

,essay_id,full_text,score,lowered,clean_text,misspelling_count,corrected_text,segmented_text,dense_vec_0,dense_vec_1,...,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score
6927,67436ca,"In our modern age, cars have become one of the...",2,"in our modern age, cars have become one of the...",in our modern age cars have become one of the ...,4,in our modern age cars have become one of the ...,in our modern age cars have become one of the ...,-0.041480,0.162677,...,176,176.0,176,176,4.886364,14,1,-98.71,73.81,-0.7227
6928,6744a28,"""Imagine a computer that knows when you're hap...",4,"""imagine a computer that knows when you're hap...",imagine a computer that knows when you are hap...,3,imagine a computer that knows when you are hap...,imagine a computer that knows when you are hap...,0.031722,0.153669,...,370,370.0,370,370,4.613514,12,1,-295.62,150.16,0.9941
6929,6745144,I agree with the use of FACS in classrooms thi...,4,i agree with the use of facs in classrooms thi...,i agree with the use of facs in classrooms thi...,11,i agree with the use of fac s in classrooms th...,i agree with the use of fac s in classrooms th...,0.027120,0.071673,...,389,389.0,389,389,4.300771,13,1,-306.45,158.07,0.9866
6930,6745748,Automated cars are the future of driving.Drive...,2,automated cars are the future of driving.drive...,automated cars are the future of driving drive...,10,automated cars are the future of driving drive...,automated cars are the future of driving drive...,-0.059321,0.123377,...,291,291.0,291,291,4.302405,13,1,-198.52,117.91,-0.3740
6931,6747056,If people participated on joining the Seagoing...,2,if people participated on joining the seagoing...,if people participated on joining the seagoing...,4,if people participated on joining the seagoing...,if people participated on joining the seagoing...,0.008032,0.129010,...,271,271.0,271,271,4.199262,12,1,-169.76,108.84,0.7428

In [ ]:
glove

In [ ]:
len(train.columns)

In [57]:
train_essays, val_essays = custom_train_validation_split(train, test_size=0.25, random_state=42)

In [42]:
train_essays.to_parquet('train_essays.parquet')
val_essays.to_parquet('validation_essays.parquet')
train.to_parquet('train_(pre-split).parquet')

In [ ]:
# import pandas as pd

# train_essays = pd.read_parquet('/kaggle/working/train_essays.parquet')
# validation_essays = pd.read_parquet('/kaggle/working/validation_essays.parquet')

In [ ]:
def get_dense_vector(text, embeddings, embedding_type):
    """
    Compute a dense vector representation for a given text based on a specific embedding type.
    
    :param text: The text to convert to a dense vector.
    :param embeddings: Dictionary containing embedding objects for GloVe, Paragram, and FastText.
    :param embedding_type: The embedding type to use (e.g., 'glove', 'paragram', 'fasttext').
    :return: A dense vector representing the text.
    """
    words = text.split()
    word_vectors = []

    # Aggregate vectors for known words of the specific embedding type
    for word in words:
        if word in embeddings[embedding_type]:
            word_vectors.append(embeddings[embedding_type][word])

    # If there are no word vectors, return a zero vector
    if not word_vectors:
        return np.zeros(len(list(embeddings[embedding_type].values())[0]))

    # Return the mean of the word vectors as the dense vector representation
    return np.mean(word_vectors, axis=0)

In [ ]:
# Step 8: Add dense vector embeddings for each row of text as separate columns
dense_vectors = {
    'glove': test_df['corrected_text'].apply(lambda x: get_dense_vector(x, embeddings, 'glove')),
    'paragram': test_df['corrected_text'].apply(lambda x: get_dense_vector(x, embeddings, 'paragram')),
    'fasttext': test_df['corrected_text'].apply(lambda x: get_dense_vector(x, embeddings, 'fasttext'))
}

# Expand the dense vectors into separate columns for each embedding type
glove_df = pd.DataFrame(list(dense_vectors['glove']), columns=[f"glove_vec_{i}" for i in range(dense_vectors['glove'][0].size)])
paragram_df = pd.DataFrame(list(dense_vectors['paragram']), columns=[f"paragram_vec_{i}" for i in range(dense_vectors['paragram'][0].size)])
fasttext_df = pd.DataFrame(list(dense_vectors['fasttext']), columns=[f"fasttext_vec_{i}" for i in range(dense_vectors['fasttext'][0].size)])

# Concatenate these new DataFrames with the original DataFrame
test_df = pd.concat([test_df, glove_df, paragram_df, fasttext_df], axis=1)

In [58]:
import pandas as pd
from sklearn.utils import resample

def sample_df(df, col='score', sub=0, random_state=None):
    """
    Balances the classes in a DataFrame by resampling.
    
    Parameters:
    - df: DataFrame to be resampled.
    - col: The column name in df that contains class labels.
    - random_state: The random state for reproducibility.
    
    Returns:
    - balanced_df: A DataFrame with balanced classes.
    """
    class_counts = df[col].value_counts()
    target_count = max(int(class_counts.median()) - sub, class_counts.min())  # Ensure target_count is positive
    
    balanced_df = pd.DataFrame()

    for class_label in df[col].unique():
        class_subset = df[df[col] == class_label]
        
        if len(class_subset) > target_count:
            # Downsample majority classes
            class_subset = resample(class_subset,
                                    replace=False,
                                    n_samples=target_count,
                                    random_state=random_state)
        else:
            # Upsample minority classes
            class_subset = resample(class_subset,
                                    replace=True,
                                    n_samples=target_count,
                                    random_state=random_state)
        
        balanced_df = pd.concat([balanced_df, class_subset], axis=0)
    
    # Shuffle the DataFrame to mix the classes well
    balanced_df = balanced_df.sample(frac=1, random_state=random_state).reset_index(drop=True)

    return balanced_df

In [59]:
UPSAMPLE = True

if UPSAMPLE:
    
    # Balance only the training DataFrame
    train_essays = sample_df(train_essays, col='score', random_state=42, sub=0)

    
else:
    pass

In [60]:
print(train_essays['score'].value_counts())
print(val_essays['score'].value_counts())

score
2    1948
1    1948
4    1948
5    1948
3    1948
6    1948
Name: count, dtype: int64
score
3    1590
2    1176
4     987
1     295
5     242
6      37
Name: count, dtype: int64

In [61]:
train_essays.columns

Index(['essay_id', 'full_text', 'score', 'lowered', 'clean_text',
       'misspelling_count', 'corrected_text', 'segmented_text', 'dense_vec_0',
       'dense_vec_1',
       ...
       'min_paragraph_length', 'avg_sentence_length', 'max_sentence_length',
       'min_sentence_length', 'avg_word_length', 'max_word_length',
       'min_word_length', 'flesch_reading_ease', 'gunning_fog_index',
       'sentiment_score'],
      dtype='object', length=323)

In [62]:
drop_cols = [ 'full_text', 'lowered', 'clean_text','corrected_text', 'segmented_text']


train_df = train_essays.copy()
val_df = val_essays.copy()

train_df.drop(columns=drop_cols, inplace= True)
val_df.drop(columns=drop_cols, inplace= True)

In [63]:
feature_cols = []

for col in train_df.columns:
    if (col != 'essay_id') and (col != 'score'):
        feature_cols.append(col)

In [64]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pickle

# Assuming 'feature_cols' are defined elsewhere in your script

# Labels (stays the same)
train_labels = train_df['score']
val_labels = val_df['score']



# Features
train_features = train_df[feature_cols]
val_features = val_df[feature_cols]


# Initialize scaler
scaler = MinMaxScaler()

# Fit scaler to the original full training data
scaler.fit(train_features)

# Transform all datasets using the fitted scaler
train_feats_scaled = scaler.transform(train_features)
val_feats_scaled = scaler.transform(val_features)


# Save the scaler for later use
with open('tf_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [65]:
# Check if the file has been written correctly and is not empty
import os
scaler_path = 'tf_scaler.pkl'
if os.path.getsize(scaler_path) > 0:
    print(f"Scaler saved successfully in {scaler_path}.")
else:
    print(f"Failed to save scaler to {scaler_path}. File is empty.")

Scaler saved successfully in tf_scaler.pkl.

In [66]:
import tensorflow as tf

# Assuming train_labels and val_labels are your label arrays with classes 1-6

train_labels_one_hot = tf.keras.utils.to_categorical(train_labels - 1, num_classes=6)
val_labels_one_hot = tf.keras.utils.to_categorical(val_labels - 1, num_classes=6)

In [67]:
# Log shapes right before the fit call
print("Training features shape:", train_feats_scaled.shape)
print("Training labels shape:", train_labels_one_hot.shape)
print("Validation features shape:", val_feats_scaled.shape)
print("Validation labels shape:", val_labels_one_hot.shape)

Training features shape: (11688, 316)
Training labels shape: (11688, 6)
Validation features shape: (4327, 316)
Validation labels shape: (4327, 6)

In [68]:
# import tensorflow as tf

# train_class = tf.data.Dataset.from_tensor_slices((train_feats_scaled, 
#                                                 train_labels_one_hot)).batch(32)

# val_class = tf.data.Dataset.from_tensor_slices((val_feats_scaled, 
#                                               val_labels_one_hot)).batch(32)

In [69]:
# from sklearn.utils import class_weight

# class_weights = class_weight.compute_class_weight('balanced', classes=np.unique(train_labels), y=train_labels)
# class_weights_dict = {i: weight for i, weight in enumerate(class_weights)}

# class_weights

In [70]:
import tensorflow as tf
import numpy as np

def quadratic_weighted_kappa(y_true, y_pred):
    """
    Calculates the Quadratic Weighted Kappa (QWK) aka Cohen's Kappa with quadratic weights.
    
    Parameters:
    y_true (tensor): The ground truth labels as one-hot encoded vectors.
    y_pred (tensor): The predicted probability distributions.
    
    Returns:
    float: The QWK score.
    """
    # Convert predictions to class indices
    y_pred_classes = tf.argmax(y_pred, axis=-1)
    y_pred_one_hot = tf.one_hot(y_pred_classes, depth=y_true.shape[-1])

    # Calculate the confusion matrix
    confusion_matrix = tf.math.confusion_matrix(tf.argmax(y_true, axis=1), y_pred_classes, num_classes=y_true.shape[-1])

    # Normalize the confusion matrix
    confusion_matrix = tf.cast(confusion_matrix, dtype=tf.float32)
    confusion_matrix = confusion_matrix / tf.reduce_sum(confusion_matrix)

    # Calculate weights
    num_classes = tf.shape(confusion_matrix)[0]
    weights = tf.cast(tf.range(num_classes), dtype=tf.float32) / tf.cast(num_classes - 1, dtype=tf.float32)
    weights = tf.square(tf.expand_dims(weights, -1) - tf.expand_dims(weights, 0))

    # Calculate the observed and expected agreement
    observed = tf.reduce_sum(weights * confusion_matrix)
    expected = tf.reduce_sum(
        weights * tf.matmul(
            tf.reshape(tf.reduce_sum(confusion_matrix, axis=1), [-1, 1]),
            tf.reshape(tf.reduce_sum(confusion_matrix, axis=0), [1, -1])
        )
    )

    # Calculate the kappa score
    kappa = 1.0 - observed / expected
    return kappa

In [71]:
import tensorflow as tf
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.optimizers import schedules, AdamW, RMSprop

def build_classification_model(hp, input_shape=(train_feats_scaled.shape[1],)):
    
    n_hidden = hp.Int("n_hidden", min_value=0, max_value=8, default=2)  # number of hidden layers
    n_neurons = hp.Int("n_neurons", min_value=16, max_value=256)  # neurons in each hidden layer
    l2_reg = hp.Float("l2_reg", min_value=1e-6, max_value=1e-2, sampling="log")  # L2 regularization
    learning_rate = hp.Float("learning_rate", min_value=1e-4, max_value=1e-2, sampling="log")  # learning rate

    optimizer_choice = hp.Choice("optimizer_choice", ['adam', 'sgd', 'RMSprop', 'Adagrad', 'Adadelta', 'Nadam', 'Ftrl', 'L-BFGS'])

    # Learning rate schedulers
    lr_schedule = schedules.ExponentialDecay(initial_learning_rate=learning_rate,
                                             decay_steps=10000,
                                             decay_rate=0.9)

    if optimizer_choice == 'adam':
        optimizer = AdamW(learning_rate=lr_schedule)
    elif optimizer_choice == 'sgd':
        optimizer = tf.keras.optimizers.SGD(learning_rate=lr_schedule)
    elif optimizer_choice == 'RMSprop':
        optimizer = RMSprop(learning_rate=lr_schedule)
    elif optimizer_choice == 'Adagrad':
        optimizer = tf.keras.optimizers.Adagrad(learning_rate=lr_schedule)
    elif optimizer_choice == 'Adadelta':
        optimizer = tf.keras.optimizers.Adadelta(learning_rate=lr_schedule)
    elif optimizer_choice == 'Nadam':
        optimizer = tf.keras.optimizers.Nadam(learning_rate=lr_schedule)
    else:
        optimizer = tf.keras.optimizers.Ftrl(learning_rate=lr_schedule)

    model = tf.keras.models.Sequential()

    # Input layer
    model.add(tf.keras.Input(shape=input_shape))  # Explicit input layer

    model.add(tf.keras.layers.Dense(n_neurons, 
                                    activation='relu', 
                                    kernel_regularizer=tf.keras.regularizers.l2(l2_reg)))

    dropout_rate = hp.Float("dropout_rate", min_value=0.0, max_value=0.5, step=0.05)  # dropout rate

    # Hidden layers with Batch Normalization and Dropout
    for _ in range(n_hidden):
        model.add(tf.keras.layers.BatchNormalization())
        
        model.add(tf.keras.layers.Dense(n_neurons, 
                                        activation='relu', 
                                        kernel_regularizer=tf.keras.regularizers.l2(l2_reg)))
        
        model.add(tf.keras.layers.Dropout(rate=dropout_rate))

    # Output layer for 6 classes
    model.add(tf.keras.layers.Dense(6, activation='softmax'))
    
    
    
#     from tensorflow.keras.metrics import AUC

#     # For binary classification
#     roc_auc = AUC(curve='ROC')

#     # For multi-class classification (assuming one-vs-all approach)
#     roc_auc_multi = AUC(curve='ROC', multi_label=True, num_labels=6)




    # Then, you can add it to your model's compile method as a metric
    model.compile(optimizer=optimizer,
              loss='categorical_crossentropy',
              metrics=[ 
                       tf.keras.metrics.CategoricalAccuracy(),
                       tf.keras.metrics.F1Score( average='weighted'),
                       tf.keras.metrics.AUC(curve='ROC', multi_label=True, num_labels=6),
                       quadratic_weighted_kappa])


    # Learning rate reduction callback
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=1e-5)

    return model



from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
import keras_tuner as kt

model_checkpoint = ModelCheckpoint('data/models/best_standard_model_epoch.keras', 
                                   save_best_only=True, monitor='val_loss', mode='min')

early_stopping = EarlyStopping(monitor='val_loss', patience=5, 
                               restore_best_weights=True)

call_backs = [model_checkpoint, early_stopping]

tuner = kt.BayesianOptimization(
    build_classification_model,
    objective='val_loss',
    max_trials=20,
    num_initial_points= 5,
    seed=1,
    overwrite=True,
    directory='data/models/tuner_2',
    project_name='standard',
)

tuner.search(train_feats_scaled, train_labels_one_hot, epochs=1000, 
             validation_data= (val_feats_scaled, val_labels_one_hot), callbacks = call_backs, verbose=2)      # class_weight=class_weights_dict,

Trial 16 Complete [00h 00m 16s]
val_loss: 1.223796010017395

Best val_loss So Far: 1.223796010017395
Total elapsed time: 00h 10m 08s

Search: Running Trial #17

Value             |Best Value So Far |Hyperparameter
6                 |5                 |n_hidden
16                |185               |n_neurons
1e-06             |1e-06             |l2_reg
0.0057195         |0.01              |learning_rate
Adadelta          |RMSprop           |optimizer_choice
0.05              |0                 |dropout_rate

Epoch 1/1000
366/366 - 5s - 13ms/step - auc: 0.4911 - categorical_accuracy: 0.1650 - f1_score: 0.1406 - loss: 2.0463 - quadratic_weighted_kappa: -4.4719e-03 - val_auc: 0.4957 - val_categorical_accuracy: 0.0700 - val_f1_score: 0.0616 - val_loss: 2.0610 - val_quadratic_weighted_kappa: -3.6809e-03
Epoch 2/1000
366/366 - 1s - 2ms/step - auc: 0.4952 - categorical_accuracy: 0.1658 - f1_score: 0.1420 - loss: 2.0208 - quadratic_weighted_kappa: 4.1241e-04 - val_auc: 0.4895 - val_categorical_accuracy: 0.0911 - val_f1_score: 0.0826 - val_loss: 2.1188 - val_quadratic_weighted_kappa: 0.0106
Epoch 3/1000
366/366 - 1s - 2ms/step - auc: 0.4936 - categorical_accuracy: 0.1691 - f1_score: 0.1466 - loss: 2.0202 - quadratic_weighted_kappa: 0.0019 - val_auc: 0.4889 - val_categorical_accuracy: 0.0929 - val_f1_score: 0.0875 - val_loss: 2.0975 - val_quadratic_weighted_kappa: 0.0100
Epoch 4/1000
366/366 - 1s - 2ms/step - auc: 0.4995 - categorical_accuracy: 0.1731 - f1_score: 0.1494 - loss: 1.9967 - quadratic_weighted_kappa: 0.0199 - val_auc: 0.4900 - val_categorical_accuracy: 0.0881 - val_f1_score: 0.0844 - val_loss: 2.0870 - val_quadratic_weighted_kappa: 0.0111
Epoch 5/1000
366/366 - 1s - 2ms/step - auc: 0.4984 - categorical_accuracy: 0.1633 - f1_score: 0.1421 - loss: 1.9889 - quadratic_weighted_kappa: 0.0163 - val_auc: 0.4928 - val_categorical_accuracy: 0.0913 - val_f1_score: 0.0888 - val_loss: 2.0806 - val_quadratic_weighted_kappa: 0.0115
Epoch 6/1000
366/366 - 1s - 2ms/step - auc: 0.5028 - categorical_accuracy: 0.1703 - f1_score: 0.1494 - loss: 1.9770 - quadratic_weighted_kappa: 0.0274 - val_auc: 0.4957 - val_categorical_accuracy: 0.0985 - val_f1_score: 0.0980 - val_loss: 2.0596 - val_quadratic_weighted_kappa: 0.0182
Epoch 7/1000
366/366 - 1s - 2ms/step - auc: 0.5032 - categorical_accuracy: 0.1700 - f1_score: 0.1493 - loss: 1.9715 - quadratic_weighted_kappa: 0.0217 - val_auc: 0.4988 - val_categorical_accuracy: 0.0950 - val_f1_score: 0.0920 - val_loss: 2.0509 - val_quadratic_weighted_kappa: 0.0235
Epoch 8/1000
366/366 - 1s - 2ms/step - auc: 0.5056 - categorical_accuracy: 0.1727 - f1_score: 0.1528 - loss: 1.9668 - quadratic_weighted_kappa: 0.0307 - val_auc: 0.5008 - val_categorical_accuracy: 0.0950 - val_f1_score: 0.0941 - val_loss: 2.0458 - val_quadratic_weighted_kappa: 0.0162
Epoch 9/1000
366/366 - 1s - 2ms/step - auc: 0.5024 - categorical_accuracy: 0.1698 - f1_score: 0.1494 - loss: 1.9648 - quadratic_weighted_kappa: 0.0330 - val_auc: 0.5023 - val_categorical_accuracy: 0.0948 - val_f1_score: 0.0941 - val_loss: 2.0347 - val_quadratic_weighted_kappa: 0.0197
Epoch 10/1000
366/366 - 1s - 2ms/step - auc: 0.5118 - categorical_accuracy: 0.1771 - f1_score: 0.1569 - loss: 1.9418 - quadratic_weighted_kappa: 0.0247 - val_auc: 0.5053 - val_categorical_accuracy: 0.0978 - val_f1_score: 0.0984 - val_loss: 2.0155 - val_quadratic_weighted_kappa: 0.0315
Epoch 11/1000
366/366 - 1s - 2ms/step - auc: 0.5103 - categorical_accuracy: 0.1755 - f1_score: 0.1566 - loss: 1.9351 - quadratic_weighted_kappa: 0.0481 - val_auc: 0.5056 - val_categorical_accuracy: 0.0978 - val_f1_score: 0.0988 - val_loss: 2.0094 - val_quadratic_weighted_kappa: 0.0258
Epoch 12/1000
366/366 - 1s - 2ms/step - auc: 0.5172 - categorical_accuracy: 0.1868 - f1_score: 0.1675 - loss: 1.9242 - quadratic_weighted_kappa: 0.0597 - val_auc: 0.5087 - val_categorical_accuracy: 0.0973 - val_f1_score: 0.1025 - val_loss: 1.9989 - val_quadratic_weighted_kappa: 0.0263
Epoch 13/1000

In [ ]:
best_standard_model = tuner.get_best_models(num_models=1)[0]

In [ ]:
best_standard_model.summary()

In [ ]:
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
model = tuner.hypermodel.build(best_hps)
history = model.fit(train_feats_scaled, train_labels_one_hot, 
                    epochs=1000, batch_size=32, 
                    callbacks = call_backs, verbose=2, validation_data= (val_feats_scaled, val_labels_one_hot))

In [ ]:
import matplotlib.pyplot as plt

# Assuming you have a history object from model.fit()
plt.figure(figsize=(10, 5))
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

In [ ]:
# Evaluate the model on the validation dataset

results = model.evaluate(x = val_feats_scaled, y = val_labels_one_hot , verbose=0)

# Print all results

print(results)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Assuming val_reg is your validation dataset
# Extract true labels and convert from one-hot encoding to integer labels if necessary
y_true = np.argmax(val_labels_one_hot, axis=1)


if y_true.ndim > 1 and y_true.shape[1] > 1:  # Check if y_true is one-hot encoded
    y_true = np.argmax(y_true, axis=1)

# Predict the classes with the best model on the validation data

y_pred = model.predict(val_feats_scaled)

y_pred_classes = np.argmax(y_pred, axis=1)  # Convert from probabilities to class labels

y_pred_classes = y_pred_classes + 1

In [ ]:
# Compute the confusion matrix

cm = confusion_matrix(y_true, y_pred_classes)

In [ ]:
# Plotting the confusion matrix
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

In [ ]:
print(sorted(val_labels.unique()))
print(sorted(pd.Series(y_pred_classes).unique()))

In [ ]:
from sklearn.metrics import cohen_kappa_score

# Calculate the Quadratic Weighted Kappa

qwk_score = cohen_kappa_score(y_true, y_pred_classes, weights='quadratic')

print("Quadratic Weighted Kappa score:", qwk_score)

In [ ]:
model.save('best_classification_model.keras')

# Train on full unbalanced data

In [ ]:
print(full_train_feats_scaled.shape, full_train_labels_one_hot.shape)
print(sampled_train_feats_scaled.shape,sampled_train_labels_one_hot.shape)

In [ ]:
# best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

full_model = tuner.hypermodel.build(best_hps)
full_history = model.fit(full_train_feats_scaled, full_train_labels_one_hot, 
                    epochs=1000, batch_size=32, 
                    callbacks = call_backs, verbose=2, validation_data= (full_val_feats_scaled, full_val_labels_one_hot))

In [ ]:
import matplotlib.pyplot as plt

# Assuming you have a history object from model.fit()

plt.figure(figsize=(10, 5))
plt.plot(full_history.history['loss'], label='Training Loss')
plt.plot(full_history.history['val_loss'], label='Validation Loss')
plt.title('Model Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

In [ ]:
# Evaluate the model on the validation dataset

full_results = full_model.evaluate(x = full_val_feats_scaled, y = full_val_labels_one_hot , verbose=0)

# Print all results

print(results)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Assuming val_reg is your validation dataset

# Extract true labels and convert from one-hot encoding to integer labels if necessary
full_y_true = np.argmax(full_val_labels_one_hot, axis=1)

if full_y_true.ndim > 1 and full_y_true.shape[1] > 1:  # Check if y_true is one-hot encoded
    full_y_true = np.argmax(full_y_true, axis=1)

# Predict the classes with the best model on the validation data

full_y_pred = full_model.predict(full_val_feats_scaled)

full_y_pred_classes = np.argmax(full_y_pred, axis=1)  # Convert from probabilities to class labels

# Compute the confusion matrix
full_cm = confusion_matrix(full_y_true, full_y_pred_classes)

# Plotting the confusion matrix
plt.figure(figsize=(10, 7))
sns.heatmap(full_cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

In [ ]:
full_model.save('full_best_classification_model.keras')